### ISSUE TITLE
`spack compiler find` broken, `spack compiler add` no longer accepts paths

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1071]
Just merged to the latest develop.
```
$ spack compiler find
Traceback (most recent call last):
  File "/soft/spack/bin/spack", line 179, in <module>
    main()
  File "/soft/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/blues/gpfs/home/software/spack/lib/spack/spack/cmd/compiler.py", line 145, in compiler
    action[args.compiler_command](args)
KeyError: 'find'
$ spack compiler add
==> Found no new compilers
$ spack compiler add /soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/gcc-6.1.0-q2zosj3igepi3pjnqt74bwazmptr5gpj
Traceback (most recent call last):
  File "/soft/spack/bin/spack", line 179, in <module>
    main()
  File "/soft/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/blues/gpfs/home/software/spack/lib/spack/spack/cmd/compiler.py", line 145, in compiler
    action[args.compiler_command](args)
  File "/blues/gpfs/home/software/spack/lib/spack/spack/cmd/compiler.py", line 79, in compiler_add
    compilers = [c for c in spack.compilers.find_compilers(*args.add_paths)
TypeError: find_compilers() takes no arguments (1 given)
```
It seems that `spack compiler find` is no longer a valid alias? And `spack compiler add` no longer accepts paths?

**Comment by adamjstewart** [comment]
It's also no longer picking up gfortran on CentOS 6???
```yaml
compilers:
- compiler:
    modules: []
    operating_system: centos6
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: null
      fc: null
    spec: gcc@4.4.7
```

**Comment by adamjstewart** [comment]
Just looked at lib/spack/spack/cmd/compiler.py and the alias was indeed removed. Looks like a bad merge.

**Comment by adamjstewart** [comment]
Spack no longer picks up gfortran on Fedora 23 as well.

**Comment by mathstuf** [comment]
Looks like a bad merge conflict resolution in 9f59c128bec12baede054bf54b9afc69b2130d. @becker33?

**Comment by tgamblin** [comment]
Should be fixed now -- can you guys verify?

**Comment by adamjstewart** [comment]
It appears to be partially fixed. `spack compiler find` and `spack compiler add` both exist and accept a path. However, it still doesn't pick up gfortran. And it isn't telling me when it finds a new compiler.
```bash
[11:40:28] ajstewart@mcswl143:~/.spack
$ spack config get compilers
compilers: []
[11:40:35] ajstewart@mcswl143:~/.spack
$ spack compiler add
==> Found no new compilers
[11:40:43] ajstewart@mcswl143:~/.spack
$ spack config get compilers
compilers:
- compiler:
    modules: []
    operating_system: fedora23
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: null
      fc: null
    spec: gcc@5.3.1
[11:40:45] ajstewart@mcswl143:~/.spack
$ spack compiler remove gcc
==> Removed compiler gcc@5.3.1
[11:40:54] ajstewart@mcswl143:~/.spack
$ spack config get compilers
compilers: []
[11:40:56] ajstewart@mcswl143:~/.spack
$ spack compiler find /usr/bin
==> Found no new compilers
[11:41:05] ajstewart@mcswl143:~/.spack
$ spack config get compilers
compilers:
- compiler:
    modules: []
    operating_system: fedora23
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: null
      fc: null
    spec: gcc@5.3.1
```
