### ISSUE TITLE
Problem installing Python 2.7.11

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1100]
Surprisingly, I'm having problems installing Python 2.7.11 with Spack (CentOS 7).  I have no problems with python@3:

```
$ spack install python@2.7:2.8
```

results in...

```
ux-x86_64/gcc-4.9.3/netcdf-4.4.0-rx32ppcgwsxk2fxbexopuwk3xvtvrqbd/lib:/home2/rpfische/spack/opt/spack/linux-x86_64/gcc-4.9.3/git-2.8.1-jacg3hncs6kq6gt5ctbjayu64lbnsaxv/lib64 ./python -E -S -m sysconfig --generate-posix-vars ;\
if test $? -ne 0 ; then \
    echo "generate-posix-vars failed" ; \
    rm -f ./pybuilddir.txt ; \
    exit 1 ; \
fi
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/sysconfig.py", line 636, in <module>
    _main()
  File "/usr/lib64/python2.7/sysconfig.py", line 624, in _main
    _generate_posix_vars()
  File "/usr/lib64/python2.7/sysconfig.py", line 304, in _generate_posix_vars
    raise IOError(msg)
IOError: invalid Python installation: unable to open /tmp/rpfische/spack-stage/spack-stage-8orwGQ/Python-2.7.11/pyconfig-64.h (No such file or directory)
generate-posix-vars failed
make: *** [pybuilddir.txt] Error 1
```

Enclosed is the full build log; does anyone know why this might be happening?

[spack_build.txt](https://github.com/LLNL/spack/files/328887/spack_build.txt)

**Comment by alalazo** [comment]
This seems a regression (if it ever was solved at some point) on an old issue of yours #860

**Comment by citibeth** [comment]
Thanks... Yes, it looks like the problem is still there.

**Comment by jesslinn** [comment]
I had the same problem building Python-2.7.12 with spack-0.9.1.  The problem is noticed when the system python is version 2.7.5 or less which has the pyconfig-64.h file.  

The problem is caused because $SPACK_ROOT/lib/spack/env/cc adds libraries of dependencies to the rpath including /usr/lib and /usr/lib64.  The python install script sets the LD_LIBRARY_PATH to the build directory in order to pick up the newly generated python libraries, but with /usr/lib64 in the rpath, the system `libpython2.7`.so is found instead.

Assuming that one never wants to add /usr/lib or /usr/lib64 to the rpath of an executable, one fix/workaraound is to  not add system dependencies to the rpath in the cc wrapper script (e.g. ` [ ${dep} == '/usr' ] && continue ]` in the dependency loop.

**Comment by alalazo** [comment]
@jesslinn I think this has been solved in `develop` precisely in the way you suggested! :smile: 

Also, for your information, there will be a new release soon with this and a lot more other changes / bugfixes (see project v 0.10).

**Comment by jesslinn** [comment]
Thanks. I actually am using develop 592df25 fresh as of yesterday, so it is not fixed there.

On reflection it might be better not to add rpaths for any non-spack generated dependency, rather than singling out /usr.

**Comment by alalazo** [comment]
> The problem is caused because $SPACK_ROOT/lib/spack/env/cc adds libraries of dependencies to the rpath including /usr/lib and /usr/lib64.

I thought this shouldn't happen since #2083, I'll try to see tomorrow if I can reproduce the issue. Which OS are you on?

**Comment by jesslinn** [comment]
rhel7 and ol7

**Comment by citibeth** [comment]
Yes, my Python 2.7 problems are on CentOS7 also.

**Comment by jesslinn** [comment]
/usr was getting injected into my dependency list because of taking the recommendation in (Spack) Getting Started to use the system's openssl:

```yaml
packages:
    openssl:
        paths:
            openssl@system: /usr
        version: [system]
        buildable: False
```
So one way to hide the underlying problem is just to let spack build openssl.

The reason that `filter_system_paths` from  [#2083](https://github.com/LLNL/spack/pull/2083) does not work for cleaning up dependencies is that it combines ` ['/', '/usr', '/usr/local']` with `['lib', 'lib64', 'include']` and removes those paths.  The dep_prefixes list only has the dependency prefixes in it (`/usr` in this case) so these are not removed and can cause problems when cc adds -L and -I flags built from them.

A hack fix would be to add '/usr' to the `system_dirs` that get removed by filter_system_paths.  This works fine for this case where the compiler/loader will already look in /usr for things it does not find.   Removing /usr/local dependencies seems more problematic since a site might well want to specify a dependency on a /usr/local package rather than build it.  Rather than remove such paths entirely, it might be better to sort the dependency list, with spack dependencies first and os dependencies later.

**Comment by citibeth** [comment]
Tell spack that openssl is in '/fakepath', does that fix the problem?

**Comment by davydden** [comment]
> The reason that filter_system_paths from #2083 does not work for cleaning up dependencies is that it combines ['/', '/usr', '/usr/local'] with ['lib', 'lib64', 'include'] and removes those paths. The dep_prefixes list only has the dependency prefixes in it (/usr in this case) so these are not removed and can cause problems when cc adds -L and -I flags built from them.

you are right, this needs to be fixed. 

The right way to fix this may not be by adding workarounds to filter `/usr/ `from `prefix`, but adjusting compiler wrappers so that instead of`prefix`-es they use `prefix/lib` and `prefix/include`. I don't know details of wrappers, but I see no reasons why `SPACK_DEPENDENCIES`, `SPACK_RPATH_DEPS` and `SPACK_LINK_DEPS` have to be `prefix`es.

Otherwise I am happy to adjust `filter_system_paths()` so that it also removes plain `/` and `/usr` prefixes.

@alalazo @tgamblin thoughts?

**Comment by jesslinn** [comment]
@davydden  I don't think the essential problem comes from using prefix or prefix/lib and prefix/include although you are right that it would be another way to fix the current symptom .  The deeper problem comes up whenever a general install prefix is used for multiple dependencies from outside of spack (e.g. /usr or /usr/local).  If one wants to use package1 (openssl) from such a location but not package2 (python) that is also installed there, then it is necessary for the packge2 replacement paths to come first on the compile/link line.  If you remove  /usr/local paths in filter_system_paths, then a dependency from there will not be found.  This is why I was wondering if it might not be better to sort the paths.

**Comment by davydden** [comment]
>  If you remove /usr/local paths in filter_system_paths, then a dependency from there will not be found.

i think we just need to avoid using prefixes of `/usr/local/` and that's why: When you do `/usr` or `/`, then during linking `/usr/lib` and `/lib` will be found no problem AFAIC (so no issues with removing such prefixes), however if you say that `/usr/local/lib` won't be found automatically, then sorting this prefix won't help here because you may be breaking the following linking chain: `package-in-local-lib -> package-in-spack`, where you would anyway be in troubles as symbols for `package-in-spack` contained in `package-in-local-lib` won't be found when order of libs is changed.
Consequently, i don't think sorting is an ultimate solution.

I will adjust `filter_system_paths` to filter pure prefixes such as `/usr` and `/`....

**Comment by jesslinn** [comment]
I completely agree that it is best not to build with packages that use `/usr/local` as a prefix.

The dep_prefixes are currently sorted alphabetically by package name.  My only point was that if, instead of removing a `/usr/local` path completely, it were moved to the end of the list, then if someone happened to specify `packagename@system: /usr/local` in packages.yaml, it would work the way a dependency on `/usr` will work after your PR is merged.   This seems slightly better than quietly ignoring a user-specified system dependency which might get silently replaced by a version from `/lib` or `/usr/lib`.

**Comment by davydden** [comment]
> The dep_prefixes are currently sorted alphabetically by package name.

Looking at 
```
dep_prefixes = [d.prefix for d in
                      pkg.spec.traverse(root=False, deptype=('build', 'link'))]
```
i very much doubt this is indeed the case. In other words, they must be related to the DAG we build, and not just something random/alphabetical.

> My only point was that..

With due respect I perfectly understand your point, I just do NOT agree that this is the right approach because packages depend on one another and order of the libraries in the link line is important. See my comment above https://github.com/LLNL/spack/issues/1100#issuecomment-269044856

**Comment by davydden** [comment]
@jesslinn If you have an alternative solution, please create a PR. I am not a maintainer of Spack so I do not decide what is merged and what isn't.

**Comment by citibeth** [comment]
> you may be breaking the following linking chain: package-in-local-lib -> package-in-spack, where you would anyway be in troubles as symbols used in package-in-spack contained in package-in-local-lib won't be found when order of libs is changed.
> Consequently, i don't think sorting is an ultimate solution.

So we have a situation here where C->B->A.  C and A are built with Spack, but B is not.  That's not a use case I'm particularly interested in supporting.

I am of the opinion that paths already built-in to the compiler should not be specified again as -I or -L.  But paths not built-in should be.  Apparently, what is / is not included by default varies between compilers:

https://www.google.com/search?q=gcc+is+%2Fusr%2Flocal+included+audomatically

We already know that paths containing more than one package can be problematic, and can "pollute" the build with packages we don't want.  If such paths were automatically included by the compiler, they are put at the end.  Does it make sense to also put multi-package paths not included by the compiler at the end, too?   That would seem to be consistent.

This brings up the question of how to tell single-package from multi-package paths.  I might suggest the following heuristics:

 1. If it's Spack-installed, it's single-package.
 2. If it's a standard system path (/, /usr, /usr/local, etc.) assume multi-package.
 3. If neither (1) or (2), assume multi-package; unless we're told otherwise by the user in some configuration file (`packages.yaml` or somewhere else?)

Note that (3) is the biggest departure from current practice; where we currently act like all user-supplied paths in `packages.yaml` are single-package.

**Comment by citibeth** [comment]
> My only point was that if, instead of removing a `/usr/local` path completely, it were moved to the end of the list...

My brief research above indicates that removing `/usr/local` won't work at all with Clang.

> then if someone happened to specify packagename@system: /usr/local in packages.yaml, it would work the way a dependency on /usr will work after your PR is merged. This seems slightly better than quietly ignoring a user-specified system dependency which might get silently replaced by a version from /lib or /usr/lib.

How do you know that's not already the case (with GCC at least)?  I believe GCC seraches `/usr/local` before any other system directories:

https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html

**Comment by davydden** [comment]
> Apparently, what is / is not included by default varies between compilers:

One can check `$cpp -v` to see which folders are searched for by pre-processor.

So for Apple's `clang` it has: 
```
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
```
whereas `$ ~/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-yuzfgyrrvsnlutzrys2hwgbr47km7cql/bin/cpp -v` says
```
#include <...> search starts here:
 /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-yuzfgyrrvsnlutzrys2hwgbr47km7cql/lib64/gcc/x86_64-apple-darwin16.1.0/6.2.0/include
 /usr/local/include
 /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-yuzfgyrrvsnlutzrys2hwgbr47km7cql/include
 /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gcc-6.2.0-yuzfgyrrvsnlutzrys2hwgbr47km7cql/lib64/gcc/x86_64-apple-darwin16.1.0/6.2.0/include-fixed
 /usr/include
 /System/Library/Frameworks
 /Library/Frameworks
End of search list.
```

So at least on macOS (I am away from Ubuntu at the moment, so can't test), both `/usr/local` and `/usr` are searched for. Also no huge difference between the two lists or their order as far as `/usr` and `/usr/local` are concerned. So I am not sure what @citibeth means by

> My brief research above indicates that removing /usr/local won't work at all with Clang.

AFAICT it should work as expected and filtering it out shall not harm anything, but instead will make sure that all Spack-ed dependencies are properly picked up instead of, possibly, those provided by other sources (system, other package manager that install in `/usr/local` like Homebrew or alike).

**Comment by citibeth** [comment]
> So I am not sure what @citibeth <https://github.com/citibeth> means by
>
> My brief research above indicates that removing /usr/local won't work at
> all with Clang.
>
> See the linked article.  These things change all the time, of course.


> AFAICT it should work as expected and filtering it out shall not harm
> anything, but instead will make sure that all Spack-ed dependencies are
> properly picked up instead of, possibly, those provided by other sources
> (system, other package manager that install in /usr/local like Homebrew
> or alike).
>
We  can't assume what the compiler will / will not include on its own.
Appending these things at the end of our path will lead to greater
predictability.  What's the harm?

**Comment by joshuata** [comment]
I am still running into this problem on OSX. Was a solution/workaround settled on?

**Comment by davydden** [comment]
R u ruining the latest develop version?

**Comment by joshuata** [comment]
Yes. I pulled the most recent develop branch and still have this problem.

**Comment by adamjstewart** [comment]
Can you try #3910 and/or #3367 and see if they solve your problem? The former removes system paths from external packages and the latter changes how Python is built on macOS (builds static libraries by default instead of shared). I'm not sure which will solve your problem.

**Comment by davydden** [comment]
Please open a separate issue, attach build log, any custom configuration u have on macOS. I did not have any issues building python a weak ago or so on Sierra
