### ISSUE TITLE
Cannot uninstall package by hash

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1377]
I have several versions of a package installed that differ only by their hash:

```
$ spack find -p cactusext
==> 3 installed packages.
-- linux-redhat7-x86_64 / gcc@6.1.0-spack -----------------------
    cactusext@master  /home/eschnett/src/spack/opt/spack/linux-redhat7-x86_64/gcc-6.1.0-spack/cactusext-master-oi3cpui7hrd5j6wuilp2dmxbkv2tlo3q
    cactusext@master  /home/eschnett/src/spack/opt/spack/linux-redhat7-x86_64/gcc-6.1.0-spack/cactusext-master-iwpmzszzi47ge2s5rikzzmchqo33qg65
    cactusext@master  /home/eschnett/src/spack/opt/spack/linux-redhat7-x86_64/gcc-6.1.0-spack/cactusext-master-ppvk4aqxve274wlhcb2pyzqrlrozps5o
```

When I try to uninstall by hash, Spack wants to uninstall all of them:

```
$ spack uninstall cactusext/oi3cpui
==> Error: cactusext matches multiple packages:

-- linux-redhat7-x86_64 / gcc@6.1.0-spack -----------------------
oi3cpui cactusext@master%gcc+funhpc+julia+llvm+simulationio

iwpmzsz cactusext@master%gcc+funhpc+julia+llvm+simulationio

ppvk4aq cactusext@master%gcc+funhpc+julia+llvm+simulationio


==> Error: You can either:
    a) Use a more specific spec, or
    b) use spack uninstall -a to uninstall ALL matching specs.
```

**Comment by adamjstewart** [comment]
This is definitely a bug. I reported a similar problem in #1178.

In the meantime, try not specifying the package name:
```
spack uninstall /oi3cpui
```

**Comment by eschnett** [comment]
As a work-around, I'm using `rm -rf` to delete the package in the `opt/spack` directory, and then `spack reindex`.

**Comment by adamjstewart** [comment]
That also works, unless you run into the problem I did with #1320. *sigh*

**Comment by eschnett** [comment]
Hasn't #1320 been fixed?

**Comment by adamjstewart** [comment]
Not sure, I abandoned that Spack installation and reinstalled it again elsewhere. I can't risk uninstalling and reinstalling the 500 packages that I currently have installed that my users depend on. Hence #1325

**Comment by citibeth** [comment]
As discussed at most recent Spack meeting... a general Spack garbage collector will probably be more useful than deleting single packages.

**Comment by eschnett** [comment]
More comments here:
(1) Manually deleting packages can lead to an inconsistent package index that `spack reindex` cannot fix, as described above
(2) Uninstalling packages by specifying only the hash (without the package name) does not always work

**Comment by citibeth** [comment]
Still doesn't work.  See the latest:
```
$ spack uninstall /ruhltkr62akc3yp2l
==> Error: py-basemap@1.0.7%gcc@4.9.3 arch=linux-centos7-x86_64^ImageMagick@7.0.2-7%gcc@4.9.3 arch=linux-centos7-x86_64^autoconf@2.69%gcc@4.9.3 arch=linux-centos7-x86_64^bzip2@1.0.6%gcc@4.9.3 arch=linux-centos7-x86_64^cairo@1.14.0%gcc@4.9.3 arch=linux-centos7-x86_64^cmake@3.6.1%gcc@4.9.3~doc+ncurses+openssl~ownlibs~qt arch=linux-centos7-x86_64^curl@7.50.3%gcc@4.9.3 arch=linux-centos7-x86_64^expat@2.2.0%gcc@4.9.3 arch=linux-centos7-x86_64^fontconfig@2.11.1%gcc@4.9.3 arch=linux-centos7-x86_64^freetype@2.5.3%gcc@4.9.3 arch=linux-centos7-x86_64^geos@3.5.0%gcc@4.9.3 arch=linux-centos7-x86_64^gettext@0.19.8.1%gcc@4.9.3+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-x86_64^ghostscript@9.18%gcc@4.9.3 arch=linux-centos7-x86_64^ghostscript-fonts@8.11%gcc@4.9.3 arch=linux-centos7-x86_64^glib@2.49.4%gcc@4.9.3 arch=linux-centos7-x86_64^gmp@6.1.1%gcc@4.9.3 arch=linux-centos7-x86_64^harfbuzz@0.9.37%gcc@4.9.3 arch=linux-centos7-x86_64^icu4c@57.1%gcc@4.9.3 arch=linux-centos7-x86_64^jpeg@9b%gcc@4.9.3 arch=linux-centos7-x86_64^libarchive@3.2.1%gcc@4.9.3 arch=linux-centos7-x86_64^libffi@3.2.1%gcc@4.9.3 arch=linux-centos7-x86_64^libgcrypt@1.6.2%gcc@4.9.3 arch=linux-centos7-x86_64^libgpg-error@1.21%gcc@4.9.3 arch=linux-centos7-x86_64^libpng@1.6.24%gcc@4.9.3 arch=linux-centos7-x86_64^libtiff@4.0.6%gcc@4.9.3 arch=linux-centos7-x86_64^libxml2@2.9.4%gcc@4.9.3~python arch=linux-centos7-x86_64^libxslt@1.1.28%gcc@4.9.3 arch=linux-centos7-x86_64^lz4@131%gcc@4.9.3 arch=linux-centos7-x86_64^lzma@4.32.7%gcc@4.9.3 arch=linux-centos7-x86_64^lzo@2.09%gcc@4.9.3 arch=linux-centos7-x86_64^ncurses@6.0%gcc@4.9.3 arch=linux-centos7-x86_64^nettle@3.2%gcc@4.9.3 arch=linux-centos7-x86_64^openblas@0.2.19%gcc@4.9.3+fpic~openmp+shared arch=linux-centos7-x86_64^openssl@system%gcc@4.9.3 arch=linux-centos7-x86_64^pango@1.40.1%gcc@4.9.3 arch=linux-centos7-x86_64^pcre@8.39%gcc@4.9.3+utf arch=linux-centos7-x86_64^pixman@0.32.6%gcc@4.9.3 arch=linux-centos7-x86_64^py-cycler@0.10.0%gcc@4.9.3 arch=linux-centos7-x86_64^py-dateutil@2.5.2%gcc@4.9.3 arch=linux-centos7-x86_64^py-ipython@3.1.0%gcc@4.9.3 arch=linux-centos7-x86_64^py-matplotlib@1.5.1%gcc@4.9.3+gui+ipython arch=linux-centos7-x86_64^py-mock@1.3.0%gcc@4.9.3 arch=linux-centos7-x86_64^py-numpy@1.11.1%gcc@4.9.3+blas+lapack arch=linux-centos7-x86_64^py-pbr@1.8.1%gcc@4.9.3 arch=linux-centos7-x86_64^py-pillow@3.2.0%gcc@4.9.3~freetype+jpeg~jpeg2000~lcms~tiff+zlib arch=linux-centos7-x86_64^py-pygments@2.1.3%gcc@4.9.3 arch=linux-centos7-x86_64^py-pyparsing@2.0.3%gcc@4.9.3 arch=linux-centos7-x86_64^py-pyside@1.2.4%gcc@4.9.3 arch=linux-centos7-x86_64^py-pytz@2016.6.1%gcc@4.9.3 arch=linux-centos7-x86_64^py-six@1.10.0%gcc@4.9.3 arch=linux-centos7-x86_64^python@3.5.2%gcc@4.9.3~tk~ucs4 arch=linux-centos7-x86_64^qhull@2015.2%gcc@4.9.3 arch=linux-centos7-x86_64^qt@4.8.5%gcc@4.9.3~dbus~examples~gtk~krellpatch~mesa arch=linux-centos7-x86_64^readline@6.3%gcc@4.9.3 arch=linux-centos7-x86_64^sqlite@3.8.5%gcc@4.9.3 arch=linux-centos7-x86_64^tar@1.29%gcc@4.9.3 arch=linux-centos7-x86_64^tcl@8.6.5%gcc@4.9.3 arch=linux-centos7-x86_64^tk@8.6.5%gcc@4.9.3 arch=linux-centos7-x86_64^xz@5.2.2%gcc@4.9.3 arch=linux-centos7-x86_64^zlib@1.2.8%gcc@4.9.3 arch=linux-centos7-x86_64 matches multiple packages:

-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
ruhltkr py-basemap@1.0.7%gcc

qyw4iiz py-basemap@1.0.7%gcc


==> Error: You can either:
    a) Use a more specific spec, or
    b) use spack uninstall -a to uninstall ALL matching specs.

```

**Comment by tgamblin** [comment]
yep this is in the bugs that need to be addressed for v0.10.

**Comment by citibeth** [comment]
Is it linked into the GitHub project (sorry I just don't know)

**Comment by tgamblin** [comment]
Not sure what you're asking.  If you look on GitHub in the upper right of this issue you can see the link to the Project.  It says the name of the project and the status of the issue in that project (which column it's in)

**Comment by davydden** [comment]
Regarding the uninstall issues by hash, i notice that it does not work in case variants/options/dependencies of a package change between installation. For example I have had `p4est->lua` installed, but now i removed `lua` (which was wrong), and reinstall `p4est`. In this case `spack uninsta /hash` wont work and it will show all versions of `p4est` installed.

**Comment by davydden** [comment]
> So... uninstall by hash needs to NOT rely on the current hashes of packages?

I am not sure what you mean, but i guess the problem is that once a user install something into `<package>-hash-old` and then the package change (variants/dependencies), then spack won't be able to uninstall the old package by `hash-old`, however Spack still lists it among other installed variants of this package. 

I think this is not a big problem and it appears due to the fact that Spack is in alpha, once it is more stable those cases will become rare.

**Comment by davydden** [comment]
What I am saying is, uninstall by hash relies on the fact that the package to be uninstalled is consistent with it's `package.py` in Spack.

**Comment by becker33** [comment]
Spack is supposed to cache the old hash of the package once the package is concrete, specifically to avoid this issue. While looking into @2520 I've discovered that this caching is getting blown away at some point in the install process. I'm assuming that a similar problem is occurring with uninstall. 

I don't have an answer to this problem at the moment, all I can say is that I'm working on isolating it.

**Comment by davydden** [comment]
thanks @becker33 ! p.s. i edited your comment to correct the link to the issue.

**Comment by tgamblin** [comment]
@eschnett: this should be fixed by #2626.  Can you verify?  I tested with the package DB you attached above.

**Comment by citibeth** [comment]
I'm re-opening because this bug still appears.  For example:
```
$ dspack find modele
==> 2 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
modele@landice  modele@landice
$ dspack find /rh6pzb33moo472eepco2xpz2gzb6mgez
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
modele@landice
$ dspack find modele/rh6pzb33moo472eepco2xpz2gzb6mgez
==> 2 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
modele@landice  modele@landice
$ alias dspack='\spack -c ~/spscopes/centos7 -c ~/spscopes/gissversions -c ~/spscopes/twoway -c ~/spscopes/develop'
```
I have observed this bug with `spack uninstall`, `spack find` and `spack module loads`.  It probably exists in other commands that use the same underlying mechanism as well.

I last merged from `upstream/develop` on Dec 21, and it did not have conflicts in any core packages.  A spot-check of #2626 reveals that I seem to be running that code.
```
commit ad5de649d368d8a5dffc1b1638421a5e660e5826
Merge: 63e1546 e340f27
Author: Elizabeth Fischer <elizabeth.fischer@columbia.edu>
Date:   Wed Dec 21 18:55:12 2016 -0500

    Merge remote-tracking branch 'upstream/develop' into efischer/develop
    
    # Conflicts:
    #   var/spack/repos/builtin/packages/graphviz/package.py
    #   var/spack/repos/builtin/packages/libspatialindex/package.py
    #   var/spack/repos/builtin/packages/netcdf/package.py
    #   var/spack/repos/builtin/packages/openblas/package.py
    #   var/spack/repos/builtin/packages/petsc/package.py
    #   var/spack/repos/builtin/packages/py-pathspec/package.py
    #   var/spack/repos/builtin/packages/py-rtree/package.py
```

**Comment by tgamblin** [comment]
@citibeth:
1. can you paste the output of `spack find -l modele`?
1. can you attach the tarball resulting from running `spack debug create-db-tarball`

**Comment by citibeth** [comment]
```
$ dspack find -l modele
==> 2 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
rh6pzb3 modele@landice  fnwpplp modele@landice
[rpfische@gs611-gibbs build]$ \spack find -l modele
==> 2 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
rh6pzb3 modele@landice  fnwpplp modele@landice
```

I emailed you the tarball.

**Comment by tgamblin** [comment]
Can't reproduce.  On `develop`:

```console
$ spack find modele
==> 2 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
modele@landice  modele@landice
$ spack find -l modele
==> 2 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
rh6pzb3 modele@landice  fnwpplp modele@landice
$ spack find /rh6pzb3
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
modele@landice
$ spack find /fnwpplp
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
modele@landice
$ spack find modele /fnwpplp
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
modele@landice
$ spack find modele /rh6pzb3
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
modele@landice
$ spack find -L modele
==> 2 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
rh6pzb33moo472eepco2xpz2gzb6mgez modele@landice  fnwpplpz4xnatomvcgz2nj473pk5sp3l modele@landice
$ spack find -L /rh6pzb33moo472eepco2xpz2gzb6mgez
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
rh6pzb33moo472eepco2xpz2gzb6mgez modele@landice
$ spack find -L /fnwpplpz4xnatomvcgz2nj473pk5sp3l
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
fnwpplpz4xnatomvcgz2nj473pk5sp3l modele@landice
$ spack find -L modele /rh6pzb33moo472eepco2xpz2gzb6mgez
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
rh6pzb33moo472eepco2xpz2gzb6mgez modele@landice
$ :^A^K^A^K
$ spack find -L modele /fnwpplpz4xnatomvcgz2nj473pk5sp3l
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@4.9.3 -----------------------------
fnwpplpz4xnatomvcgz2nj473pk5sp3l modele@landice
```

**Comment by tgamblin** [comment]
obviously reopen if this is still broken, but using your database things seem to work properly on the current `develop` branch.

I did try this with `0.10` and it seems to be broken there, so we should probably put out a point release.

**Comment by citibeth** [comment]
> I did try this with 0.10 and it seems to be broken there, so we should probably put out a point release.

OK thanks for checking.  It looks like it was fixed somewhere later than #2626 but has been fixed now.  I'll assume it's fixed.  For now, the workaround is easier than merging in from `develop`.

**Comment by tgamblin** [comment]
Oh!  Looking at your commands again, this is not the match by hash bug that #2626 fixed, but the *parser* issue that #2889 fixed. In your output above, Spack is interpreting `spack find modele/hash` as two specs: `modele` and `/hash`.

See #2889 for more details.

**Comment by citibeth** [comment]
Thanks, that explains a lot.  I consider this case closed.
