### ISSUE TITLE
spack.util.web._spider is broken for max_depth >= 3

### ISSUE THREAD

**Issue by tobbez** [LLNL/spack#1497]
As first noted here: https://github.com/LLNL/spack/issues/1225#issuecomment-232378291

The problematic code is at https://github.com/LLNL/spack/blob/develop/lib/spack/spack/util/web.py#L134:

``` python
        if subcalls:                                                                                                                       
            try:    
                pool = Pool(processes=len(subcalls))
                results = pool.map(_spider, subcalls)
                for sub_pages, sub_links in results:
                    pages.update(sub_pages)
                    links.update(sub_links)
            finally:
                pool.terminate()
                pool.join()
```

The problem is that you're not allowed to create daemonic processes from daemonic processes, and map creates daemonic subprocesses, so when recursing from one of those subprocesses we get an exception.

The reason it hasn't been caught before is that the exception is silently dropped unless you run spack in debug mode. This made it hard to notice, especially if some versions are returned (i.e. if there are archives at multiple levels of the tree), where archives at the two first levels of the hierarchy would be returned, but not ones further down.

Running in debug mode (for a package with list_depth=3) shows:

``` console
$ spack -d versions hdf5
==> ignoring page http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13.tar.md5 with content type application/x-tar
==> ignoring page http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13-RELEASE.txt with content type text/plain
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Safe versions (already checksummed):
  1.10.0-patch1  1.10.0  1.8.16  1.8.15  1.8.13
==> Remote versions (not yet checksummed):
  1.6.5  1.6.4  1.6.3  1.6.2  1.6.1  1.6.0  1.4.4  1.4.3  1.4.2  1.4.1  1.4.0  1.2.2
```

Which I believe might be happening when the code in the finally clause is executed.

Modifying the code slightly, as follows:

``` diff
diff --git a/lib/spack/spack/util/web.py b/lib/spack/spack/util/web.py
index 25f1e60..285c53b 100644
--- a/lib/spack/spack/util/web.py
+++ b/lib/spack/spack/util/web.py
@@ -132,8 +132,8 @@ def _spider(args):
                 visited.add(abs_link)

         if subcalls:
+            pool = Pool(processes=len(subcalls))
             try:
-                pool = Pool(processes=len(subcalls))
                 results = pool.map(_spider, subcalls)
                 for sub_pages, sub_links in results:
                     pages.update(sub_pages)
```

Instead shows us the first/real exception:

``` console
$ spack -d versions hdf5
==> ignoring page http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13.tar.md5 with content type application/x-tar
==> ignoring page http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13-RELEASE.txt with content type text/plain
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Error in _spider: daemonic processes are not allowed to have children
==> Safe versions (already checksummed):
  1.10.0-patch1  1.10.0  1.8.16  1.8.15  1.8.13
==> Remote versions (not yet checksummed):
  1.6.5  1.6.4  1.6.3  1.6.2  1.6.1  1.6.0  1.4.4  1.4.3  1.4.2  1.4.1  1.4.0  1.2.2
```

Further changing the code to give us a full stack trace:

``` diff
diff --git a/lib/spack/spack/util/web.py b/lib/spack/spack/util/web.py
index 25f1e60..a3de476 100644
--- a/lib/spack/spack/util/web.py
+++ b/lib/spack/spack/util/web.py
@@ -132,8 +132,8 @@ def _spider(args):
                 visited.add(abs_link)

         if subcalls:
+            pool = Pool(processes=len(subcalls))
             try:
-                pool = Pool(processes=len(subcalls))
                 results = pool.map(_spider, subcalls)
                 for sub_pages, sub_links in results:
                     pages.update(sub_pages)
@@ -157,9 +157,9 @@ def _spider(args):

         tty.warn(msg, url, "HTMLParseError: " + str(e))

-    except Exception as e:
-        # Other types of errors are completely ignored, except in debug mode.
-        tty.debug("Error in _spider: %s" % e)
+    #except Exception as e:
+    #    # Other types of errors are completely ignored, except in debug mode.
+    #    tty.debug("Error in _spider: %s" % e)

     return pages, links
```

gives:

``` console
$ spack -d versions hdf5
==> ignoring page http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13-RELEASE.txt with content type text/plain
==> ignoring page http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13.tar.md5 with content type application/x-tar
Traceback (most recent call last):
  File "/home/ketl/spack/bin/spack", line 184, in <module>
    main()
  File "/home/ketl/spack/bin/spack", line 161, in main
    return_val = command(parser, args)
  File "/home/ketl/spack/lib/spack/spack/cmd/versions.py", line 41, in versions
    fetched_versions = pkg.fetch_remote_versions()
  File "/home/ketl/spack/lib/spack/spack/package.py", line 1383, in fetch_remote_versions
    list_depth=self.list_depth)
  File "/home/ketl/spack/lib/spack/spack/util/web.py", line 215, in find_versions_of_archive
    p, l = spider(lurl, depth=list_depth)
  File "/home/ketl/spack/lib/spack/spack/util/web.py", line 177, in spider
    1, max_depth, False))
  File "/home/ketl/spack/lib/spack/spack/util/web.py", line 137, in _spider
    results = pool.map(_spider, subcalls)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AssertionError: daemonic processes are not allowed to have children
```

**Comment by adamjstewart** [comment]
I'm no longer seeing this bug:
```
$ spack -d versions hdf5
==> Safe versions (already checksummed):
  1.10.0-patch1  1.10.0  1.8.18  1.8.17  1.8.16  1.8.15  1.8.14  1.8.13  1.8.12
==> Remote versions (not yet checksummed):
  1.2.2
```
Perhaps it was fixed by another PR? If not, feel free to reopen this issue.

**Comment by tobbez** [comment]
I don't seem to have permission to reopen the issue.

This problem is still present, but that reproducer stopped working because the hdf5 download directory got redirected to a new subdomain (it moved from `http://www.hdfgroup.org/ftp/HDF5/releases/` to `https://support.hdfgroup.org/ftp/HDF5/releases/`). This caused `_spider` to filter out *all* found URLs, since they do not start with `http://www.hdfgroup.org/ftp/HDF5/releases/`, which meant the code path containing the recursion never executed.

Updating the package file to use the new URL:
```diff
diff --git a/var/spack/repos/builtin/packages/hdf5/package.py b/var/spack/repos/builtin/packages/hdf5/package.py
index aedaf1821..1793c65dd 100644
--- a/var/spack/repos/builtin/packages/hdf5/package.py
+++ b/var/spack/repos/builtin/packages/hdf5/package.py
@@ -35,7 +35,7 @@ class Hdf5(Package):

     homepage = "http://www.hdfgroup.org/HDF5/"
     url = "http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13.tar.gz"
-    list_url = "http://www.hdfgroup.org/ftp/HDF5/releases"
+    list_url = "https://support.hdfgroup.org/ftp/HDF5/releases/"
     list_depth = 3

     version('1.10.0-patch1', '9180ff0ef8dc2ef3f61bd37a7404f295')
```

Shows the issue is still there:
```
$ ./bin/spack -d versions hdf5
==> HTTP Error 404: Not Found
==> ignoring page https://support.hdfgroup.org/ftp/HDF5/releases/COPYING
==> ignoring page https://support.hdfgroup.org/ftp/HDF5/releases/COPYING_LBNL_HDF5
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Error in _spider: local variable 'pool' referenced before assignment
==> Safe versions (already checksummed):
  1.10.0-patch1  1.10.0  1.8.16  1.8.15  1.8.13
==> Remote versions (not yet checksummed):
  1.6.5  1.6.4  1.6.3  1.6.2  1.6.1  1.6.0  1.4.4  1.4.3  1.4.2  1.4.1  1.4.0  1.2.2
```
