### ISSUE TITLE
Installation issue: pocl@1.5 and pocl@master

### ISSUE THREAD

**Issue by Sinan81** [LLNL/spack#17048]
### Steps to reproduce the issue
I am using Spack development branch
```console
$ spack install pocl
...
[ 77%] Building C object bin/CMakeFiles/poclcc.dir/__/lib/poclu/misc.c.o
cd /mnt/local/cache/sbulut/spack-stage/spack-stage-pocl-1.5-acptiw7fzycqao3jopnsinzx7xxt5wz6/spack-build/bin && /mnt/local/spack/lib/spack/env/gcc/gcc -DCL_TARGET_OPENCL_VERSION=220 -DCL_USE_DEPRECATED_OPENCL_1_0_APIS -DCL_USE_DEPRECATED_OPENCL_1_1_APIS -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_USE_DEPRECATED_OPENCL_2_0_APIS -DCL_USE_DEPRECATED_OPENCL_2_1_APIS -I/cache/sbulut/spack-stage/spack-stage-pocl-1.5-acptiw7fzycqao3jopnsinzx7xxt5wz6/spack-src/include -I/mnt/local/cache/sbulut/spack-stage/spack-stage-pocl-1.5-acptiw7fzycqao3jopnsinzx7xxt5wz6/spack-build  -O2 -g -DNDEBUG -fPIE   -Werror=implicit-function-declaration -Wincompatible-pointer-types -pthread -o CMakeFiles/poclcc.dir/__/lib/poclu/misc.c.o   -c /cache/sbulut/spack-stage/spack-stage-pocl-1.5-acptiw7fzycqao3jopnsinzx7xxt5wz6/spack-src/lib/poclu/misc.c
../../lib/CL/libOpenCL.so.2.5.0: undefined reference to `getPollyPluginInfo()'
collect2: error: ld returned 1 exit status
../../lib/CL/libOpenCL.so.2.5.0: undefined reference to `getPollyPluginInfo()'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/kernel/sampler_address_clamp] Error 1
make[2]: Leaving directory `/mnt/local/cache/sbulut/spack-stage/spack-stage-pocl-1.5-acptiw7fzycqao3jopnsinzx7xxt5wz6/spack-build'
make[1]: *** [tests/kernel/CMakeFiles/sampler_address_clamp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [tests/kernel/kernel] Error 1
make[2]: Leaving directory `/mnt/local/cache/sbulut/spack-stage/spack-stage-pocl-1.5-acptiw7fzycqao3jopnsinzx7xxt5wz6/spack-build'
make[1]: *** [tests/kernel/CMakeFiles/kernel.dir/all] Error 2
../../lib/CL/libOpenCL.so.2.5.0: undefined reference to `getPollyPluginInfo()'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/kernel/image_query_funcs] Error 1
make[2]: Leaving directory `/mnt/local/cache/sbulut/spack-stage/spack-stage-pocl-1.5-acptiw7fzycqao3jopnsinzx7xxt5wz6/spack-build'
make[1]: *** [tests/kernel/CMakeFiles/image_query_funcs.dir/all] Error 2
[ 77%] Linking C executable poclcc
cd /mnt/local/cache/sbulut/spack-stage/spack-stage-pocl-1.5-acptiw7fzycqao3jopnsinzx7xxt5wz6/spack-build/bin && /mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/cmake-3.17.1-cicgl6bcblre7wkgaqtateadycevv7a4/bin/cmake -E cmake_link_script CMakeFiles/poclcc.dir/link.txt --verbose=1
```
default version, `pocl@1.5` fails to build as well as `pocl@master`

However `pocl@1.4` builds just fine with `llvm@9.0.1`

### Information on your system

- centos7.6 skylake
- gcc@8.3.0
- dependency LLVM defaulted to 10.0.0

### Additional information

**Comment by SirRujak** [comment]
I've been trying to test out the rocm branches which rely on pocl and it appears that this issue was fixed in llvm@10.0.1 as per this [bug report](https://bugs.llvm.org/show_bug.cgi?id=44870). On my local machine I was able to just add version 10.0.1 to the llvm spack definition and it built correctly. I am not entirely sure if anything else would need to happen for the llvm update but I wanted to at least mention that it appears to work.

**Comment by Sinan81** [comment]
> I've been trying to test out the rocm branches which rely on pocl and it appears that this issue was fixed in llvm@10.0.1 as per this [bug report](https://bugs.llvm.org/show_bug.cgi?id=44870). On my local machine I was able to just add version 10.0.1 to the llvm spack definition and it built correctly. I am not entirely sure if anything else would need to happen for the llvm update but I wanted to at least mention that it appears to work.

Weird, the build is still failing for me despite I am using llvm@10.0.1. Could you provide the spec of the successful build?

**Comment by Sinan81** [comment]
disabling `polly ` option in llvm pushes build percentages from 70ish to 99% however it is still failing due to a different error:
```
...
     2120    /cache/sbulut/spack-stage/spack-stage-pocl-1.5-e34rzscsntotrane57rayue3wulyujav/
             spack-src/examples/matrix1/matrix1.c: In function 'main':
  >> 2121    /cache/sbulut/spack-stage/spack-stage-pocl-1.5-e34rzscsntotrane57rayue3wulyujav/
             spack-src/examples/matrix1/matrix1.c:408:3: error: implicit declaration of funct
             ion 'srandom'; did you mean 'srand'? [-Werror=implicit-function-declaration]
     2122       srandom (time (NULL));
     2123       ^~~~~~~
     2124       srand
  >> 2125    /cache/sbulut/spack-stage/spack-stage-pocl-1.5-e34rzscsntotrane57rayue3wulyujav/
             spack-src/examples/matrix1/matrix1.c:414:20: error: implicit declaration of func
             tion 'random'; did you mean 'rand'? [-Werror=implicit-function-declaration]
     2126               long r = random ();
     2127                        ^~~~~~
     2128                        rand
...
```
This looks like a somewhat trivial error.

**Comment by SirRujak** [comment]
My install was a bit messy due to trying to get the rocm build going concurrently so I am starting a rebuild of pocl with a fresh spack install to sort things out. I'll post back with the specifics of my build process and the spec for it when it finishes up. May be a bit but I should be able to have it ready later today.

**Comment by Sinan81** [comment]
> My install was a bit messy due to trying to get the rocm build going concurrently so I am starting a rebuild of pocl with a fresh spack install to sort things out. I'll post back with the specifics of my build process and the spec for it when it finishes up. May be a bit but I should be able to have it ready later today.

Please take your time. This is not something super urgent. Thanks!

**Comment by SirRujak** [comment]
No worries! Had some non-computer stuff to do today so I have been running it in the background building away. I was able to build it again from a fresh install with both gcc@8.3.0 and gcc@9.3.0. Here is the [spec.yaml](https://github.com/spack/spack/files/5046620/specyaml.txt) for pocl. For reference I am on the spack develop branch and pulled it today. The only change I made was to the llvm package.py in which I added 
    `version('10.0.1', sha256='c7ccb735c37b4ec470f66a6c35fbae4f029c0f88038f6977180b1a8ddc255637')`

Looking through the spec it does appear to have built llvm 10.0.1 with polly as well so I am not entirely sure what may be happening on your end but if there is anything other information I can share just let me know!

**Comment by Sinan81** [comment]
tried to build pocl again from a nearly fresh clone of spack, still getting the same error.

**Comment by Sinan81** [comment]
I guess it is time creating an issue in pocl github repo.

**Comment by Sinan81** [comment]
Weird: When I tried building with `pocl+icd`, it doesn't fail with polly error anymore, it proceeds further from 80% to 90%, but fails with:
```
  >> 4857    /cache/sbulut/spack-stage/spack-stage-pocl-1.5-z4skv64fwxgkfbrd3oing6647zijdk6b/spack-src/examples/matrix1/matrix1.c:408:3: error: implicit declaration of function 'srandom'; did you mean 'srand'? [-Werror=implicit-function-
             declaration]
     4858       srandom (time (NULL));
     4859       ^~~~~~~
```

**Comment by hartzell** [comment]
@Sinan81 -- Did you ever get @1.5 to build.  We're seeing a similar failure with CentOS7 and gcc@8.4.0.

**Comment by Sinan81** [comment]
@hartzell  I must have tried building it with gcc@7.4 and gcc@8.3 but it doesn't look like it worked.
