### ISSUE TITLE
Installation issue: Paraview

### ISSUE THREAD

**Issue by opadron** [LLNL/spack#19134]
### Steps to reproduce the issue

```console
$ spack install paraview@5.7.0 +kits
```

```console
CMake Error at CMake/vtkModuleWrapClientServer.cmake:58 (message):
  The ParaView::VTKExtensionsPoints hierarchy file is attached to a
  non-imported target and a hierarchy target is missing.
Call Stack (most recent call first):
  CMake/vtkModuleWrapClientServer.cmake:139 (_vtk_module_wrap_client_server_sources)
  CMake/vtkModuleWrapClientServer.cmake:306 (_vtk_module_wrap_client_server_library)
  CMakeLists.txt:910 (vtk_module_wrap_client_server)


-- Configuring incomplete, errors occurred!
See also "/tmp/root/spack-stage/spack-stage-paraview-5.7.0-5bbm5dwuhmfzrmxp4rtpxczk7ia53up4/spack-build-5bbm5dw/CMakeFiles/CMakeOutput.log".
See also "/tmp/root/spack-stage/spack-stage-paraview-5.7.0-5bbm5dwuhmfzrmxp4rtpxczk7ia53up4/spack-build-5bbm5dw/CMakeFiles/CMakeError.log".
```
### Information on your system

* Ran on the latest `spack/ubuntu-bionic` docker image.
* **Spack:** 0.15.4
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-x86_64

### Additional information

* [spack-build-out.txt](https://gist.github.com/opadron/1e41d051f6706a484a132c07cf5739ff#file-spack-build-out-txt)
* [spack-build-env.txt](https://gist.github.com/opadron/1e41d051f6706a484a132c07cf5739ff#file-spack-build-env-txt)
* [CMakeOutput.log](https://gist.github.com/opadron/1e41d051f6706a484a132c07cf5739ff#file-cmakeoutput-log)
* [CMakeError.log](https://gist.github.com/opadron/1e41d051f6706a484a132c07cf5739ff#file-cmakeerror-log)

@chuckatkins
@danlipsa

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by chuckatkins** [comment]
@mathstuf any insight into what's happening here?

**Comment by mathstuf** [comment]
I think this is a bug that was fixed later in 5.8. See paraview/paraview@3035632a4c08c1c05dbd4a1fd5a72994296ade64, paraview/paraview@a5cbf67597a82bb3496b187535a03d6344e6bca6, vtk/vtk@293ab8d7448d71693bdb1169c8c8025b84a2b23b, vtk/vtk@0ed03368dd429853db3cfde4551388b2f85014ae

This is probably not an exhaustive list.

**Comment by mathstuf** [comment]
Kitware/paraview@3035632a4c08c1c05dbd4a1fd5a72994296ade64, Kitware/paraview@a5cbf67597a82bb3496b187535a03d6344e6bca6, Kitware/vtk@293ab8d7448d71693bdb1169c8c8025b84a2b23b, Kitware/vtk@0ed03368dd429853db3cfde4551388b2f85014ae

Hmm. Not sure why I can't edit my other comment.

**Comment by chuckatkins** [comment]
@mathstuf After applying the patches, the issue still exists, just in a different spot:
```
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
CMake Error at VTK/CMake/vtkModuleWrapPython.cmake:96 (message):
  The VTK::CommonCore hierarchy file is attached to a non-imported target and
  a hierarchy target (CommonCore-objects-hierarchy) is missing.
Call Stack (most recent call first):
  VTK/CMake/vtkModuleWrapPython.cmake:197 (_vtk_module_wrap_python_sources)
  VTK/CMake/vtkModuleWrapPython.cmake:637 (_vtk_module_wrap_python_library)
  CMakeLists.txt:928 (vtk_module_wrap_python)
```

**Comment by mathstuf** [comment]
Kitware/vtk@cb8356aa0fffa66923b946bb2aba57a957adbc8a and Kitware/vtk@61d8d21b4dffcfb882b633bbea6daf738d1e82b2 look relevant to that. How I'm finding these in case there are more:

```sh
git log -p -Shierarchy -- 'CMake/vtkModule*'
```
