### ISSUE TITLE
An Issue with Externally Installed Intel Parallel Studio XE on macOS.

### ISSUE THREAD

**Issue by zhiyuanzhai** [LLNL/spack#19937]
## Update

This error may actually come down to the situation when Spack is dealing with packages that are not dependent on MPIs when Intel Parallel Studio exists in the root spec. Spack would behave as if it is operating on Linux and tries to look for a library `libmkl_blacs_intelmpi_lp64`, which does not exist since Intel's MPI is not included in macOS, thus communicating with Intel MPI is not necessary.

---
## The Original Description

The problem is that, when using an externally installed Intel Parallel Studio in `spack`, `spack` tries to find `intel-mpi` and other related libraries, **which is NOT included in macOS version of Intel Parallel Studio**.

Here's an example:
```
$ spack install julia +mkl
...
==> Error: InstallError: Cannot locate ScaLapack/BLACS libraries:
	['libmkl_scalapack_lp64', 'libmkl_blacs_intelmpi_lp64']

/Users/zhiyuan/.local/opt/spack/lib/spack/spack/build_systems/intel.py:838, in scalapack_libs:
        835            shared=('+shared' in self.spec))
        836        debug_print(sca_libs)
        837
  >>    838        if len(sca_libs) < 2:
        839            raise_lib_error(
        840                'Cannot locate ScaLapack/BLACS libraries:', scalapack_libnames)
        841        # NB: ScaLapack is installed as "cluster" components within MKL or
```
Indeed, `libmkl_blacs_intelmpi_lp64` does not exist, because `intel-mpi` is not installed. I guess that macOS uses `mpich` instead, since I've found a similar library named `libmkl_blacs_mpich_lp64`.

Is there any simple way to fix it?

*Note*: System Info.
```
$ spack debug report
```
* **Spack:** 0.15.4-1930-d40a35e8d
* **Python:** 3.9.0
* **Platform:** darwin-bigsur-skylake

`packages.yaml`:
```yaml
packages:
  ...
  intel-parallel-studio:
    externals:
    - spec: intel-parallel-studio@composer.2020.4 arch=darwin-bigsur-x86_64
      modules:
      - intel
    buildable: False
  ...
```

**Comment by zhiyuanzhai** [comment]
@adamjstewart @mgsternberg @davydden @glennpj @becker33

**Comment by adamjstewart** [comment]
> spack tries to find intel-mpi and other related libraries, which is NOT included in macOS version of Intel Parallel Studio!

That's odd. Spack should know that the Professional Edition and Composer Edition don't come with MPI, only the Cluster Edition does. Can you try adding `~mpi` to your spec? That should solve the issue.

**Comment by zhiyuanzhai** [comment]
@adamjstewart The problem still exists, after adding that flag.

Maybe my description was not quite accurate? It seems that the error occurred when checking whether the library `libmkl_blacs_intelmpi_lp64` exists or not. It's not searching `intel-mpi` directly.

I guess `libmkl_blacs_intelmpi_lp64` is the library that MKL use to communicate with or call `intel-mpi`, which is not actually necessary when `mpi` itself is not included. 

And I don't know whether there is such a lib file included with other versions of PSXE.

**Comment by zhiyuanzhai** [comment]
When looking through the `intel-mkl` directory, I found a similar library name, `libmkl_blacs_mpich_lp64.a`, which seems to be using `mpich` instead of `intel-mkl`.

**Comment by zhiyuanzhai** [comment]
I think I've figured it out. It's in `intel.py`, line 803:
https://github.com/spack/spack/blob/4609a126baa383ce8057253dacd6ac4fc415ac72/lib/spack/spack/build_systems/intel.py#L802-L826
It seems that the situation described above has been taken into account, but only when the package is dependent on `mpich`. For `julia`, this is not the case, as `mpi` is not a dependency of `julia`, which means `^mpich` is not in the `spec_root`, leading to an error.

A quick fix might be removing the requirement that '^mpich' must be in the spec, but I'm not sure if this will cause other problems.

EDIT: I made it better looking.

**Comment by zhiyuanzhai** [comment]
Since latest Intel packages like `intel-mkl` on macOS is only compatible with `mpich`, is it feasible to consider them conflicting with MPIs other than `mpich`? @adamjstewart

**Comment by adamjstewart** [comment]
I have to admit, I'm not super familiar with Intel packages. Is it true that `mpich` is supported but `openmpi` and `intel-mpi` aren't? I find it hard to believe that `intel-mpi` isn't supported.

I think what you want is to rename `^intel-parallel-studio` to `^intel-parallel-studio+mpi`.

**Comment by zhiyuanzhai** [comment]
@adamjstewart I'm not sure if this is the correct understanding. But the comment in the `intel.py` says:
```python
...    
# The only supported choice for MKL 2018 on Mac.
blacs_lib = 'libmkl_blacs_mpich'
...
```
It looks as if the Intel MKL since 2018 on Mac has been using `mpich` only. But this still needs to be verified by the official documentations.

But I believe one thing is for sure: the Intel packages since 2018 won't work properly on a Mac with an `if` statement like this. It can only handle the situation when `^mpich` is in the spec, i.e., the package is possibly dependent on MPI. When building packages like `julia`, which doesn't explicitly depend on any MPIs, execution of this script would not lead to the first `if` block. It would go straight to the third `elif`, where a non-existing library name will be appended to the list, causing the trouble mentioned above. 

And that's what I mean to say by showing those python code.

**Comment by zhiyuanzhai** [comment]
```bash
$ ls /opt/intel/mkl/lib
libmkl_avx.dylib               libmkl_intel_ilp64.a           libmkl_scalapack_lp64.a
libmkl_avx2.dylib              libmkl_intel_ilp64.dylib       libmkl_scalapack_lp64.dylib
libmkl_avx512.dylib            libmkl_intel_lp64.a            libmkl_sequential.a
libmkl_blacs_mpich_ilp64.a     libmkl_intel_lp64.dylib        libmkl_sequential.dylib
libmkl_blacs_mpich_ilp64.dylib libmkl_intel_thread.a          libmkl_tbb_thread.a
libmkl_blacs_mpich_lp64.a      libmkl_intel_thread.dylib      libmkl_tbb_thread.dylib
libmkl_blacs_mpich_lp64.dylib  libmkl_lapack95_ilp64.a        libmkl_vml_avx.dylib
libmkl_blas95_ilp64.a          libmkl_lapack95_lp64.a         libmkl_vml_avx2.dylib
libmkl_blas95_lp64.a           libmkl_mc3.dylib               libmkl_vml_avx512.dylib
libmkl_cdft_core.a             libmkl_pgi_thread.a            libmkl_vml_mc2.dylib
libmkl_cdft_core.dylib         libmkl_rt.dylib                libmkl_vml_mc3.dylib
libmkl_core.a                  libmkl_scalapack_ilp64.a       locale
libmkl_core.dylib              libmkl_scalapack_ilp64.dylib
```
Here's the contents of MKL libraries on my Mac.

**Comment by mgsternberg** [comment]
@adamjstewart is right in pointing to the cascading `if`.

I need to refresh my mind and look into background, but I think the question is: how come `scalapack_libs()` is called when no MPI is in the DAG? The libs do exist on Mac, at least for new releases (cf. comment about the optional cluster components in previous releases), and so it will be fine to link them.

Can ScaLAPACK be called and function without MPI? Otherwise, it looks like `+mpich` needs to be added to a package’s spec on Mac as soon as ScaLAPACK is being used. @zhiyuanzhai Can you try that?

**Comment by zhiyuanzhai** [comment]
@mgsternberg Well, as the comment in `intel.py` says: 
>  Intel MKL does not directly depend on MPI but the BLACS library which underlies ScaLapack does. It comes in several personalities; we must supply a personality matching the MPI implementation that is active for the root package that asked for ScaLapack. 

I know little about ScaLAPACK. Is there any example that I can try?

Sounds like we can separate ScaLAPACK from Intel MKL? I thought Intel MKL were considered as a whole package that includes ScaLAPACK.

**Comment by zhiyuanzhai** [comment]
Is there any progress on this? @mgsternberg @adamjstewart 

From what I've learnt these days, I don't think ScaLAPACK can function without MPI (though I don't know much about it). Now MKL seems to be considered as a whole, and ScaLAPACK is part of it. If ScaLAPACK is considered to depend on MPIs, then MKL should depend on MPIs too. Or maybe we can separate each component from MKL?

**Comment by zhiyuanzhai** [comment]
@adamjstewart I'm so sorry to say this, but it turns out adding the flag `~mpi` actually works. It's my mistake simply adding the flag to the installation command. I should have added that flag to `packages.yaml`, the place. I'm not sure why this is different, but after I tried one more time today, in the "correct" way, it magically worked.

But why do we have to specify `~mpi` even when `@composer.xxxx.x` is in the spec? Shouldn't Spack know that the composer version does not include Intel's MPI libraries?

Again, I apologise for my mistakes which may leads to serious confusion. I'm so sorry for that...

**Comment by mgsternberg** [comment]
@zhiyuanzhai  I am glad you could sort this out; we're gaining clarity. Just to confirm, I take it you succeeded _without_ your proposed fix #20031 applied, correct?

Also, @zhiyuanzhai can you inspect how the concretizer resolves dependency packages by default and how that changes with `~mpi`?


About the background question:
> But why do we have to specify `~mpi` even when `@composer.xxxx.x` is in the spec? Shouldn't Spack know that the composer version does not include Intel's MPI libraries?

Consider that the BLACS component of the ScaLAPACK component of MKL (sigh) can work with *several* MPI flavors, not just Intel-MPI. On macOS, per your previous example, only the MPICH2 ABI is supported:
```
$ ls -1 /opt/intel/mkl/lib/libmkl_blacs_mpich*
libmkl_blacs_mpich_ilp64.a
libmkl_blacs_mpich_ilp64.dylib
libmkl_blacs_mpich_lp64.a
libmkl_blacs_mpich_lp64.dylib
```
For MPI other than Intel's, even possibly vanilla non-Intel MPICH2, the full story is complicated, requiring a [custom wrapper to provide an MPI-independent ABI to Intel MKL](https://software.intel.com/content/www/us/en/develop/documentation/mkl-macos-developer-guide/top/working-with-the-intel-math-kernel-library-cluster-software/using-a-custom-message-passing-interface.html). It's not quite clear if one needs the wrapper even when offering a vanilla MPICH2, because AFAIK Intel-MPI uses the MPICH2 ABI.


Michael

**Comment by zhiyuanzhai** [comment]
@adamjstewart I can confirm that I'm on the branch `develop`.

As for the resolution of the concretizer without `~mpi`
```
$ spack spec intel-parallel-studio@composer.2020.4
Input spec
--------------------------------
intel-parallel-studio@composer.2020.4

Concretized
--------------------------------
==> Error: Conflicts in concretized spec "intel-parallel-studio@composer.2020.4%gcc@10.2.0~advisor~clck+daal~gdb~ilp64~inspector+ipp~itac+mkl+mpi~newdtags+rpath+shared+tbb~vtune auto_dispatch=none threads=none arch=darwin-bigsur-skylake/oxk2nzw"

List of matching conflicts for spec:

    intel-parallel-studio@composer.2020.4%gcc@10.2.0~advisor~clck+daal~gdb~ilp64~inspector+ipp~itac+mkl+mpi~newdtags+rpath+shared+tbb~vtune auto_dispatch=none threads=none arch=darwin-bigsur-skylake

1. "+mpi" conflicts with "intel-parallel-studio@composer.0:composer.9999"
```
the conflict was actually found. 

When `~mpi` is specified
```
$ spack spec intel-parallel-studio@composer.2020.4~mpi
Input spec
--------------------------------
intel-parallel-studio@composer.2020.4~mpi

Concretized
--------------------------------
intel-parallel-studio@composer.2020.4%gcc@10.2.0~advisor~clck+daal~gdb~ilp64~inspector+ipp~itac+mkl~mpi~newdtags+rpath+shared+tbb~vtune auto_dispatch=none threads=none arch=darwin-bigsur-skylake
```

**Comment by adamjstewart** [comment]
I'm hitting this now too:
```
==> Error: InstallError: Cannot locate ScaLapack/BLACS libraries:
	['libmkl_scalapack_lp64', 'libmkl_blacs_openmpi_lp64']

/Users/Adam/spack/lib/spack/spack/build_systems/intel.py:838, in scalapack_libs:
        835            shared=('+shared' in self.spec))
        836        debug_print(sca_libs)
        837
  >>    838        if len(sca_libs) < 2:
        839            raise_lib_error(
        840                'Cannot locate ScaLapack/BLACS libraries:', scalapack_libnames)
        841        # NB: ScaLapack is installed as "cluster" components within MKL or
```

**Comment by adamjstewart** [comment]
Here is what I have on the system:
```
$ l /opt/intel/compilers_and_libraries_2020.0.166/mac/mkl/lib/
libmkl_avx.dylib               libmkl_blas95_lp64.a           libmkl_intel_lp64.dylib        libmkl_scalapack_ilp64.a       libmkl_vml_avx.dylib
libmkl_avx2.dylib              libmkl_cdft_core.a             libmkl_intel_thread.a          libmkl_scalapack_ilp64.dylib   libmkl_vml_avx2.dylib
libmkl_avx512.dylib            libmkl_cdft_core.dylib         libmkl_intel_thread.dylib      libmkl_scalapack_lp64.a        libmkl_vml_avx512.dylib
libmkl_blacs_mpich_ilp64.a     libmkl_core.a                  libmkl_lapack95_ilp64.a        libmkl_scalapack_lp64.dylib    libmkl_vml_mc2.dylib
libmkl_blacs_mpich_ilp64.dylib libmkl_core.dylib              libmkl_lapack95_lp64.a         libmkl_sequential.a            libmkl_vml_mc3.dylib
libmkl_blacs_mpich_lp64.a      libmkl_intel_ilp64.a           libmkl_mc3.dylib               libmkl_sequential.dylib        locale
libmkl_blacs_mpich_lp64.dylib  libmkl_intel_ilp64.dylib       libmkl_pgi_thread.a            libmkl_tbb_thread.a
libmkl_blas95_ilp64.a          libmkl_intel_lp64.a            libmkl_rt.dylib                libmkl_tbb_thread.dylib
```

**Comment by adamjstewart** [comment]
I'm building a DAG where both `intel-mkl` and `openmpi` are transient dependencies, but the direct package doesn't depend on either.

**Comment by mgsternberg** [comment]
@adamjstewart Are you in a position to share the DAG, incl. its root, that triggered this?

Do transient dependencies occur for other packages  in Spack, and how are they handled?

**Comment by adamjstewart** [comment]
@mgsternberg here is the DAG:
```
$ spack spec openvslam
Input spec
--------------------------------
openvslam

Concretized
--------------------------------
openvslam@master%apple-clang@12.0.0~ipo build_type=RelWithDebInfo patches=131159b0042300614d039ceb3538defe4d302b59dc748b02287fc8ff895e6bbd arch=darwin-catalina-x86_64
    ^cmake@3.19.1%apple-clang@12.0.0~doc+ncurses+openssl+ownlibs~qt arch=darwin-catalina-x86_64
        ^ncurses@6.2%apple-clang@12.0.0~symlinks+termlib arch=darwin-catalina-x86_64
            ^pkgconf@1.7.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^openssl@1.1.1i%apple-clang@12.0.0+systemcerts arch=darwin-catalina-x86_64
            ^perl@5.32.0%apple-clang@12.0.0+cpanm+shared+threads patches=517afe8ca1cb12f798f20b21583d91463fe3f4fa9244c6c8e054a92c8135da8f arch=darwin-catalina-x86_64
                ^berkeley-db@18.1.40%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^gdbm@1.18.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^readline@8.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^zlib@1.2.11%apple-clang@12.0.0+optimize+pic+shared arch=darwin-catalina-x86_64
    ^dbow2@shinsumicco%apple-clang@12.0.0~ipo build_type=RelWithDebInfo arch=darwin-catalina-x86_64
        ^boost@1.74.0%apple-clang@12.0.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=98 visibility=hidden arch=darwin-catalina-x86_64
            ^bzip2@1.0.8%apple-clang@12.0.0+shared arch=darwin-catalina-x86_64
                ^diffutils@3.7%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^libiconv@1.16%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^dlib@master%apple-clang@12.0.0~ipo build_type=RelWithDebInfo arch=darwin-catalina-x86_64
            ^opencv@4.2.0%apple-clang@12.0.0+calib3d~contrib+core~cuda~cudacodec~dnn~eigen~fast-math+features2d+flann~gtk+highgui+imgcodecs+imgproc~ipo~ipp~ipp_iw~jasper~java~jpeg~lapack~ml~opencl~opencl_svm~openclamdblas~openclamdfft~openmp~png~powerpc~pthreads_pf~python~qt+shared~stitching~superres~tiff~ts~video+videoio~videostab~vsx~vtk~zlib build_type=RelWithDebInfo cuda_arch=none arch=darwin-catalina-x86_64
                ^ffmpeg@4.2.2%apple-clang@12.0.0~X~avresample+bzlib~drawtext+gpl~libaom~libmp3lame~libopenjpeg~libopus~libsnappy~libspeex~libssh~libvorbis~libwebp~libzmq~lzma~nonfree~openssl~sdl2+shared+version3 arch=darwin-catalina-x86_64
                    ^yasm@1.3.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^openmpi@3.1.6%apple-clang@12.0.0~atomics~cuda~cxx~cxx_exceptions+gpfs~java~legacylaunchers~lustre~memchecker~pmi~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=none schedulers=none arch=darwin-catalina-x86_64
                    ^hwloc@1.11.11%apple-clang@12.0.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~pci+shared arch=darwin-catalina-x86_64
                        ^libxml2@2.9.10%apple-clang@12.0.0~python arch=darwin-catalina-x86_64
                            ^xz@5.2.5%apple-clang@12.0.0~pic arch=darwin-catalina-x86_64
    ^eigen@3.3.8%apple-clang@12.0.0~ipo build_type=RelWithDebInfo patches=62590e9b33a8f72b608a72b87147a306e7cb20766ea53c6b8e0a183fa6cb7635 arch=darwin-catalina-x86_64
    ^g2o@20200410_git%apple-clang@12.0.0~ipo build_type=RelWithDebInfo arch=darwin-catalina-x86_64
        ^ceres-solver@1.14.0%apple-clang@12.0.0~examples~ipo+shared~suitesparse build_type=RelWithDebInfo arch=darwin-catalina-x86_64
            ^glog@0.4.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^gflags@2.2.2%apple-clang@12.0.0~ipo build_type=RelWithDebInfo arch=darwin-catalina-x86_64
            ^intel-mkl@2020.0.166%apple-clang@12.0.0~ilp64+shared threads=none arch=darwin-catalina-x86_64
        ^freeglut@3.2.1%apple-clang@12.0.0~ipo build_type=RelWithDebInfo arch=darwin-catalina-x86_64
            ^inputproto@2.3.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^util-macros@1.19.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^libx11@1.7.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^kbproto@1.0.7%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^libxcb@1.14%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^libpthread-stubs@0.4%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^libxau@1.0.8%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^xproto@7.0.31%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^libxdmcp@1.1.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^xcb-proto@1.14.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^xextproto@7.3.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^xtrans@1.3.5%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^libxi@1.7.6%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^fixesproto@5.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^libxext@1.3.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^libxfixes@5.0.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^libxrandr@1.5.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^libxrender@0.9.10%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^renderproto@0.11.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^randrproto@1.5.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^libxxf86vm@1.1.4%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^xf86vidmodeproto@2.3.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^opengl@2.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^openglu@1.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^xrandr@1.5.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
        ^libqglviewer@2.7.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^qt@5.15.2%apple-clang@12.0.0~dbus~debug~doc~examples+framework~gtk+gui+opengl~phonon+shared+sql+ssl+tools~webkit patches=7f34d48d2faaa108dc3fcc47187af1ccd1d37ee0f931b42597b820f03a99864c arch=darwin-catalina-x86_64
                ^double-conversion@2.0.1%apple-clang@12.0.0~ipo build_type=RelWithDebInfo arch=darwin-catalina-x86_64
                ^freetype@2.10.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^libpng@1.6.37%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^glib@2.66.2%apple-clang@12.0.0~libmount patches=b3fd45063a19c871048aa1f28692293ab8971a871bdcbe65f06f17fdd79db9e2 tracing=none arch=darwin-catalina-x86_64
                    ^gettext@0.21%apple-clang@12.0.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-catalina-x86_64
                        ^tar@1.32%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^libffi@3.3%apple-clang@12.0.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=darwin-catalina-x86_64
                    ^meson@0.56.0%apple-clang@12.0.0 patches=7a7ff3bffb5c1996faf178da6765d578394624edb96fe9297bf21f2e3cd9ebda arch=darwin-catalina-x86_64
                        ^ninja@1.10.1%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^python@3.8.6%apple-clang@12.0.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=darwin-catalina-x86_64
                                ^expat@2.2.10%apple-clang@12.0.0~libbsd arch=darwin-catalina-x86_64
                                ^sqlite@3.33.0%apple-clang@12.0.0+column_metadata+fts~functions~rtree arch=darwin-catalina-x86_64
                        ^py-setuptools@50.3.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^pcre@8.44%apple-clang@12.0.0~jit+multibyte+utf arch=darwin-catalina-x86_64
                ^harfbuzz@2.6.8%apple-clang@12.0.0~graphite2 arch=darwin-catalina-x86_64
                    ^cairo@1.16.0%apple-clang@12.0.0~X~fc~ft~gobject~pdf~png~svg patches=7c4da77767fe9feb03f8051def0832f0c67f99162913275cfa127a88df19cf51 arch=darwin-catalina-x86_64
                        ^autoconf@2.69%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                            ^m4@1.4.18%apple-clang@12.0.0+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=darwin-catalina-x86_64
                                ^libsigsegv@2.12%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^automake@1.16.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^libtool@2.4.6%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^pixman@0.40.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^icu4c@67.1%apple-clang@12.0.0 cxxstd=11 arch=darwin-catalina-x86_64
                ^libjpeg-turbo@2.0.4%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                    ^nasm@2.15.05%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^libmng@2.0.3%apple-clang@12.0.0~ipo build_type=RelWithDebInfo arch=darwin-catalina-x86_64
                    ^lcms@2.9%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                        ^libtiff@4.1.0%apple-clang@12.0.0 arch=darwin-catalina-x86_64
                ^pcre2@10.35%apple-clang@12.0.0~jit+multibyte arch=darwin-catalina-x86_64
        ^suite-sparse@5.8.1%apple-clang@12.0.0~cuda~openmp+pic~tbb arch=darwin-catalina-x86_64
            ^gmp@6.1.2%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^metis@5.1.0%apple-clang@12.0.0~gdb~int64~real64+shared build_type=Release patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1 arch=darwin-catalina-x86_64
            ^mpfr@4.0.2%apple-clang@12.0.0 patches=3f80b836948aa96f8d1cb9cc7f3f55973f19285482a96f9a4e1623d460bcccf0 arch=darwin-catalina-x86_64
                ^autoconf-archive@2019.01.06%apple-clang@12.0.0 arch=darwin-catalina-x86_64
    ^pangolin@master%apple-clang@12.0.0~ipo build_type=RelWithDebInfo arch=darwin-catalina-x86_64
        ^glew@2.1.0%apple-clang@12.0.0~ipo build_type=RelWithDebInfo arch=darwin-catalina-x86_64
            ^libice@1.0.9%apple-clang@12.0.0 arch=darwin-catalina-x86_64
            ^libsm@1.2.3%apple-clang@12.0.0 arch=darwin-catalina-x86_64
    ^yaml-cpp@0.6.3%apple-clang@12.0.0~ipo+pic+shared~tests build_type=RelWithDebInfo arch=darwin-catalina-x86_64
```
Some of these packages aren't yet in Spack, but they will be soon.

By "transient dependency" I mean a dependency of a dependency. By default, Spack includes all direct and transient dependencies via the compiler wrappers. `dealii` is the only package I know of that has broken because of this, and has an explicit `transitive_rpaths = False`.

**Comment by mgsternberg** [comment]
@adamjstewart Good to have a concrete example now. `openmpi` is triggered by `opencv`, despite the latter's copious number of `~`, even `~lapack`. I don't use Catalina yet, but I suppose that doesn't matter here …

The `intel-mkl` package attempts to be helpful and link ScaLAPACK because it is provided, yet not otherwise handled by Spack (IIRC – it's been a while since I used ScaLAPACK at all). I think it's necessary to scale back the helpfulness and not attempt ScaLAPACK linkage at all, either flatly, or more surgically *if* the spec tree can be inspected and contains, very roughly, `+mpi~mpich` or `~lapack`. 🤔

**Comment by adamjstewart** [comment]
Yes, `opencv+videoio` requires `mpi`, and `ceres-solver` requires `lapack`. I don't think any package actually requires `scalapack`.

**Comment by alalazo** [comment]
This issue seems related to the `intel-parallel-studio` recipe, on Intel based macOS systems. Closing, since it's probably not very relevant anymore (we deprecated intel packages pre oneAPI). Let me know if you think something should still be discussed in this issue.
