### ISSUE TITLE
Spack install mpich even if it is specified in packages.yaml

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#2093]
Here is simple example:

I have specified `mpich` as an external package in `packages.yaml` :

```bash
    mpich:
        paths:
            mpich@3.2%gcc@6.2.0: /usr/local
        version: [3.2]
```
(I didn't specify buildable false because I want to build it with clang compiler).

Now lets look at `HDF5` spec:

```
spack spec hdf5 +mpi %gcc
Input spec
------------------------------
  hdf5%gcc+mpi

Normalized
------------------------------
  hdf5%gcc+mpi
      ^mpi
      ^zlib@1.1.2:

Concretized
------------------------------
  hdf5@1.10.0-patch1%gcc@6.2.0+cxx~debug~fortran+mpi+shared~szip~threadsafe arch=darwin-elcapitan-x86_64
      ^mpich@3.2%gcc@6.2.0+hydra+pmi+romio~verbs arch=darwin-elcapitan-x86_64
      ^zlib@1.2.8%gcc@6.2.0 arch=darwin-elcapitan-x86_64
```

If I try install above `mpich` then:
```bash
spack install --fake mpich@3.2%gcc@6.2.0+hydra+pmi+romio~verbs arch=darwin-elcapitan-x86_64
==> mpich is externally installed in /usr/local
```
Which is expected behaviour. Now if I try to install `HDF5`, it builds `mpich`:

```bash
spack install --fake hdf5 +mpi %gcc
==> Installing hdf5
==> Installing mpich
==> Building mpich
==> Successfully installed mpich
  Fetch: .  Build: 0.12s.  Total: 0.12s.
[+] /Users/kumbhar/workarena/software/sources/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0/mpich-3.2-vawupusw7g7zwadhoaqfefzyizosh2ml
==> zlib is already installed in /Users/kumbhar/workarena/software/sources/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0/zlib-1.2.8-fbuurtffrrl7o2h5q4vnf7dgf67bo7au
==> Building hdf5
==> Successfully installed hdf5
  Fetch: .  Build: 0.29s.  Total: 0.29s.
[+] /Users/kumbhar/workarena/software/sources/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0/hdf5-1.10.0-patch1-3mx2kc2rcd52gkysod5k2vccsj4m6f4u
```

Why it's building `mpich`? If I explicitly specify `mpich` dependency  then it doesn't :

```bash
spack install --fake hdf5 +mpi %gcc ^mpich
==> Installing hdf5
==> mpich is externally installed in /usr/local
==> zlib is already installed in /Users/kumbhar/workarena/software/sources/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0/zlib-1.2.8-fbuurtffrrl7o2h5q4vnf7dgf67bo7au
==> Building hdf5
==> Successfully installed hdf5
  Fetch: .  Build: 0.29s.  Total: 0.29s.
[+] /Users/kumbhar/workarena/software/sources/spack/opt/spack/darwin-elcapitan-x86_64/gcc-6.2.0/hdf5-1.10.0-patch1-3mx2kc2rcd52gkysod5k2vccsj4m6f4u
==> Warning: Dependency missing due to corrupt install directory:
  /usr/local
  Install prefix exists but contains no spec.yaml:
      /usr/local
```
Am I missing anything? (recent concretisation issue #2068)

**Comment by pramodk** [comment]
Another question, if `mpi` variant is `on` by default, why can't we say : 

```bash
spack spec hdf5 ^mpich
Input spec
------------------------------
  hdf5
      ^mpich

Normalized
------------------------------
==> Error: hdf5 does not depend on mpich
```
We have to specify `+mpi` on command line.

**Comment by citibeth** [comment]
> Another question, if mpi variant is on by default, why can't we say : 

This is a longstanding issue with Spack.  There are threads that explain it (it has to do with virtual packages and forwarding stuff through them).

BUT... the best approach IMHO it is to put all desired versioning information in `packages.yaml`, and then all my `spack install` command lines are "clean", i.e. no variants or `^` stuff.  Here is my `packages.yaml` for your perusal:

[packages.yaml.txt](https://github.com/LLNL/spack/files/546384/packages.yaml.txt)

> Why it's building mpich?

Because it needs `mpich@3.2%gcc@6.2.0+hydra+pmi+romio~verbs` but you only promised it `mpich@3.2%gcc@6.2.0` in your `packages.yaml`.  If `+hydra`, `+pmi` or `+romio` are not turn on by default in `mpich/package.py`, then Spack will think the installed version is not sufficient.

I don't know why `spack install --fake` worked as expected but the later `spack install` did not.

(BTW... linking directly to stuff in `/usr/local` could be dangerous.  Builds could pick up any other packages that happen to exist there; and these could end up overshadowing stuff Spack built itself.  This is a known issue...)

You'll probably be happier if you can just let Spack build `mpich`.  If not, you might need to symlink it into its own install tree so you don't get pollution from `/usr/local`.

**Comment by pramodk** [comment]
@citibeth :

>> Why it's building mpich?

>  Because it needs mpich@3.2%gcc@6.2.0+hydra+pmi+romio~verbs but you only promised it mpich@3.2%gcc@6.2.0 in your packages.yaml. If +hydra, +pmi or +romio are not turn on by default in mpich/package.py, then Spack will think the installed version is not sufficient.

` +hydra, +pmi or +romio` are on by default in `mpich` and hence I didn't expect the build. Here is another example : 

Spec for package show me:

```bash
Concretized
------------------------------
  testpkg@develop%pgi@16.5-0+mpi+neurodamusmod+report~tests arch=linux-redhat6-x86_64
      ^cmake@3.6.1%pgi@16.5-0~doc+ncurses+openssl~ownlibs~qt arch=linux-redhat6-x86_64
      ^openmpi@1.10.2%pgi@16.5-0~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm+verbs+vt arch=linux-redhat6-x86_64
```

Ok, I copied that spec for `openmpi` and added entry into `packages.yaml` : 

```bash
    openmpi:
        modules:
            openmpi@1.10.2%pgi@16.5-0~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm+verbs+vt arch=linux-redhat6-x86_64: pgi/mpich/16.5
           #also tried
           #openmpi@1.10.2%pgi@16.5-0 arch=linux-redhat6-x86_64: pgi/mpich/16.5
        version: [1.10.2]
        buildable: False
```

And  spack still installs openmpi  : 

```bash
spack install -v --fake testpkg@develop +report %pgi ^openmpi
==> Installing testpkg
==> cmake is externally installed in cmake-3.6.1-gcc-4.4.7-xhpqagp
==> Installing openmpi
==> Warning: OpenMPI : FORTRAN compiler not found
==> Warning: OpenMPI : FORTRAN bindings will be disabled
==> Building openmpi
==> Warning: OpenMPI : FORTRAN compiler not found
==> Warning: OpenMPI : FORTRAN bindings will be disabled
==> Warning: OpenMPI : FORTRAN compiler not found
==> Warning: OpenMPI : FORTRAN bindings will be disabled
==> Warning: OpenMPI : FORTRAN compiler not found
==> Warning: OpenMPI : FORTRAN bindings will be disabled
==> Successfully installed openmpi
.....
```

But now if I add `paths` instead of `modules` then it works fine:

```bash
        paths:
            openmpi@1.10.2%pgi@16.5-0 arch=linux-redhat6-x86_64: /gpfs/bbp.cscs.ch/apps/viz/tools/pgi/16.5/linux86-64/2016/mpi/openmpi-1.10.2
```

So there is some bug in concretisation.

**Comment by citibeth** [comment]
You got me there.  I agree, looks like a bug.

**Comment by tgamblin** [comment]
@pramodk: just to check is this fixed by #2071?

**Comment by pramodk** [comment]
@tgamblin : i will try to see if I can reproduce the issue later this week.

**Comment by pramodk** [comment]
@tgamblin : I am still having this issue (but now working on some different cluster with `OpenMPI`). To provide more info, here is what I see:
```bash

#application asks for dependencies
    ...
    depends_on('libtool', type='build')
    depends_on('mpi@1:', when='+mpi')    #+mpi is true by default

#my packages.yaml
    openmpi:
        paths:
            openmpi@1.10.2: /gpfs/bbp.cscs.ch/apps/viz/tools/pgi/16.5/linux86-64/2016/mpi/openmpi-1.10.2
        buildable: False
        version: [1.10.2]

#what openmpi package.py has
provides('mpi@:3.0', when='@1.7.5:')
```
In this case spack try to install `OpenMPI` (and note that there is `buildable` `false`). From my understanding `openmpi@1.10.2` should satisfy  `mpi@1:`? 

(If I change `packages.yaml` version from `1.10.2` to `2.0.1` then spack doesn't try to install `OpenMPI`).

AM I missing anything obvious here?

**Comment by pramodk** [comment]
This issue has also been reported in #2242. And this is driving me crazy : 

```bash
# packages.yaml on my mac

    mpich:
        paths:
            mpich@develop: /usr/local             #changed from 3.2 to develop version to see if that changes anything
        buildable: False
        version: [develop]

# first installation says mpi externally installed
spack install neuron  +mpi %clang
==> Installing neuron
==> python is externally installed in /System/Library/Frameworks/Python.framework/Versions/2.7
==> automake is externally installed in /usr/local
==> libtool is externally installed in /usr/local
==> mpich is externally installed in /usr/local

# +tau variant tries to install mpich

spack install neuron +tau +mpi %clang
==> Installing neuron
==> tau is already installed in /Users/kumbhar/workarena/software/sources/spack/opt/spack/darwin-elcapitan-x86_64/clang-3.9.0/tau-2.25.2-6qtlovfx6p42reo72xvibo2wtgawdbqx
==> python is externally installed in /System/Library/Frameworks/Python.framework/Versions/2.7
==> automake is externally installed in /usr/local
==> libtool is externally installed in /usr/local
==> Installing mpich
==> Warning: There is no checksum on file to fetch mpich@develop safely.
  Fetch anyway? [y/N] ==> Error: EOFError: EOF when reading a line

$ spack spec neuron +tau +mpi %clang

Concretized
--------------------------------
neuron@develop%clang@3.9.0~cross-compile+mpi+python+static+tau arch=darwin-elcapitan-x86_64
    ^autoconf@system%clang@3.9.0 arch=darwin-elcapitan-x86_64
    ^automake@system%clang@3.9.0 arch=darwin-elcapitan-x86_64
    ^libtool@system%clang@3.9.0 arch=darwin-elcapitan-x86_64
    ^mpich@develop%clang@3.9.0+hydra+pmi+romio~verbs arch=darwin-elcapitan-x86_64
    ^pkg-config@system%clang@3.9.0+internal_glib arch=darwin-elcapitan-x86_64
    ^python@2.7.10%clang@3.9.0~tk~ucs4 arch=darwin-elcapitan-x86_64
    ^tau@2.25.2%clang@3.9.0+comm~download+mpi~ompt~openmp+phase~scorep arch=darwin-elcapitan-x86_64
        ^pdt@3.22.1%clang@3.9.0 arch=darwin-elcapitan-x86_64


$ spack spec neuron  +mpi %clang
Concretized
--------------------------------
neuron@develop%clang@3.9.0~cross-compile+mpi+python+static~tau arch=darwin-elcapitan-x86_64
    ^autoconf@system%clang@3.9.0 arch=darwin-elcapitan-x86_64
    ^automake@system%clang@3.9.0 arch=darwin-elcapitan-x86_64
    ^libtool@system%clang@3.9.0 arch=darwin-elcapitan-x86_64
    ^mpich@develop%clang@3.9.0+hydra+pmi+romio~verbs arch=darwin-elcapitan-x86_64
    ^pkg-config@system%clang@3.9.0+internal_glib arch=darwin-elcapitan-x86_64
    ^python@2.7.10%clang@3.9.0~tk~ucs4 arch=darwin-elcapitan-x86_64
```

If someone can provide some insights/workaround, it will be really helpful! And if you need any info for debug, I would be happy to provide.

**Comment by pramodk** [comment]
Ok, here is some more information : 

I am looking into `Package.do_install()` and checking if `external` is setup properly. I added following debug/print statement: 
```bash
--- a/lib/spack/spack/package.py
+++ b/lib/spack/spack/package.py
@@ -1176,6 +1176,7 @@ class PackageBase(object):
         # First, install dependencies recursively.
         if install_deps:
             for dep in self.spec.dependencies():
+                print "dep : ", dep, dep.external, dep.package.spec.external
                 dep.package.do_install(….
```
Now I see following (see the end of below line) : 
```bash
dep :  mpich@3.2%pgi@16.5-0+hydra+pmi+romio~verbs arch=linux-rhel6-x86_64 /gpfs-path/16.5/linux86-64/2016/mpi/openmpi-1.10.2 None
```

Is that `dep.package.spec.external` supposed to be `None` ? Because of this when we call `dep.package.do_install`, the `do_install` method checks `self.spec.external`, which is `None`, and hence continue installing `mpich`.

@alalazo, @tgamblin, @davydden @adamjstewart : any hints to further debug this issue?

**Comment by alalazo** [comment]
As of 8d118104c79bca646b193f84857b75b7f54359df this works as intended:
```console
$ spack spec hdf5 +mpi %gcc
Input spec
--------------------------------
hdf5%gcc+mpi

Concretized
--------------------------------
hdf5@1.12.1%gcc@9.3.0~cxx~fortran~hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo patches=ee351eb arch=linux-ubuntu20.04-icelake
    ^cmake@3.22.2%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-icelake
        ^ncurses@6.2%gcc@9.3.0~symlinks+termlib abi=none arch=linux-ubuntu20.04-icelake
            ^pkgconf@1.8.0%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
        ^openssl@1.1.1m%gcc@9.3.0~docs certs=system arch=linux-ubuntu20.04-icelake
            ^perl@5.34.0%gcc@9.3.0+cpanm+shared+threads arch=linux-ubuntu20.04-icelake
                ^berkeley-db@18.1.40%gcc@9.3.0+cxx~docs+stl patches=b231fcc arch=linux-ubuntu20.04-icelake
                ^bzip2@1.0.8%gcc@9.3.0~debug~pic+shared arch=linux-ubuntu20.04-icelake
                    ^diffutils@3.8%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                        ^libiconv@1.16%gcc@9.3.0 libs=shared,static arch=linux-ubuntu20.04-icelake
                ^gdbm@1.19%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                    ^readline@8.1%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                ^zlib@1.2.11%gcc@9.3.0+optimize+pic+shared arch=linux-ubuntu20.04-icelake
                    ^python@2.7.18%gcc@9.3.0+bz2+ctypes+dbm~debug+ensurepip~libxml2~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared~sqlite3~ssl~tix~tkinter~ucs4+uuid~zlib patches=6bbcac8,7e1bd91 arch=linux-ubuntu20.04-icelake
                        ^expat@2.4.6%gcc@9.3.0+libbsd arch=linux-ubuntu20.04-icelake
                            ^libbsd@0.11.5%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                                ^libmd@1.0.4%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                        ^gettext@0.21%gcc@9.3.0+bzip2+curses+git~libunistring~libxml2+tar+xz arch=linux-ubuntu20.04-icelake
                            ^tar@1.34%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                            ^xz@5.2.5%gcc@9.3.0~pic libs=shared,static arch=linux-ubuntu20.04-icelake
                        ^libffi@3.4.2%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                        ^util-linux-uuid@2.37.4%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
    ^mpich@3.2%gcc@9.3.0~argobots+fortran+hwloc+hydra+libxml2+pci+romio~slurm~two_level_namespace~verbs+wrapperrpath device=ch4 netmod=ofi pmi=pmi arch=linux-ubuntu20.04-icelake
```

**Comment by pramodk** [comment]
> Edit : I am not able to reliably confirm the last part about paths vs. modules. Sometime it works, sometime it doesn't! Difficult to understand whats going on!

As mentioned in https://github.com/spack/spack/issues/2093#issuecomment-255606876, the behaviour was bit random. But I am sure lot has changed during last 5.5 years and don't have recent memory of this issue. So good to close this!
