### ISSUE TITLE
Installation issue: hdf  +external-xdr ^libtirpc failing (libtirpc issue???)

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#23297]
I am attempting to build hdf on a 64 bit system using libtirpc as external-xdr, but the build fails complaining that the hdf configure parameter --enable-hdf4-xdr  is not supported for 64 bit mode.

Debugging the hdf configure script a bit further, it appears that spack is correctly not passing either --enable-hdf4-xdr or --disable-hdf4-xdr (due to a bug in hdf configure script the latter is treated the same as the former), and that the hdf configure script attempts to determine if an external xdr is available by compiling a test code, which fails.

The test code appears to be failing because it cannot find the libtirpc header files types.h, xdr.h, which libtirpc installs into
``` `spack location -i libtirpc`/include/tirpc/rpc ```
but the include directory spack is using is only ``` `spack location -i libtirpc`/include```, i.e. stops at the include directory.  (I.e., the value of  self.spec['rpc'].headers.cpp_flags inside the hdf recipe is "-I<PREFIX to libtirpc>/include").  This is causing issues because the hdf test code is doing a simple
``` #include <rpc/xdr.h>``` as can be seen in the attached config.log (further down).

I believe this to be a bug in the spack recipe for libtirpc, as not only does the test code usage seem correct, but even the types.h file from libtirpc has include statements like
```#include <netconfig.h>```
which would also require and -I flags to include the tirpc subdirectory in order to work.

As a test, I manually added symlinks in the libtirpc installation directory
```console
cd `spack location -i libtircp`
cd include
ln tircp/* .
```
and the spack installation of hdf succeeded.  

So I believe the proper solution is to modify libtirpc to return a path to its header files including the tirpc subdirectory (or perhaps both with and without it, in case anything was expecting the additional tirpc layer), but I am not sure how to achieve that in spack.

### Steps to reproduce the issue
```console
$ spack install hdf@4.2.14 +external-xdr +fortran ~java ~netcdf +pic ~shared +szip %gcc@8.4.0
...
configure: error: --enable-hdf4-xdr is not supported for 64 bit mode.
```
The configuration has the provider for rpc set to libtirpc.  We are using libtirpc@1.2.6

### Information on your system
```console
$ spack debug report
* **Spack:** 0.14.2-6183-fa31a33599
* **Python:** 3.6.8
* **Platform:** linux-rhel8-x86_64
* **Concretizer:** original
```
As mentioned previously, our configuration includes
```console
packages:
  #Default settings for all packages
  all:
    buildable: true
    providers::
      ...
      rpc: [libtirpc]
     ...
```

### Additional information

* [spack-configure-args.txt](https://github.com/spack/spack/files/6387344/spack-configure-args.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/6387345/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6387346/spack-build-env.txt)
* [spack-build-02-configure-out.txt](https://github.com/spack/spack/files/6387347/spack-build-02-configure-out.txt)
* [spack-build-01-autoreconf-out.txt](https://github.com/spack/spack/files/6387348/spack-build-01-autoreconf-out.txt)
* [config.log](https://github.com/spack/spack/files/6387469/config.log)

@lrknox as a maintainer of hdf package.
No maintainers found for libtirpc (which I suspect is the real culprit)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by cessenat** [comment]
Hello @payerle I do not have this issue with a recent spack ; it seems your version is 0.14 and the problem may have been corrected since.
Possibly by yourself see https://github.com/spack/spack/pull/15993.
Am I wrong ?

**Comment by payerle** [comment]
I was attempting to upgrade from spack-0.14 to spack 0.16, and I did not notice that 
spack debug report was still showing 0.14

So, obviously I did something wrong on upgrade attempt --- I suspect my spack is in a weird state.  
So I will close this ticket, fix my upgrade, and try again.
