### ISSUE TITLE
axom 0.4.0: build fails: ld: cannot find -lopenmp

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#23339]
`axom@0.4.0` fails to build using:
* spack@develop (087110bcb013566f6ba392d4c271e891f4b3a2b1 from `Thu Apr 29 16:43:01 2021 +0200`)
* Ubuntu 20.04 - GCC 9.3.0
* RHEL 8 - GCC 8.3.1

Using container: `ecpe4s/ubuntu20.04-runner-x86_64:2021-03-10`
Concrete spec: [axom-ayoawp.spec.yaml.txt](https://github.com/spack/spack/files/6400068/axom-ayoawp.spec.yaml.txt)
Build log: [axom-build-out.txt](https://github.com/spack/spack/files/6400078/axom-build-out.txt)

```
$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it

$> spack install --cache-only --only dependencies --include-build-deps -f ./axom-ayoawp.spec.yaml
... OK

$> spack install --no-cache -f ./axom-ayoawp.spec.yaml
...
==> Installing axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx
==> Warning: Missing a source id for conduit@develop
==> No patches needed for axom
==> axom: Executing phase: 'initconfig'
==> axom: Executing phase: 'cmake'
==> axom: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

4 errors found in build log:
     500          |   ^~~~~~
     501    [ 27%] Linking CXX executable ../../../examples/core_utilities_ex
     502    cd /tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-build-ayoawpa/axom/core/examples && /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/cma
            ke-3.19.7-7zkgd4xkg62fl5x2upq4mof5dkkkg3u4/bin/cmake -E cmake_link_script CMakeFiles/core_utilities_ex.dir/link.txt --verbose=1
     503    /opt/spack/lib/spack/env/gcc/g++      -Wall -Wextra  -O2 -g -DNDEBUG -Wl,--export-dynamic -rdynamic -fopenmp -Wl,-rpath -Wl,/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mp
            ich-3.4.1-hm77n22t37spis2wa4wssqtmqnvuhfz6/lib -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hwloc-2.4.1-6lkpnwfflqhxirx554hzmbkck4v6vs25/lib CMakeFiles/core_utilities_ex
            .dir/core_utilities.cpp.o ../CMakeFiles/core.dir/utilities/FileUtilities.cpp.o ../CMakeFiles/core.dir/utilities/StringUtilities.cpp.o ../CMakeFiles/core.dir/utilities/Utilities.cpp.o
             ../CMakeFiles/core.dir/utilities/About.cpp.o ../CMakeFiles/core.dir/utilities/nvtx/interface.cpp.o ../CMakeFiles/core.dir/utilities/nvtx/Range.cpp.o ../CMakeFiles/core.dir/numerics/
            polynomial_solvers.cpp.o ../CMakeFiles/core.dir/Types.cpp.o -o ../../../examples/core_utilities_ex  -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/umpire-4.1.2-of
            zdoemhytkqvaq4vaeifnarrdhfo6ep/lib:/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/raja-0.13.0-l22sfjknjzhqf6vxsr34apzqkmz3zixd/lib:/opt/spack/opt/spack/linux-ubuntu20.04-x86
            _64/gcc-9.3.0/mpich-3.4.1-hm77n22t37spis2wa4wssqtmqnvuhfz6/lib /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/umpire-4.1.2-ofzdoemhytkqvaq4vaeifnarrdhfo6ep/lib/libumpire.so
            /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/raja-0.13.0-l22sfjknjzhqf6vxsr34apzqkmz3zixd/lib/libRAJA.so /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.
            1-hm77n22t37spis2wa4wssqtmqnvuhfz6/lib/libmpi.so /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.1-hm77n22t37spis2wa4wssqtmqnvuhfz6/lib/libmpicxx.so /opt/spack/opt/
            spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.1-hm77n22t37spis2wa4wssqtmqnvuhfz6/lib/libmpifort.so -lopenmp -ldl
     504    [ 27%] Building CXX object axom/mint/CMakeFiles/mint.dir/mesh/blueprint.cpp.o
     505    cd /tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-build-ayoawpa/axom/mint && /opt/spack/lib/spack/env/gcc/g++ -DAXOM_DEBUG -I/tmp/root/spack-stag
            e/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-build-ayoawpa/include -I/tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-src/src -I
            /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/camp-0.1.0-cmr4rmbw36urn2b72ghkesab3qepb3iz/include -I/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/raja-0.13.0-l22s
            fjknjzhqf6vxsr34apzqkmz3zixd/include -isystem /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/umpire-4.1.2-ofzdoemhytkqvaq4vaeifnarrdhfo6ep/include -isystem /opt/spack/opt/sp
            ack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.1-hm77n22t37spis2wa4wssqtmqnvuhfz6/include -Wall -Wextra  -O2 -g -DNDEBUG -fPIC -fopenmp -std=c++14 -o CMakeFiles/mint.dir/mesh/bluep
            rint.cpp.o -c /tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-src/src/axom/mint/mesh/blueprint.cpp
  >> 506    /usr/bin/ld: cannot find -lopenmp
  >> 507    collect2: error: ld returned 1 exit status
  >> 508    make[2]: *** [axom/core/examples/CMakeFiles/core_utilities_ex.dir/build.make:127: examples/core_utilities_ex] Error 1
     509    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-build-ayoawpa'
  >> 510    make[1]: *** [CMakeFiles/Makefile2:929: axom/core/examples/CMakeFiles/core_utilities_ex.dir/all] Error 2
     511    make[1]: *** Waiting for unfinished jobs....
     512    [ 28%] Building CXX object axom/slam/examples/tinyHydro/CMakeFiles/slam_tinyHydro_ex.dir/PolygonMeshXY.cpp.o
     513    cd /tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-build-ayoawpa/axom/slam/examples/tinyHydro && /opt/spack/lib/spack/env/gcc/g++ -DAXOM_DEBUG -I/
            tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-build-ayoawpa/include -I/tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppcey
            rx/spack-src/src -I/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/camp-0.1.0-cmr4rmbw36urn2b72ghkesab3qepb3iz/include -I/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3
            .0/raja-0.13.0-l22sfjknjzhqf6vxsr34apzqkmz3zixd/include -isystem /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/umpire-4.1.2-ofzdoemhytkqvaq4vaeifnarrdhfo6ep/include -isyste
            m /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.1-hm77n22t37spis2wa4wssqtmqnvuhfz6/include -isystem /tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4
            spywmjvpppceyrx/spack-src/src/thirdparty -Wall -Wextra  -O2 -g -DNDEBUG -fPIC -fopenmp -std=c++14 -o CMakeFiles/slam_tinyHydro_ex.dir/PolygonMeshXY.cpp.o -c /tmp/root/spack-stage/spa
            ck-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-src/src/axom/slam/examples/tinyHydro/PolygonMeshXY.cpp
     514    [ 29%] Building CXX object axom/mint/CMakeFiles/mint.dir/mesh/CurvilinearMesh.cpp.o
     515    cd /tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-build-ayoawpa/axom/mint && /opt/spack/lib/spack/env/gcc/g++ -DAXOM_DEBUG -I/tmp/root/spack-stag
            e/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-build-ayoawpa/include -I/tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-src/src -I
            /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/camp-0.1.0-cmr4rmbw36urn2b72ghkesab3qepb3iz/include -I/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/raja-0.13.0-l22s
            fjknjzhqf6vxsr34apzqkmz3zixd/include -isystem /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/umpire-4.1.2-ofzdoemhytkqvaq4vaeifnarrdhfo6ep/include -isystem /opt/spack/opt/sp
            ack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.1-hm77n22t37spis2wa4wssqtmqnvuhfz6/include -Wall -Wextra  -O2 -g -DNDEBUG -fPIC -fopenmp -std=c++14 -o CMakeFiles/mint.dir/mesh/Curvi
            linearMesh.cpp.o -c /tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-src/src/axom/mint/mesh/CurvilinearMesh.cpp
     516    [ 30%] Building CXX object axom/sidre/CMakeFiles/sidre.dir/core/View.cpp.o

See build log for details:
  /tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-build-out.txt
```

@white238

**Comment by white238** [comment]
There seems to be an unguarded openmp dependency in this release.  Can you use axom@develop?  I am currently fixing something but I can try to provide a patch in spack for this release once I track it down.

**Comment by eugeneswalker** [comment]
> Can you use axom@develop?

Yes, that worked! We would love a patch! Thank you.

**Comment by white238** [comment]
@eugeneswalker this was actually a pretty nasty set of problems that caused this.  I think i fixed it in the PR mentioned above.  Can you see if this fixes your problem?  My day is over and if you haven't responded I will try to reproduce this tomorrow.

**Comment by eugeneswalker** [comment]
> I think i fixed it in the PR mentioned above. Can you see if this fixes your problem?

Thank you for your quick work. Unfortunately, this didn't resolve the issue. I get the same error :(
```
  >> 440    /usr/bin/ld: cannot find -lopenmp
  >> 441    collect2: error: ld returned 1 exit status
  >> 442    make[2]: *** [axom/core/examples/CMakeFiles/core_utilities_ex.dir/build.make:127: examples/core_utilities_ex] Error 1
     443    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-axom-0.4.0-ayoawpaledknbjhc4spywmjvpppceyrx/spack-build-ayoawpa'
  >> 444    make[1]: *** [CMakeFiles/Makefile2:929: axom/core/examples/CMakeFiles/core_utilities_ex.dir/all] Error 2
```

**Comment by white238** [comment]
I think I was running into a first-come-first-set-the-version situation.  I am running it through a set of tests now.

**Comment by eugeneswalker** [comment]
This issue isn't resolved by #23356 as far as I can tell :(

**Comment by becker33** [comment]
I was overeager merging it. @white238 is working on a further fix (that I would have known to wait for if I had been slightly more patient).

**Comment by becker33** [comment]
Sorry for the wasted time :/
