### ISSUE TITLE
Lmod 'hierarchy' ignored

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#24216]
@becker33 I think this relates to #23703 . Basically, the old 'empty hierarchy' in my modules config seems to be overridden by the 'default' key in the spack lmod defaults -- but only for some packages.

I haven't spent the time to reproduce this on a completely clean build, and some of the packages are installed via environments, others aren't.

### Steps to reproduce the issue

```console
$ spack -d module lmod refresh -y trilinos%gcc@10
==> [2021-06-09-08:50:40.872745] Imported module from built-in commands
==> [2021-06-09-08:50:40.884989] Imported module from built-in commands
==> [2021-06-09-08:50:40.888085] Reading config file /projects/spack2020/etc/spack/defaults/config.yaml
==> [2021-06-09-08:50:40.928025] Reading config file /projects/spack2020/etc/spack/config.yaml
==> [2021-06-09-08:50:40.935245] DATABASE LOCK TIMEOUT: 3s
==> [2021-06-09-08:50:40.935351] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-06-09-08:50:41.101820] Reading config file /projects/spack2020/etc/spack/defaults/repos.yaml
==> [2021-06-09-08:50:41.104794] Reading config file /projects/spack2020/etc/spack/repos.yaml
==> [2021-06-09-08:50:42.180869] Reading config file /projects/spack2020/etc/spack/defaults/modules.yaml
==> [2021-06-09-08:50:42.193172] Reading config file /projects/spack2020/etc/spack/defaults/linux/modules.yaml
==> [2021-06-09-08:50:42.197015] Reading config file /projects/spack2020/etc/spack/modules.yaml
==> [2021-06-09-08:50:42.316378] Reading config file /projects/spack2020/etc/spack/compilers.yaml
==> [2021-06-09-08:50:42.357782] Regenerating lmod module files
==> [2021-06-09-08:50:43.520019] 	WRITE: trilinos@13.0.0%gcc@10.2.0~adios2~alloptpkgs+amesos~amesos2+anasazi+aztec+belos~boost~cgns~chaco~complex~debug~dtk+epetra+epetraext~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hypre+ifpack+ifpack2+intrepid~intrepid2~isorropia+kokkos~matio~mesquite~metis~minitensor+ml~mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado+shards+shared~shylu~stk+stratimikos~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo gotype=long_long arch=linux-rhel7-haswell/wcfgufe [/projects/spack2020/share/spack/lmod/linux-rhel7-x86_64/gcc/10.2.0/trilinos/13.0.0-wcfgufe.lua]
==> [2021-06-09-08:50:43.656952] Reading config file /projects/spack2020/etc/spack/defaults/packages.yaml
==> [2021-06-09-08:50:43.688764] Reading config file /projects/spack2020/etc/spack/packages.yaml
==> [2021-06-09-08:50:43.712536] 	WRITE: trilinos@13.0.0%gcc@10.2.0~adios2~alloptpkgs+amesos~amesos2+anasazi+aztec+belos~boost~cgns~chaco~complex~debug~dtk+epetra+epetraext~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hypre+ifpack+ifpack2+intrepid~intrepid2~isorropia+kokkos~matio~mesquite~metis~minitensor+ml+mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado+shards+shared~shylu~stk+stratimikos~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo gotype=long_long arch=linux-rhel7-haswell/rgammyu [/projects/spack2020/share/spack/lmod/linux-rhel7-x86_64/openmpi/3.1.6-vnidi5n/gcc/10.2.0/trilinos/13.0.0-rgammyu.lua]
==> [2021-06-09-08:50:43.799463] 	WRITE: trilinos@13.0.1%gcc@10.2.0~adios2~alloptpkgs+amesos+amesos2~amesos2basker+anasazi+aztec+belos~boost~cgns~chaco~complex~cuda~cuda_rdc~debug~dtk+epetra+epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hwloc~hypre+ifpack+ifpack2+intrepid~intrepid2~ipo~isorropia+kokkos~matio~mesquite~metis~minitensor+ml+mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado~scorec+shards+shared~shylu~stk~stokhos+stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~trilinoscouplings~wrapper~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=none cxxstd=11 gotype=long_long arch=linux-rhel7-haswell/6o7s6hd [/projects/spack2020/share/spack/lmod/linux-rhel7-x86_64/openmpi/4.0.5-2o7q6yb/gcc/10.2.0/trilinos/13.0.1-6o7s6hd.lua]
```

### Information on your system

```
$ spack config blame modules
---                                                           modules:
etc/spack/modules.yaml:2                    enable:
etc/spack/modules.yaml:3                    - lmod
etc/spack/modules.yaml:4                    prefix_inspections:
etc/spack/modules.yaml:5                      bin:
etc/spack/modules.yaml:6                      - PATH
etc/spack/modules.yaml:7                      man:
etc/spack/modules.yaml:8                      - MANPATH
etc/spack/modules.yaml:9                      share/man:
etc/spack/modules.yaml:10                     - MANPATH
etc/spack/modules.yaml:11                     share/aclocal:
etc/spack/modules.yaml:12                     - ACLOCAL_PATH
etc/spack/modules.yaml:13                     include: []
etc/spack/modules.yaml:14                     lib:
etc/spack/modules.yaml:15                     - LIBRARY_PATH
etc/spack/modules.yaml:16                     lib64:
etc/spack/modules.yaml:17                     - LIBRARY_PATH
etc/spack/modules.yaml:18                     lib/pkgconfig:
etc/spack/modules.yaml:19                     - PKG_CONFIG_PATH
etc/spack/modules.yaml:20                     lib64/pkgconfig:
etc/spack/modules.yaml:21                     - PKG_CONFIG_PATH
etc/spack/modules.yaml:22                     share/pkgconfig:
etc/spack/modules.yaml:23                     - PKG_CONFIG_PATH
                                              ? ''
                                              : - CMAKE_PREFIX_PATH
etc/spack/modules.yaml:26                       - ${PACKAGE}_ROOT
etc/spack/modules.yaml:26                   # These are configurations for the module set named "default"
etc/spack/modules.yaml:27                   lmod:
etc/spack/modules.yaml:28                     core_compilers:
etc/spack/modules.yaml:29                     - gcc@4.8.5
etc/spack/modules.yaml:30                     hash_length: 4
etc/spack/modules.yaml:31                     hierarchy: []
etc/spack/modules.yaml:32                     ^python:
etc/spack/modules.yaml:33                       autoload: direct
etc/spack/modules.yaml:34                     all:
etc/spack/modules.yaml:35                       suffixes:
etc/spack/modules.yaml:36                         ^python@2: py2
etc/spack/modules.yaml:37                         +cuda: cuda
etc/spack/modules.yaml:38                         +debug: debug
etc/spack/modules.yaml:39                         +mpi: mpi
etc/spack/modules.yaml:40                         +multithreaded: mt
etc/spack/modules.yaml:41                         +openmp: mt
etc/spack/modules.yaml:42                         +threads: mt
etc/spack/modules.yaml:43                         ~shared: static
etc/spack/modules.yaml:44                         cxxstd=98: c++98
etc/spack/modules.yaml:45                         cxxstd=14: c++14
etc/spack/modules.yaml:46                         cxxstd=17: c++17
etc/spack/modules.yaml:47                     lava:
etc/spack/modules.yaml:48                       template: group-restricted.lua
etc/spack/modules.yaml:49                     mcnp:
etc/spack/modules.yaml:48                       template: group-restricted.lua
etc/spack/modules.yaml:50                     mcnp-data:
etc/spack/modules.yaml:48                       template: group-restricted.lua
etc/spack/modules.yaml:51                     scale:
etc/spack/modules.yaml:48                       template: group-restricted.lua
etc/spack/modules.yaml:52                     scale-data:
etc/spack/modules.yaml:48                       template: group-restricted.lua
etc/spack/defaults/linux/modules.yaml:17    default:
etc/spack/defaults/linux/modules.yaml:18      prefix_inspections:
etc/spack/defaults/linux/modules.yaml:19        lib:
etc/spack/defaults/linux/modules.yaml:20        - LD_LIBRARY_PATH
etc/spack/defaults/linux/modules.yaml:21        lib64:
etc/spack/defaults/linux/modules.yaml:22        - LD_LIBRARY_PATH
etc/spack/defaults/modules.yaml:46            enable:
etc/spack/defaults/modules.yaml:46            - tcl
etc/spack/defaults/modules.yaml:47            # Default configurations if lmod is enabled
etc/spack/defaults/modules.yaml:50            lmod:
etc/spack/defaults/modules.yaml:51              hierarchy:
etc/spack/defaults/modules.yaml:52              - mpi
```

Module file:
```
$ cat etc/spack/modules.yaml
modules:
  enable::
    - lmod
  prefix_inspections:
    bin:
    - PATH
    man:
    - MANPATH
    share/man:
    - MANPATH
    share/aclocal:
    - ACLOCAL_PATH
    include:: []
    lib:
    - LIBRARY_PATH
    lib64:
    - LIBRARY_PATH
    lib/pkgconfig:
    - PKG_CONFIG_PATH
    lib64/pkgconfig:
    - PKG_CONFIG_PATH
    share/pkgconfig:
    - PKG_CONFIG_PATH
    '':
    - CMAKE_PREFIX_PATH
    - '${PACKAGE}_ROOT'
  lmod:
    core_compilers:
      - 'gcc@4.8.5'
    hash_length: 4
    hierarchy:: []
    ^python:
      autoload:  'direct'
    all:
      suffixes:
        '^python@2': py2
        '+cuda': 'cuda'
        '+debug': debug
        '+mpi': mpi
        '+multithreaded': mt
        '+openmp': mt
        '+threads': mt
        '~shared': 'static'
        'cxxstd=98': 'c++98'
        'cxxstd=14': 'c++14'
        'cxxstd=17': 'c++17'
    lava: &restricted
      template: 'group-restricted.lua'
    mcnp: *restricted
    mcnp-data: *restricted
    scale: *restricted
    scale-data: *restricted
```

### Additional information

* **Spack:** 0.16.2-3016-1fd1f1c93f
* **Python:** 3.8.6
* **Platform:** linux-rhel7-haswell
* **Concretizer:** clingo

**Comment by becker33** [comment]
I think this should be fixed by a more recent bugfix: https://github.com/spack/spack/pull/24151

**Comment by sethrj** [comment]
@becker33 Thanks, but sadly it's still broken:
```console
$ spack debug report
* **Spack:** 0.16.2-3076-849943c63d
* **Python:** 3.8.6
* **Platform:** linux-rhel7-haswell
* **Concretizer:** clingo
$ spack -d module lmod refresh -y trilinos%gcc@10
==> [2021-06-09-21:05:02.896827] Imported module from built-in commands
==> [2021-06-09-21:05:02.911513] Imported module from built-in commands
==> [2021-06-09-21:05:02.915125] Reading config file /projects/spack2020/etc/spack/defaults/config.yaml
==> [2021-06-09-21:05:02.959614] Reading config file /projects/spack2020/etc/spack/config.yaml
==> [2021-06-09-21:05:02.967261] DATABASE LOCK TIMEOUT: 3s
==> [2021-06-09-21:05:02.967376] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-06-09-21:05:03.129828] Reading config file /projects/spack2020/etc/spack/defaults/repos.yaml
==> [2021-06-09-21:05:03.132623] Reading config file /projects/spack2020/etc/spack/repos.yaml
==> [2021-06-09-21:05:04.193532] Reading config file /projects/spack2020/etc/spack/defaults/modules.yaml
==> [2021-06-09-21:05:04.205391] Reading config file /projects/spack2020/etc/spack/defaults/linux/modules.yaml
==> [2021-06-09-21:05:04.208780] Reading config file /projects/spack2020/etc/spack/modules.yaml
==> [2021-06-09-21:05:04.329109] Reading config file /projects/spack2020/etc/spack/compilers.yaml
==> [2021-06-09-21:05:04.368960] Regenerating lmod module files
==> [2021-06-09-21:05:05.286445] 	WRITE: trilinos@13.0.0%gcc@10.2.0~adios2~alloptpkgs+amesos~amesos2+anasazi+aztec+belos~boost~cgns~chaco~complex~debug~dtk+epetra+epetraext~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hypre+ifpack+ifpack2+intrepid~intrepid2~isorropia+kokkos~matio~mesquite~metis~minitensor+ml~mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado+shards+shared~shylu~stk+stratimikos~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo gotype=long_long arch=linux-rhel7-haswell/wcfgufe [/projects/spack2020/share/spack/lmod/linux-rhel7-x86_64/gcc/10.2.0/trilinos/13.0.0-wcfgufe.lua]
==> [2021-06-09-21:05:05.422303] Reading config file /projects/spack2020/etc/spack/defaults/packages.yaml
==> [2021-06-09-21:05:05.452247] Reading config file /projects/spack2020/etc/spack/packages.yaml
==> [2021-06-09-21:05:05.475443] 	WRITE: trilinos@13.0.0%gcc@10.2.0~adios2~alloptpkgs+amesos~amesos2+anasazi+aztec+belos~boost~cgns~chaco~complex~debug~dtk+epetra+epetraext~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hypre+ifpack+ifpack2+intrepid~intrepid2~isorropia+kokkos~matio~mesquite~metis~minitensor+ml+mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado+shards+shared~shylu~stk+stratimikos~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo gotype=long_long arch=linux-rhel7-haswell/rgammyu [/projects/spack2020/share/spack/lmod/linux-rhel7-x86_64/openmpi/3.1.6-vnidi5n/gcc/10.2.0/trilinos/13.0.0-rgammyu.lua]
==> [2021-06-09-21:05:05.563532] 	WRITE: trilinos@13.0.1%gcc@10.2.0~adios2~alloptpkgs+amesos+amesos2~amesos2basker+anasazi+aztec+belos~boost~cgns~chaco~complex~cuda~cuda_rdc~debug~dtk+epetra+epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~exodus+explicit_template_instantiation~float+fortran~glm~gtest+hdf5~hwloc~hypre+ifpack+ifpack2+intrepid~intrepid2~ipo~isorropia+kokkos~matio~mesquite~metis~minitensor+ml+mpi~muelu~mumps~netcdf~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado~scorec+shards+shared~shylu~stk~stokhos+stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~trilinoscouplings~wrapper~x11~xsdkflags~zlib~zoltan~zoltan2 build_type=RelWithDebInfo cuda_arch=none cxxstd=11 gotype=long_long arch=linux-rhel7-haswell/6o7s6hd [/projects/spack2020/share/spack/lmod/linux-rhel7-x86_64/openmpi/4.0.5-2o7q6yb/gcc/10.2.0/trilinos/13.0.1-6o7s6hd.lua]
$ spack config blame modules
---                                           modules:
/home/s3j/.spack/modules.yaml:2                 default:
/home/s3j/.spack/modules.yaml:3                   lmod:
/home/s3j/.spack/modules.yaml:4                     core_compilers:
/home/s3j/.spack/modules.yaml:5                     - gcc@4.8.5
.../etc/spack/defaults/modules.yaml:51              hierarchy:
.../etc/spack/defaults/modules.yaml:52              - mpi
.../etc/spack/defaults/modules.yaml:46            enable:
.../etc/spack/defaults/modules.yaml:46            - tcl
.../etc/spack/defaults/modules.yaml:47            # Default configurations if lmod is enabled
.../etc/spack/modules.yaml:2                    enable:
.../etc/spack/modules.yaml:3                    - lmod
.../etc/spack/modules.yaml:4                    prefix_inspections:
.../etc/spack/modules.yaml:5                      bin:
.../etc/spack/modules.yaml:6                      - PATH
.../etc/spack/modules.yaml:7                      man:
.../etc/spack/modules.yaml:8                      - MANPATH
.../etc/spack/modules.yaml:9                      share/man:
.../etc/spack/modules.yaml:10                     - MANPATH
.../etc/spack/modules.yaml:11                     share/aclocal:
.../etc/spack/modules.yaml:12                     - ACLOCAL_PATH
.../etc/spack/modules.yaml:13                     include: []
.../etc/spack/modules.yaml:14                     lib:
.../etc/spack/modules.yaml:15                     - LIBRARY_PATH
.../etc/spack/defaults/linux/modules.yaml:19      - LD_LIBRARY_PATH
.../etc/spack/modules.yaml:16                     lib64:
.../etc/spack/modules.yaml:17                     - LIBRARY_PATH
.../etc/spack/defaults/linux/modules.yaml:21      - LD_LIBRARY_PATH
.../etc/spack/modules.yaml:18                     lib/pkgconfig:
.../etc/spack/modules.yaml:19                     - PKG_CONFIG_PATH
.../etc/spack/modules.yaml:20                     lib64/pkgconfig:
.../etc/spack/modules.yaml:21                     - PKG_CONFIG_PATH
.../etc/spack/modules.yaml:22                     share/pkgconfig:
.../etc/spack/modules.yaml:23                     - PKG_CONFIG_PATH
...                                               ? ''
...                                               : - CMAKE_PREFIX_PATH
.../etc/spack/modules.yaml:26                       - ${PACKAGE}_ROOT
.../etc/spack/modules.yaml:26                   # These are configurations for the module set named "default"
.../etc/spack/modules.yaml:27                   lmod:
.../etc/spack/modules.yaml:28                     core_compilers:
.../etc/spack/modules.yaml:29                     - gcc@4.8.5
.../etc/spack/modules.yaml:30                     hash_length: 4
.../etc/spack/modules.yaml:31                     hierarchy: []
.../etc/spack/modules.yaml:32                     ^python:
.../etc/spack/modules.yaml:33                       autoload: direct
.../etc/spack/modules.yaml:34                     all:
.../etc/spack/modules.yaml:35                       suffixes:
.../etc/spack/modules.yaml:36                         ^python@2: py2
.../etc/spack/modules.yaml:37                         +cuda: cuda
.../etc/spack/modules.yaml:38                         +debug: debug
.../etc/spack/modules.yaml:39                         +mpi: mpi
.../etc/spack/modules.yaml:40                         +multithreaded: mt
.../etc/spack/modules.yaml:41                         +openmp: mt
.../etc/spack/modules.yaml:42                         +threads: mt
.../etc/spack/modules.yaml:43                         ~shared: static
.../etc/spack/modules.yaml:44                         cxxstd=98: c++98
.../etc/spack/modules.yaml:45                         cxxstd=14: c++14
.../etc/spack/modules.yaml:46                         cxxstd=17: c++17
.../etc/spack/modules.yaml:47                     lava:
.../etc/spack/modules.yaml:48                       template: group-restricted.lua
.../etc/spack/modules.yaml:49                     mcnp:
.../etc/spack/modules.yaml:48                       template: group-restricted.lua
.../etc/spack/modules.yaml:50                     mcnp-data:
.../etc/spack/modules.yaml:48                       template: group-restricted.lua
.../etc/spack/modules.yaml:51                     scale:
.../etc/spack/modules.yaml:48                       template: group-restricted.lua
.../etc/spack/modules.yaml:52                     scale-data:
.../etc/spack/modules.yaml:48                       template: group-restricted.lua
```

Also I don't know if this is related, but the `spack -d module lmod refresh` command itself generates `/home/s3j/.spack/modules.yaml`: I deleted it immediately before that. Why does it keep coming back? I find the `~/.spack` to be the most common source of surprises when trying to generate module files.

**Comment by becker33** [comment]
Ok, as a workaround you can take everything under the `lmod` key in your yaml file, and put it under `default:lmod` instead. I will try to figure out how to fix the backwards compatibility -- I misread the output from spack blame the first time.

**Comment by sethrj** [comment]
I made the following changes:
- moved `lmod` under `default`
- moved `enable` under `default`
- added `::` to `lib` and `lib64` which were surprisingly appending `LD_LIBRARY_PATH` (this was not formerly needed)

@becker33 Module generation now works as expected! Furthermore, it no longer regenerates the `~/.spack/modules.yaml` file.  Thanks!

Maybe rather than trying to add a "backward compatible" support, it's better to error out or provide an "upgrade" path. It seems like there are a lot of subtleties in how this is getting processed.

**Comment by sethrj** [comment]
@becker33 A coworker messaged me today:

> it doesn’t seem to be applying autoload: direct

and thankfully I was able to send him to your workaround comment. But this is the third time this week that someone's had to ask me about new breaking changes with modules. I think it's worth adding to https://github.com/spack/spack/issues/24223 . If there's no straightforward way to add bulletproof backward compatibility, but there's a way to detect and either upgrade or error old schemas, I think that should be a priority. The mysterious "some subtle aspect of modules break" is very hard to track down unless you're aware of the issue, because of the lag between pulling, generating modules, and using modules.

**Comment by alalazo** [comment]
> If there's no straightforward way to add bulletproof backward compatibility, but there's a way to detect and either upgrade or error old schemas, I think that should be a priority.

@sethjr Don't know if this fits what you have in mind, but we were discussing a command like #23053 that user can run and get warnings about their configurations or other relevant aspects of Spack.

**Comment by alalazo** [comment]
Closing, since from https://github.com/spack/spack/issues/24216#issuecomment-858209974 it seems it was fixed. @sethrj 
 feel free to reopen if I misunderstood.
