### ISSUE TITLE
Installation issue: rocm-smi-lib-4.2.0 creates dangling symlink

### ISSUE THREAD

**Issue by UweSauter** [LLNL/spack#24497]
@arjun-raj-kuppala  @srekolam

### Steps to reproduce the issue

```console
$ spack install rocm-smi-lib@4.2.0 %gcc@10.3.0 ^cmake@3.17.5
[…]

$ cd /opt/hlrs/spack/2021-06-16/rocm-smi-lib/4.2.0-gcc-10.3.0-jkdzf74a/bin
$ ls -la
total 132
drwxrwsr-x 2 hpcoft30 hpc43203   4096 Jun 22 02:09 .
drwxrwsr-x 8 hpcoft30 hpc43203   4096 Jun 22 02:09 ..
lrwxrwxrwx 1 hpcoft30 hpc43203     11 Jun 22 02:09 rocm-smi -> rocm_smi.py
-rwxrwxr-x 1 hpcoft30 hpc43203 122715 Feb 24 18:02 rocm_smi.py
lrwxrwxrwx 1 hpcoft30 hpc43203     36 Jun 22 02:09 rsmiBindings.py -> ../rocm_smi/bindings/rsmiBindings.py
```
but `../rocm_smi/` does not exist. The symlink should point to `../bindings/rsmiBindings.py`.

### Information on your system
```
$ spack debug report
* **Spack:** 0.16.2-3246-d3a1da8
* **Python:** 3.6.8
* **Platform:** linux-centos7-zen2
* **Concretizer:** original
```

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
Can you maybe bump this issue while you're at it? https://github.com/RadeonOpenCompute/rocm_smi_lib/issues/84 not sure it gets noticed, but well...

**Comment by srekolam** [comment]
Seems like a issue even with rocm-4.1.0

**Comment by srekolam** [comment]
i think commenting the L46 in the rocm-smi-lib recipe should fix this issue.

**Comment by UweSauter** [comment]
I commented the last line of `rocm-smi-lib/package.py` and it does not solve the problem. The symlink still points to a non-existing directory:
`rsmiBindings.py -> ../rocm_smi/bindings/rsmiBindings.py`

```
$ cd /opt/hlrs/spack/2021-06-16/rocm-smi-lib/4.2.0-gcc-10.3.0-jkdzf74a
$ tree
.
├── bin
│   ├── rocm-smi -> rocm_smi.py
│   ├── rocm_smi.py
│   └── rsmiBindings.py -> ../rocm_smi/bindings/rsmiBindings.py
├── bindings
│   └── rsmiBindings.py
├── include
│   └── rocm_smi
│       ├── kfd_ioctl.h
│       └── rocm_smi.h
├── lib
│   ├── librocm_smi64.so -> librocm_smi64.so.1
│   ├── librocm_smi64.so.1 -> librocm_smi64.so.1.0
│   └── librocm_smi64.so.1.0
└── oam
    ├── include
    │   └── oam
    │       ├── amd_oam.h
    │       └── oam_mapi.h
    └── lib
        ├── liboam.so -> liboam.so.1
        ├── liboam.so.1 -> liboam.so.1.0
        └── liboam.so.1.0

9 directories, 14 files
```

**Comment by srekolam** [comment]
hmm..this is what i see after i comment the  line  : shutil.rmtree(self.prefix.rocm_smi) 

/tmp/spack/opt/spack/linux-sles15-skylake_avx512/gcc-7.5.0/rocm-smi-lib-4.2.0-a3g33mv3q4gygznryo3ah2c3m3gkhuou # tree
.
|-- bin
|   |-- rocm-smi -> rocm_smi.py
|   |-- rocm_smi.py
|   `-- rsmiBindings.py -> ../rocm_smi/bindings/rsmiBindings.py
|-- bindings
|   `-- rsmiBindings.py
|-- include
|   `-- rocm_smi
|       |-- kfd_ioctl.h
|       `-- rocm_smi.h
|-- lib
|   |-- librocm_smi64.so -> librocm_smi64.so.1
|   |-- librocm_smi64.so.1 -> librocm_smi64.so.1.0
|   `-- librocm_smi64.so.1.0
|-- oam
|   |-- include
|   |   `-- oam
|   |       |-- amd_oam.h
|   |       `-- oam_mapi.h
|   `-- lib
|       |-- liboam.so -> liboam.so.1
|       |-- liboam.so.1 -> liboam.so.1.0
|       `-- liboam.so.1.0
`-- rocm_smi
    |-- bindings
    |   `-- rsmiBindings.py
    |-- include
    |   `-- rocm_smi
    |       |-- kfd_ioctl.h
    |       `-- rocm_smi.h
    `-- lib
        |-- librocm_smi64.so -> librocm_smi64.so.1
        |-- librocm_smi64.so.1 -> librocm_smi64.so.1.0
        `-- librocm_smi64.so.1.0

14 directories, 20 files

**Comment by UweSauter** [comment]
Would you mind putting that in code tags? It's hard to get the structure when the formatting is off…

**Comment by srekolam** [comment]
```ixt-rack-104:/tmp/spack/opt/spack/linux-sles15-skylake_avx512/gcc-7.5.0/rocm-smi-lib-4.2.0-a3g33mv3q4gygznryo3ah2c3m3gkhuou # tree
.
|-- bin
|   |-- rocm-smi -> rocm_smi.py
|   |-- rocm_smi.py
|   `-- rsmiBindings.py -> ../rocm_smi/bindings/rsmiBindings.py
|-- bindings
|   `-- rsmiBindings.py
|-- include
|   `-- rocm_smi
|       |-- kfd_ioctl.h
|       `-- rocm_smi.h
|-- lib
|   |-- librocm_smi64.so -> librocm_smi64.so.1
|   |-- librocm_smi64.so.1 -> librocm_smi64.so.1.0
|   `-- librocm_smi64.so.1.0
|-- oam
|   |-- include
|   |   `-- oam
|   |       |-- amd_oam.h
|   |       `-- oam_mapi.h
|   `-- lib
|       |-- liboam.so -> liboam.so.1
|       |-- liboam.so.1 -> liboam.so.1.0
|       `-- liboam.so.1.0
`-- rocm_smi
    |-- bindings
    |   `-- rsmiBindings.py
    |-- include
    |   `-- rocm_smi
    |       |-- kfd_ioctl.h
    |       `-- rocm_smi.h
    `-- lib
        |-- librocm_smi64.so -> librocm_smi64.so.1
        |-- librocm_smi64.so.1 -> librocm_smi64.so.1.0
        `-- librocm_smi64.so.1.0

14 directories, 20 files
`

**Comment by UweSauter** [comment]
Ok, I see what commenting line 46 did.

This is not an acceptable solution as it just prevents a cleanup during installation, duplicating storage needs for the `rocm_smi` directory and everything in it.

The symlink needs to be directed to the correct path, either by the build process or by some cleanup process if it cannot be done during build. Perhaps the fix really is in RadeonOpenCompute/rocm_smi_lib#84.

**Comment by srekolam** [comment]
how about adding the below at the end as part of post_install-
os.remove(join_path(self.prefix.bin,'rsmiBindings.py'))
        symlink( '../bindings/rsmiBindings.py',
                join_path(self.prefix.bin,'rsmiBindings.py'))

you need import os at the beginning. This will correct the symlink to point to right file

**Comment by UweSauter** [comment]
I reinstalled and now can run `rocm-smi` without getting Python import errors. The symlink now points to the correct file.

**Comment by srekolam** [comment]
the fix #24603 is merged into spack develop branch

**Comment by UweSauter** [comment]
#24603 was not yet merged. The build pipeline failed at one step.

**Comment by srekolam** [comment]
i see this merged today..can we close this issue ?
