### ISSUE TITLE
Binary relocation doesn't relocate paths needed for Spack smoke tests

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#29186]
### Steps to reproduce

Binary relocation of some packages with spack smoke tests does not relocate strings needed for the tests.

For example, `superlu-dist` built in a long path, cached, and then installed to a short path:

```
$> grep -Inr placeholder $(spack location -i superlu-dist)/.spack/test
...
/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/superlu-dist-7.2.0-mml2dkzs2j4wmfjw3hgqwxtgsg7pcooc/.spack/test/make.inc:63:CXX          = /spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.2-b2hsqqqnsiodzp3kw63u425osorilfty/bin/mpic++
/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/superlu-dist-7.2.0-mml2dkzs2j4wmfjw3hgqwxtgsg7pcooc/.spack/test/make.inc:72:LOADER       = /spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.4.2-b2hsqqqnsiodzp3kw63u425osorilfty/bin/mpic++
```

As a result:
```
$> spack test run superlu-dist
...
==> Spack test vsvxgi2wnywtn4zo2n7dlufn7motg6l7
==> Testing package superlu-dist-7.2.0-mml2dkz
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'pddrive'

1 error found in test log:
     4     ==> [2022-02-24-07:47:58.575778] FILTER FILE: /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/superlu-dist-7.2.0-mml2dkzs2j4wmfjw3hgqwxtg
           sg7pcooc/.spack/test/make.inc [replacing "^LIBS.+\+=.+"]
     5     ==> [2022-02-24-07:47:58.719216] FILTER FILE: /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/superlu-dist-7.2.0-mml2dkzs2j4wmfjw3hgqwxtg
           sg7pcooc/.spack/test/make.inc [replacing "^LIBS[^\+]+=.+"]
     6     ==> [2022-02-24-07:47:58.722301] FILTER FILE: /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/superlu-dist-7.2.0-mml2dkzs2j4wmfjw3hgqwxtg
           sg7pcooc/.spack/test/make.inc [replacing "^LOADOPTS.+"]
     7     ==> [2022-02-24-07:47:58.723600] 'make' '-j16' 'pddrive'
     8     /spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_pla
           ceholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-x86_64/
           gcc-9.3.0/mpich-3.4.2-b2hsqqqnsiodzp3kw63u425osorilfty/bin/mpicc -O3 -DNDEBUG -I/spack/opt/spack/__spack_path_placeholder__/__spack_path_plac
           eholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde
           r__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-x86_64/gcc-9.3.0/metis-5.1.0-vds2a7ehbmqig5t4e5albl6ivgtl4mvm/includ
           e -I/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path
           _placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-x86
           _64/gcc-9.3.0/parmetis-4.0.3-545mtgbbbzffl3mdpx67jubb5r7cgzjg/include -DUSE_VENDOR_BLAS  -std=c99 -fPIC   -I/spack/opt/spack/__spack_path_pla
           ceholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placehold
           er__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-x86_64/gcc-9.3.0/superlu-dist-7.2.0-mml2
           dkzs2j4wmfjw3hgqwxtgsg7pcooc/include -c pddrive.c
     9     make: /spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_pa
           th_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-x
           86_64/gcc-9.3.0/mpich-3.4.2-b2hsqqqnsiodzp3kw63u425osorilfty/bin/mpicc: Command not found
  >> 10    make: *** [Makefile:170: pddrive.o] Error 127

See test log for details:
  /root/.spack/test/vsvxgi2wnywtn4zo2n7dlufn7motg6l7/superlu-dist-7.2.0-mml2dkz-test-out.txt
```

@wspear @tldahlgren @balay @pghysels @liuyangzhua

### Information on your system

* **Spack:** 0.17.1
* **Python:** 3.9.5
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by liuyangzhuan** [comment]
@liuyangzhuan

**Comment by liuyangzhuan** [comment]
@liuyangzhuan  keeping an eye on this.

**Comment by tldahlgren** [comment]
This was discussed in a meeting earlier.  I would have to test but there could be a couple of issues here that *may* have been resolved.  For example, I think the package needs to use the right variables for built dependency compilers but I'll need review and check to be certain.  

Last I counted there are still 49 packages using the old API that may not be using "best practices" to build their tests.

Also, the `superlu-dist` package's stand-alone tests in particular have been updated to use pre-installed examples so that might not be the best example of this problem anymore.

@eugeneswalker @wspear Can we get an update on this to see if it is still a problem?

**Comment by wspear** [comment]
We are still seeing relocation-related faults in relatively recent versions of Spack (0.21.0.dev0 / tag e4s 23.11) with, e.g. Tasmanian:

```
Skipping load: Environment already setup
==> Error: TestFailure: 1 test failed.


Command exited with status 1:
    '/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/cmake-3.27.7-pzdblzeh7ptbjgoj73g3csq5jzuaxqhk/bin/cmake' '/pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/stbyq3fkftckcvy6eutrrpi6it5epxvj/tasmanian-8.0-tse33pu/cache/tasmanian/testing' '-DMPI_HOME=/opt/cray/pe/mpich/default/ofi/gnu/9.1'


1 error found in test log:
     15      add_subdirectory given source
     16      "/dev/shm/gnu/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_p
           at/linux-sles15-zen3/gcc-11.2.0/tasmanian-8.0-tse33pung6hxg5mdnanr62yi5ytmyou7/share/Tasmanian/examples"
     17      which is not an existing directory.
     18
     19
     20    -- Configuring incomplete, errors occurred!
  >> 21    FAILED: Tasmanian::test_make_test: Command exited with status 1:
     22        '/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/cmake-3.27.7-pzdblzeh7ptbjgoj73g3csq5jzuaxqhk/bin/cmake' '/pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/stbyq3fkftckcvy6eutrrpi6it5epxvj
           /tasmanian-8.0-tse33pu/cache/tasmanian/testing' '-DMPI_HOME=/opt/cray/pe/mpich/default/ofi/gnu/9.1'
     23      File "/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/bin/spack", line 52, in <module>
     24        sys.exit(main())
     25      File "/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/lib/spack/spack_installable/main.py", line 37, in main
     26        sys.exit(spack.main.main(argv))
     27      File "/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/lib/spack/spack/main.py", line 1022, in main


See test log for details:
  /pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/stbyq3fkftckcvy6eutrrpi6it5epxvj/tasmanian-8.0-tse33pu-test-out.txt

==> Error: 1 test(s) in the suite failed.
```

Sundials:

```
Skipping load: Environment already setup
Skipping load: Environment already setup
==> Error: TestFailure: 1 test failed.


Failed to find executable '/dev/shm/gnu/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_pat/linux-sles15-zen3/gcc-11.2.0/cmake-3.27.7-pzdblzeh7ptbjgoj73g3csq5jzuaxqhk/bin/cmake'



See test log for details:
  /pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/ky6qtoxgqmlvxzjshjebbms576glsvya/sundials-6.6.1-qxugk5t-test-out.txt

==> Error: 1 test(s) in the suite failed.

--- ==> Spack test ky6qtoxgqmlvxzjshjebbms576glsvya
==> Testing package sundials-6.6.1-qxugk5t
============================== 1 failed of 1 spec ==============================

See sundials-6.6.1-qxugk5t test results at:
  /pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/ky6qtoxgqmlvxzjshjebbms576glsvya/sundials-6.6.1-qxugk5t-test-out.txt ---

```

**Comment by tldahlgren** [comment]
> We are still seeing relocation-related faults in relatively recent versions of Spack (0.21.0.dev0 / tag e4s 23.11) with, e.g. Tasmanian:
> 
> ```
> Skipping load: Environment already setup
> ==> Error: TestFailure: 1 test failed.
> 
> 
> Command exited with status 1:
>     '/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/cmake-3.27.7-pzdblzeh7ptbjgoj73g3csq5jzuaxqhk/bin/cmake' '/pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/stbyq3fkftckcvy6eutrrpi6it5epxvj/tasmanian-8.0-tse33pu/cache/tasmanian/testing' '-DMPI_HOME=/opt/cray/pe/mpich/default/ofi/gnu/9.1'
> 
> 
> 1 error found in test log:
>      15      add_subdirectory given source
>      16      "/dev/shm/gnu/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_p
>            at/linux-sles15-zen3/gcc-11.2.0/tasmanian-8.0-tse33pung6hxg5mdnanr62yi5ytmyou7/share/Tasmanian/examples"
>      17      which is not an existing directory.
>      18
>      19
>      20    -- Configuring incomplete, errors occurred!
>   >> 21    FAILED: Tasmanian::test_make_test: Command exited with status 1:
>      22        '/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/cmake-3.27.7-pzdblzeh7ptbjgoj73g3csq5jzuaxqhk/bin/cmake' '/pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/stbyq3fkftckcvy6eutrrpi6it5epxvj
>            /tasmanian-8.0-tse33pu/cache/tasmanian/testing' '-DMPI_HOME=/opt/cray/pe/mpich/default/ofi/gnu/9.1'
>      23      File "/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/bin/spack", line 52, in <module>
>      24        sys.exit(main())
>      25      File "/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/lib/spack/spack_installable/main.py", line 37, in main
>      26        sys.exit(spack.main.main(argv))
>      27      File "/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/lib/spack/spack/main.py", line 1022, in main
> 
> 
> See test log for details:
>   /pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/stbyq3fkftckcvy6eutrrpi6it5epxvj/tasmanian-8.0-tse33pu-test-out.txt
> 
> ==> Error: 1 test(s) in the suite failed.
> ```
> 
> Sundials:
> 
> ```
> Skipping load: Environment already setup
> Skipping load: Environment already setup
> ==> Error: TestFailure: 1 test failed.
> 
> 
> Failed to find executable '/dev/shm/gnu/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_pat/linux-sles15-zen3/gcc-11.2.0/cmake-3.27.7-pzdblzeh7ptbjgoj73g3csq5jzuaxqhk/bin/cmake'
> 
> 
> 
> See test log for details:
>   /pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/ky6qtoxgqmlvxzjshjebbms576glsvya/sundials-6.6.1-qxugk5t-test-out.txt
> 
> ==> Error: 1 test(s) in the suite failed.
> 
> --- ==> Spack test ky6qtoxgqmlvxzjshjebbms576glsvya
> ==> Testing package sundials-6.6.1-qxugk5t
> ============================== 1 failed of 1 spec ==============================
> 
> See sundials-6.6.1-qxugk5t test results at:
>   /pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/ky6qtoxgqmlvxzjshjebbms576glsvya/sundials-6.6.1-qxugk5t-test-out.txt ---
> ```

Thanks.  

That does not look like the right path to the `tasmanian` examples subdirectory for the tests.  It looks like there may be some missing filters related to cmake files that may need to be adjusted.

The `sundials` package has not been converted to the new API so is using the old `cmake` hack, API, etc.  I started some of the conversion process in https://github.com/spack/spack/pull/35807 before the latest API work was completed.

**Comment by wspear** [comment]
Also observed on heffte: 
```
Skipping load: Environment already setup
==> Error: TestFailure: 1 test failed.


Command exited with status 1:
    '/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/cmake-3.27.7-pzdblzeh7ptbjgoj73g3csq5jzuaxqhk/bin/cmake' '/pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/qiujwgww23zs3aq4qygdyd2cccc7xqle/heffte-2.4.0-yzp5xac/cache/heffte/testing' '-DHeffte_DIR:STRING=/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/heffte-2.4.0-yzp5xac6y73jcnogcgpestr4t6arhmb3/lib/cmake/Heffte' '-DMPI_HOME:STRING=/opt/cray/pe/mpich/default/ofi/gnu/9.1'


1 error found in test log:
     17      add_subdirectory given source
     18      "/dev/shm/gnu/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_p
           at/linux-sles15-zen3/gcc-11.2.0/heffte-2.4.0-yzp5xac6y73jcnogcgpestr4t6arhmb3/share/heffte/examples"
     19      which is not an existing directory.
     20
     21
     22    -- Configuring incomplete, errors occurred!
  >> 23    FAILED: Heffte::test_make_test: Command exited with status 1:
     24        '/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/cmake-3.27.7-pzdblzeh7ptbjgoj73g3csq5jzuaxqhk/bin/cmake' '/pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/qiujwgww23zs3aq4qygdyd2cccc7xqle
           /heffte-2.4.0-yzp5xac/cache/heffte/testing' '-DHeffte_DIR:STRING=/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/heffte-2.4.0-yzp5xac6y73jcnogcgpestr4t6arhmb3/lib/cmake/Heffte' '-DMPI_HOME:STRING=/o
           pt/cray/pe/mpich/default/ofi/gnu/9.1'
     25      File "/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/bin/spack", line 52, in <module>
     26        sys.exit(main())
     27      File "/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/lib/spack/spack_installable/main.py", line 37, in main
     28        sys.exit(spack.main.main(argv))
     29      File "/global/cfs/cdirs/m3896/shared/ParaTools/E4S/23.11/PrgEnv-gnu/spack/lib/spack/spack/main.py", line 1022, in main


See test log for details:
  /pscratch/sd/w/wspear/perlmutter/spack_user_cache/test/qiujwgww23zs3aq4qygdyd2cccc7xqle/heffte-2.4.0-yzp5xac-test-out.txt

==> Error: 1 test(s) in the suite failed.

~                                                                                                                                                                                                                             
~                                                    
```

**Comment by tldahlgren** [comment]
That package also explicitly copies files instead of using the helper (https://spack.readthedocs.io/en/latest/packaging_guide.html#saving-build-time-files) and the path definitely doesn't look right.

**Comment by tldahlgren** [comment]
I can't reproduce the `heffte` or `tasmanian` failures with local spack instance installations.

**Comment by wspear** [comment]
Were they installed from a binary repository? That's the only case when this will occur as far as I am aware.

**Comment by tldahlgren** [comment]
> Were they installed from a binary repository? That's the only case when this will occur as far as I am aware.

No, both from source.  I missed that about them being installed from a binary repository.

**Comment by wspear** [comment]
The bogus paths you see in the error output posted here come from the placeholder strings used when packages are built for the binary repo. The (or at least a) issue is that these tests are getting paths from the .spack directory which has files that never get their strings updated to the actual install location.

**Comment by tldahlgren** [comment]
From what I can see in `$HEFFTE_PREFIX/.spack/test/testing/CMakeLists.txt` and `$TASMANIAN_PREFIX/.spack/test/testing/CMakeLists.txt` for my local installs, it looks like running `filter_file` (https://spack.readthedocs.io/en/latest/packaging_guide.html#filtering-functions) on `add_subdirectory` to replace the examples path to one that doesn't have the placeholders might be in order.

**Comment by wspear** [comment]
@tldahlgren Is there any news on a possible fix? Currently we don't have working tests for at least heffte, tasmanian, sundials and superlu-dist because of this issue. I'll need to re-implement the tests outside of spack if binary installs can't use the internal tests.

**Comment by wspear** [comment]
Presumably the fix will be similar to this, just targeted at some subset of files in the .spack or .spack/tests directory. Logs, for example, shouldn't need to be filtered.  https://github.com/spack/spack/pull/36611

**Comment by tldahlgren** [comment]
@wspear Is this still an issue?  I was able to install two of the four packages (`superlu-dist`, `heffte`) from the `develop` build cache on rhel8 and am not seeing any placeholders.  (I have uninstalled dependencies for the other two ATM.)

**Comment by tgamblin** [comment]
Closing this for now, as @tldahlgren could not reproduce it. If you see this again please reopen.
