### ISSUE TITLE
intel-mpi-benchmarks is outdated and incomplete

### ISSUE THREAD

**Issue by m4r1k** [LLNL/spack#32534]
### Summary

Currently, the available version of intel-mpi-benchmarks range from 2019.2 till 2019.6.
https://github.com/spack/spack/blob/v0.18.1/var/spack/repos/builtin/packages/intel-mpi-benchmarks/package.py#L22-L26

Intel has released much newer versions (latest being the 2021.3)
https://github.com/intel/mpi-benchmarks

Could you update the package.py including not only the latest versions but also all the former ones?

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
@carsonwoods is the maintainer of this build recipe

**Comment by carsonwoods** [comment]
@adamjstewart @m4r1k Please see #32535 and let me know if this resolves the issue.

**Comment by m4r1k** [comment]
Hey @carsonwoods 

First, thanks a lot for your super fast patch. Much appreciated. 
I can confirm the patch you submitted successfully builds all MPI Benchmark versions from 2019.2 onwards while the 2018 to 2019.1 fails on the patches.

```
$ module avail
----------------------------------------------------------- /sw/spack/share/spack/modules/linux-centos7-x86_64_v3 -----------------------------------------------------------
   intel-mpi-benchmarks/2019.2-gcc-12.1.0    intel-mpi-benchmarks/2021.2-gcc-12.1.0        intel-mpi/2018.4.274-gcc-12.1.0      (L)
   intel-mpi-benchmarks/2021.1-gcc-12.1.0    intel-mpi-benchmarks/2021.3-gcc-12.1.0 (D)    intel-oneapi-mpi/2021.6.0-gcc-12.1.0
```

The following for 2018.1 (same error also on 2018.0)
```
$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2018.1%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2018.1-4wulaynvi2e65o6cman5r3m4q6mmstnc
==> No binary for intel-mpi-benchmarks-2018.1-4wulaynvi2e65o6cman5r3m4q6mmstnc found: installing from source
==> Fetching https://github.com/intel/mpi-benchmarks/archive/refs/tags/v2018.1.tar.gz
The text leading up to this was:
--------------------------
|diff --git a/src_cpp/args_parser.h b/src_cpp/args_parser.h
|index 0a6c748..cfd6a89 100644
|--- a/src_cpp/args_parser.h
|+++ b/src_cpp/args_parser.h
--------------------------
File to patch:
Skip this patch? [y]
1 out of 1 hunk ignored
==> Patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/add_const.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/bin/patch' '-s' '-p' '1' '-i' '/sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/add_const.patch' '-d' '.'
```

The following for 2019.0
```
sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2019.0%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2019.0-7gxkmvfnld55ce335frdgph5dm6iyr3a
==> No binary for intel-mpi-benchmarks-2019.0-7gxkmvfnld55ce335frdgph5dm6iyr3a found: installing from source
==> Fetching https://github.com/intel/mpi-benchmarks/archive/refs/tags/v2019.0.tar.gz
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/add_const.patch
1 out of 1 hunk FAILED -- saving rejects to file src_cpp/MT/MT_benchmark.cpp.rej
==> Patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/reorder_benchmark_macros.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/bin/patch' '-s' '-p' '1' '-i' '/sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/reorder_benchmark_macros.patch' '-d' '.'
```

The following for 2019.1
```
$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2019.1%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2019.1-xcsid3us4kgzu7ujshzdqsmdti4icek5
==> No binary for intel-mpi-benchmarks-2019.1-xcsid3us4kgzu7ujshzdqsmdti4icek5 found: installing from source
==> Fetching https://github.com/intel/mpi-benchmarks/archive/refs/tags/v2019.1.tar.gz
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/add_const.patch
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/reorder_benchmark_macros.patch
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> intel-mpi-benchmarks: Executing phase: 'install'
==> Error: OSError: No such file or directory: 'IMB-P2P'

/sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/package.py:113, in install:
        110            install("IMB-MPI1", prefix.bin)
        111            install("IMB-MT", prefix.bin)
        112            install("IMB-NBC", prefix.bin)
  >>    113            install("IMB-P2P", prefix.bin)
        114            install("IMB-RMA", prefix.bin)

See build log for details:
  /sw/spack/spack-stage/root/spack-stage-intel-mpi-benchmarks-2019.1-xcsid3us4kgzu7ujshzdqsmdti4icek5/spack-build-out.txt
```

To be on the safe side, I also ran a PingPong loading `intel-mpi-benchmarks/2021.3` and correctly works.
```
[0] MPI startup(): Intel(R) MPI Library, Version 2021.6  Build 20220227 (id: 28877f3f32)
[0] MPI startup(): Copyright (C) 2003-2022 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
[0] MPI startup(): libfabric version: 1.13.2rc1-impi
[0] MPI startup(): libfabric provider: tcp;ofi_rxm
[0] MPI startup(): Load tuning file: "/sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m/mpi/2021.6.0/etc/tuning_skx_ofi_tcp-ofi-rxm.dat"
[0] MPI startup(): Rank    Pid      Node name                       Pin cpu
[0] MPI startup(): 0       3041     slurm-internal-hpc-compute-1-2  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29}
[0] MPI startup(): 1       3017     slurm-internal-hpc-compute-1-3  {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29}
[0] MPI startup(): I_MPI_ROOT=/sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m/mpi/2021.6.0
[0] MPI startup(): I_MPI_MPIRUN=mpirun
[0] MPI startup(): I_MPI_HYDRA_TOPOLIB=hwloc
[0] MPI startup(): I_MPI_HYDRA_BOOTSTRAP=slurm
[0] MPI startup(): I_MPI_INTERNAL_MEM_POLICY=default
[0] MPI startup(): I_MPI_FABRICS=ofi
[0] MPI startup(): I_MPI_DEBUG=5
#----------------------------------------------------------------
#    Intel(R) MPI Benchmarks 2021.4, MPI-1 part
#----------------------------------------------------------------
# Date                  : Tue Sep  6 22:11:59 2022
# Machine               : x86_64
# System                : Linux
# Release               : 3.10.0-1160.62.1.el7.x86_64
# Version               : #1 SMP Tue Apr 5 16:57:59 UTC 2022
# MPI Version           : 3.1
# MPI Thread Environment:


# Calling sequence was:

# IMB-MPI1 PingPong -iter 100000

# Minimum message length in bytes:   0
# Maximum message length in bytes:   4194304
#
# MPI_Datatype                   :   MPI_BYTE
# MPI_Datatype for reductions    :   MPI_FLOAT
# MPI_Op                         :   MPI_SUM
#
#

# List of Benchmarks to run:

# PingPong

#---------------------------------------------------
# Benchmarking PingPong
# #processes = 2
#---------------------------------------------------
       #bytes #repetitions      t[usec]   Mbytes/sec
            0       100000        10.02         0.00
            1       100000        10.00         0.10
            2       100000        10.06         0.20
            4       100000         9.97         0.40
            8       100000        10.15         0.79
           16       100000        10.02         1.60
           32       100000        10.08         3.17
           64       100000        10.06         6.36
          128       100000        10.24        12.50
          256       100000        11.45        22.36
          512        81920        11.74        43.62
         1024        40960        12.22        83.78
         2048        20480        13.47       152.05
         4096        10240        15.49       264.44
         8192         5120        19.39       422.41
        16384         2560        23.93       684.69
        32768         1280        32.87       996.91
        65536          640        44.85      1461.36
       131072          320        62.49      2097.59
       262144          160       146.98      1783.53
       524288           80       207.90      2521.84
      1048576           40       335.52      3125.20
      2097152           20       606.47      3457.98
      4194304           10      1263.92      3318.48
```

I guess, the two patches needs to be excluded for anything older than 2019.2. WDYT?

**Comment by carsonwoods** [comment]
Yep, I think thats correct. I'll get those changes made on my end today so that they build correctly. Hopefully this should be done by today so the patch can be merged in. 

Thanks for letting me know about the incorrect patch!

**Comment by carsonwoods** [comment]
@m4r1k I've fixed the patch bugs and the issue with 2019.1. Can you re-test and see if you're running into any more build issues? Thanks!

**Comment by m4r1k** [comment]
Hey @carsonwoods 

Thanks for the update and apologies for my late reply.

2019.0 through 2021.3 compile and works like a charm but both 2018s still fails.

```
$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2018.0%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2018.0-hbgvdw37dx56zeafs6dum5tp5voeua6r
==> No binary for intel-mpi-benchmarks-2018.0-hbgvdw37dx56zeafs6dum5tp5voeua6r found: installing from source
==> Using cached archive: /sw/spack/var/spack/cache/_source-cache/archive/2e/2e60a9894a686a95791be2227bc569bf81ca3875421b5307df7d83f885b1de88.tar.gz
==> No patches needed for intel-mpi-benchmarks
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j2' 'all'

1 error found in build log:
     4    ==> [2022-09-09-15:32:04.638100] 'make' '-j2' 'all'
  >> 5    make: *** No rule to make target `all'.  Stop.

See build log for details:
  /sw/spack/spack-stage/root/spack-stage-intel-mpi-benchmarks-2018.0-hbgvdw37dx56zeafs6dum5tp5voeua6r/spack-build-out.txt

$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2018.1%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2018.1-xkvy4b7hlyexck2i3e2aljlo3yqm6sv3
==> No binary for intel-mpi-benchmarks-2018.1-xkvy4b7hlyexck2i3e2aljlo3yqm6sv3 found: installing from source
==> Using cached archive: /sw/spack/var/spack/cache/_source-cache/archive/71/718a4eb155f18cf15a736f6496332407b5837cf1f19831723d4cfe5266c43507.tar.gz
==> No patches needed for intel-mpi-benchmarks
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j2' 'all'

1 error found in build log:
     4    ==> [2022-09-09-15:32:58.201183] 'make' '-j2' 'all'
  >> 5    make: *** No rule to make target `all'.  Stop.

See build log for details:
  /sw/spack/spack-stage/root/spack-stage-intel-mpi-benchmarks-2018.1-xkvy4b7hlyexck2i3e2aljlo3yqm6sv3/spack-build-out.txt

$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2019.0%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2019.0-dpd677befcmd2vahkrmuyeyyp4ahrukh
==> No binary for intel-mpi-benchmarks-2019.0-dpd677befcmd2vahkrmuyeyyp4ahrukh found: installing from source
==> Using cached archive: /sw/spack/var/spack/cache/_source-cache/archive/1c/1c7d44aa7fd86ca84ac7cae1a69a8426243048d6294582337f1de7b4ffe68d37.tar.gz
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/add_const.patch
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> intel-mpi-benchmarks: Executing phase: 'install'
==> intel-mpi-benchmarks: Successfully installed intel-mpi-benchmarks-2019.0-dpd677befcmd2vahkrmuyeyyp4ahrukh
  Fetch: 0.01s.  Build: 22.93s.  Total: 22.94s.
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-mpi-benchmarks-2019.0-dpd677befcmd2vahkrmuyeyyp4ahrukh

$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2019.1%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2019.1-f2aywrhngg746mgssy2ch6k5hlpftbx4
==> No binary for intel-mpi-benchmarks-2019.1-f2aywrhngg746mgssy2ch6k5hlpftbx4 found: installing from source
==> Using cached archive: /sw/spack/var/spack/cache/_source-cache/archive/fe/fe0d065b9936b6943ea83cb3d00aede43b17565285c6b1791fee8e340853ef79.tar.gz
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/add_const.patch
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/reorder_benchmark_macros.patch
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> intel-mpi-benchmarks: Executing phase: 'install'
==> intel-mpi-benchmarks: Successfully installed intel-mpi-benchmarks-2019.1-f2aywrhngg746mgssy2ch6k5hlpftbx4
  Fetch: 0.01s.  Build: 23.17s.  Total: 23.18s.
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-mpi-benchmarks-2019.1-f2aywrhngg746mgssy2ch6k5hlpftbx4

$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2019.2%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2019.2-3xkkvw6ppywhyzvkpfgm25vohcqlaqfq
==> No binary for intel-mpi-benchmarks-2019.2-3xkkvw6ppywhyzvkpfgm25vohcqlaqfq found: installing from source
==> Using cached archive: /sw/spack/var/spack/cache/_source-cache/archive/0b/0bc2224a913073aaa5958f6ae08341e5fcd39cedc6722a09bfd4a3d7591a340b.tar.gz
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/add_const.patch
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/reorder_benchmark_macros.patch
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> intel-mpi-benchmarks: Executing phase: 'install'
==> intel-mpi-benchmarks: Successfully installed intel-mpi-benchmarks-2019.2-3xkkvw6ppywhyzvkpfgm25vohcqlaqfq
  Fetch: 0.01s.  Build: 24.72s.  Total: 24.72s.
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-mpi-benchmarks-2019.2-3xkkvw6ppywhyzvkpfgm25vohcqlaqfq

$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2019.3%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2019.3-u6hn66nacpby4aaeonqocr25qm763o3x
==> No binary for intel-mpi-benchmarks-2019.3-u6hn66nacpby4aaeonqocr25qm763o3x found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/4f/4f256d11bfed9ca6166548486d61a062e67be61f13dd9f30690232720e185f31.tar.gz
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/add_const.patch
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/reorder_benchmark_macros.patch
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> intel-mpi-benchmarks: Executing phase: 'install'
==> intel-mpi-benchmarks: Successfully installed intel-mpi-benchmarks-2019.3-u6hn66nacpby4aaeonqocr25qm763o3x
  Fetch: 0.14s.  Build: 24.66s.  Total: 24.80s.
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-mpi-benchmarks-2019.3-u6hn66nacpby4aaeonqocr25qm763o3x

$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2019.4%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2019.4-smvrfkklfxyfpi6afkpwzwtwh25sudcm
==> No binary for intel-mpi-benchmarks-2019.4-smvrfkklfxyfpi6afkpwzwtwh25sudcm found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/ae/aeb336be10275c1a2f579b491b6631122876b461ac7148b1d0764f13b7552690.tar.gz
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/add_const.patch
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/reorder_benchmark_macros.patch
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> intel-mpi-benchmarks: Executing phase: 'install'
==> intel-mpi-benchmarks: Successfully installed intel-mpi-benchmarks-2019.4-smvrfkklfxyfpi6afkpwzwtwh25sudcm
  Fetch: 0.14s.  Build: 26.57s.  Total: 26.71s.
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-mpi-benchmarks-2019.4-smvrfkklfxyfpi6afkpwzwtwh25sudcm

$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2019.5%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2019.5-lfeuhgwts7t2v5exhxnfxhhhlxlr5wyo
==> No binary for intel-mpi-benchmarks-2019.5-lfeuhgwts7t2v5exhxnfxhhhlxlr5wyo found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/61/61f8e872a3c3076af53007a68e4da3a8d66be2ba7a051dc21e626a4e2d26e651.tar.gz
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/add_const.patch
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/reorder_benchmark_macros.patch
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> intel-mpi-benchmarks: Executing phase: 'install'
==> intel-mpi-benchmarks: Successfully installed intel-mpi-benchmarks-2019.5-lfeuhgwts7t2v5exhxnfxhhhlxlr5wyo
  Fetch: 0.14s.  Build: 26.67s.  Total: 26.81s.
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-mpi-benchmarks-2019.5-lfeuhgwts7t2v5exhxnfxhhhlxlr5wyo

$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2019.6%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2019.6-ppn7mqrnproortkl7gudnvq6u5vw4zv4
==> No binary for intel-mpi-benchmarks-2019.6-ppn7mqrnproortkl7gudnvq6u5vw4zv4 found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/1c/1cd0bab9e947228fced4666d907f77c51336291533919896a923cff5fcad62e9.tar.gz
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/add_const.patch
==> Applied patch /sw/spack/var/spack/repos/builtin/packages/intel-mpi-benchmarks/reorder_benchmark_macros.patch
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> intel-mpi-benchmarks: Executing phase: 'install'
==> intel-mpi-benchmarks: Successfully installed intel-mpi-benchmarks-2019.6-ppn7mqrnproortkl7gudnvq6u5vw4zv4
  Fetch: 0.11s.  Build: 27.06s.  Total: 27.17s.
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-mpi-benchmarks-2019.6-ppn7mqrnproortkl7gudnvq6u5vw4zv4

$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2021.1%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2021.1-lhayij4dl34hehsxeobst5rqbpan6ah6
==> No binary for intel-mpi-benchmarks-2021.1-lhayij4dl34hehsxeobst5rqbpan6ah6 found: installing from source
==> Using cached archive: /sw/spack/var/spack/cache/_source-cache/archive/90/9089bb81e3091af3481e03b898b339fb2d9fb6574d4ef059adb1f5410112b23a.tar.gz
==> No patches needed for intel-mpi-benchmarks
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> intel-mpi-benchmarks: Executing phase: 'install'
==> intel-mpi-benchmarks: Successfully installed intel-mpi-benchmarks-2021.1-lhayij4dl34hehsxeobst5rqbpan6ah6
  Fetch: 0.01s.  Build: 27.01s.  Total: 27.02s.
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-mpi-benchmarks-2021.1-lhayij4dl34hehsxeobst5rqbpan6ah6

$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2021.2%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2021.2-uqt5nk6xkf7rtnyasbh7zz2xpnyhn2zn
==> No binary for intel-mpi-benchmarks-2021.2-uqt5nk6xkf7rtnyasbh7zz2xpnyhn2zn found: installing from source
==> Using cached archive: /sw/spack/var/spack/cache/_source-cache/archive/ad/ade3bfe18b4313a31fc09f0bf038e0a6c169c4145089bfc6f1f827687b81be6a.tar.gz
==> No patches needed for intel-mpi-benchmarks
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> intel-mpi-benchmarks: Executing phase: 'install'
==> intel-mpi-benchmarks: Successfully installed intel-mpi-benchmarks-2021.2-uqt5nk6xkf7rtnyasbh7zz2xpnyhn2zn
  Fetch: 0.01s.  Build: 29.19s.  Total: 29.20s.
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-mpi-benchmarks-2021.2-uqt5nk6xkf7rtnyasbh7zz2xpnyhn2zn

$ sudo /sw/spack/bin/spack install intel-mpi-benchmarks@2021.3%gcc@12.1.0 target=x86_64_v3
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-oneapi-mpi-2021.6.0-apd35trsmkjes6ecost3yxm4afhnir2m
==> Installing intel-mpi-benchmarks-2021.3-bcmi6js3mu5gqfavqezss6s2wvq72dtj
==> No binary for intel-mpi-benchmarks-2021.3-bcmi6js3mu5gqfavqezss6s2wvq72dtj found: installing from source
==> Using cached archive: /sw/spack/var/spack/cache/_source-cache/archive/9b/9b58a4a7eef7c0c877513152340948402fd87cb06270d2d81308dc2ef740f4c7.tar.gz
==> No patches needed for intel-mpi-benchmarks
==> intel-mpi-benchmarks: Executing phase: 'edit'
==> intel-mpi-benchmarks: Executing phase: 'build'
==> intel-mpi-benchmarks: Executing phase: 'install'
==> intel-mpi-benchmarks: Successfully installed intel-mpi-benchmarks-2021.3-bcmi6js3mu5gqfavqezss6s2wvq72dtj
  Fetch: 0.01s.  Build: 29.04s.  Total: 29.05s.
[+] /sw/spack/opt/spack/linux-centos7-x86_64_v3/gcc-12.1.0/intel-mpi-benchmarks-2021.3-bcmi6js3mu5gqfavqezss6s2wvq72dtj
``` 

Could you fix these last two as well?

**Comment by m4r1k** [comment]
BTW, for the 2018s I think you need to reference to the GNUmakefile [1] under src. `all` is supported [2].

There are differences in the supported targets among versions but that's probably something people should be aware of [3] [4].

[1] https://github.com/intel/mpi-benchmarks/blob/v2018.0/src/GNUmakefile
[2] https://github.com/intel/mpi-benchmarks/blob/v2018.0/src/GNUmakefile#L3
[3] https://github.com/intel/mpi-benchmarks/blob/v2019.0/Makefile#L50
[4] https://github.com/intel/mpi-benchmarks/blob/IMB-v2021.3/Makefile#L50

**Comment by carsonwoods** [comment]
I'll work on getting 2018 and 2018.1 building. I've gone ahead and added in multiple provisions to prevent 2018 from building with the p2p benchmark. If someone tries it will fail to concretize and will provide an error explaining what went wrong.

**Comment by carsonwoods** [comment]
It also looks like there is a gmake requirement in there as well for older versions. I've added that as well to all 2018 versions. Additionally, it looks like Intel-MPI is required for older versions of the benchmark due to environment variables that only it sets.

**Comment by carsonwoods** [comment]
@m4r1k I think I've got everything working now. Let me know if you find any issues with installing the package after this latest round of changes.

**Comment by m4r1k** [comment]
All works like a charm for me now. Thanks a lot @carsonwoods !!
