### ISSUE TITLE
Incorrect dependency handling on spack load --dependencies

### ISSUE THREAD

**Issue by healther** [LLNL/spack#3501]
I wanted to take a shot at #3374 (now fixed by #3492) but I ran into dependency tracking issues when I wanted to use ```py-pudb```

```
$ spack load --dependencies py-pudb
$ pudb
Traceback (most recent call last):
  File "/Users/healther/Documents/git/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/py-pudb-2016.2-lqp42db6v3o3pzkzeyf4fgpc46mjtpsp/bin/pudb", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

spack, for some reason, decided that it should load ```py-setuptools```, ```py-six```, ```py-packaging```, ```py-pyparsing``` and ```py-appdirs``` even though it concretizes the spec as follows: 

```
Concretized
--------------------------------
[   ]  py-pudb@2016.2%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b r]      ^py-pygments@2.1.3%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b  ]          ^py-setuptools@34.2.0%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b r]              ^py-appdirs@1.4.0%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[bl ]                  ^python@2.7.13%clang@8.0.0-apple~tk~ucs4 arch=darwin-sierra-x86_64 
[bl ]                      ^bzip2@1.0.6%clang@8.0.0-apple+shared arch=darwin-sierra-x86_64 
[bl ]                      ^ncurses@6.0%clang@8.0.0-apple~symlinks arch=darwin-sierra-x86_64 
[b  ]                          ^gawk@4.1.4%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[bl ]                      ^openssl@1.0.2k%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b  ]                          ^perl@5.24.1%clang@8.0.0-apple+cpanm arch=darwin-sierra-x86_64 
[bl ]                          ^zlib@1.2.11%clang@8.0.0-apple+pic+shared arch=darwin-sierra-x86_64 
[bl ]                      ^readline@7.0%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[bl ]                      ^sqlite@3.8.5%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b r]              ^py-packaging@16.8%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[  r]                  ^py-pyparsing@2.1.10%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[  r]                  ^py-six@1.10.0%clang@8.0.0-apple arch=darwin-sierra-x86_64 
[b r]      ^py-urwid@1.3.0%clang@8.0.0-apple arch=darwin-sierra-x86_64
```

If I'm reading this correctly the missing packages should have been loaded according to the spec, but for some reason aren't. I haven't had time to track this down, but I think spack fails to load the dependencies of dependencies, even though it correctly concretises the spec.

I hope that I can give it a shot tomorrow or the day after.... If someone could give me a pointer where to start looking I'd appreciate it.

**Comment by adamjstewart** [comment]
This looks correct. `py-pudb` only has a build dependency on `py-setuptools`. When you load a package, you shouldn't load build dependencies. A build dependency means "this is needed to build the package, but you can delete it afterwards for all I care". The correct deptype for this one should be `type=('build', 'run')`. I'll submit a PR shortly.

**Comment by healther** [comment]
It actually (at least for me also has a run-time dependency. At least:
```
$ spack load --dependencies py-pudb
$ module list
Currently Loaded Modulefiles:
  1) bzip2-1.0.6-clang-8.0.0-apple-v2mr5fi         6) sqlite-3.8.5-clang-8.0.0-apple-qhml3gk
  2) ncurses-6.0-clang-8.0.0-apple-yz5pwlp         7) python-2.7.13-clang-8.0.0-apple-4bnzmjs
  3) zlib-1.2.11-clang-8.0.0-apple-ahv5tlv         8) py-pygments-2.1.3-clang-8.0.0-apple-cllzy4u
  4) openssl-1.0.2k-clang-8.0.0-apple-uu5hex7      9) py-urwid-1.3.0-clang-8.0.0-apple-zmdraae
  5) readline-7.0-clang-8.0.0-apple-fuphoes       10) py-pudb-2016.2-clang-8.0.0-apple-lqp42db
```
(missing the 5 packages mentioned above)
```
$ spack load py-six
$ spack load py-packaging
$ spack load py-pyparsing
$ spack load py-appdirs
$ pudb
Traceback (most recent call last):
  File "/Users/healther/Documents/git/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/py-pudb-2016.2-lqp42db6v3o3pzkzeyf4fgpc46mjtpsp/bin/pudb", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
$ module list
Currently Loaded Modulefiles:
  1) bzip2-1.0.6-clang-8.0.0-apple-v2mr5fi           8) py-pygments-2.1.3-clang-8.0.0-apple-cllzy4u
  2) ncurses-6.0-clang-8.0.0-apple-yz5pwlp           9) py-urwid-1.3.0-clang-8.0.0-apple-zmdraae
  3) zlib-1.2.11-clang-8.0.0-apple-ahv5tlv          10) py-pudb-2016.2-clang-8.0.0-apple-lqp42db
  4) openssl-1.0.2k-clang-8.0.0-apple-uu5hex7       11) py-six-1.10.0-clang-8.0.0-apple-joiwuvu
  5) readline-7.0-clang-8.0.0-apple-fuphoes         12) py-packaging-16.8-clang-8.0.0-apple-aaouo3x
  6) sqlite-3.8.5-clang-8.0.0-apple-qhml3gk         13) py-pyparsing-2.1.10-clang-8.0.0-apple-544yq7f
  7) python-2.7.13-clang-8.0.0-apple-4bnzmjs        14) py-appdirs-1.4.0-clang-8.0.0-apple-blplkct
```
loading setuptools is actually required
```
$ spack load py-setuptools
$ pudb
Usage: pudb [options] SCRIPT-TO-RUN [SCRIPT-ARGUMENTS]

Options:
  -h, --help          show this help message and exit
  -s, --steal-output  
  --pre-run=COMMAND   Run command before each program run
```

**Comment by adamjstewart** [comment]
Exactly. It _should_ have a runtime dependency, but the `package.py` didn't declare it. This is corrected in #3502.

**Comment by healther** [comment]
Ah, sorry then I misread your answer. However that does not fix my problem (I should really do a ```git diff``` before posting, I had changed that locally without having an effect).

**Comment by healther** [comment]
Okay I started to poke around a bit and it seems that @adamjstewart 's patch regarding the ```py-setuptools``` run-dependency of ```py-pudb``` doesn't make it into the db. Even after a ```spack reindex```. 
At least my ```opt/spack/.spack-db/index.json``` didn't change after pulling the current LLNL-develop and running ```spack reindex```.
Is this intentional behavior?

**Comment by healther** [comment]
Turns out I also needed to reinstall ```py-pudb```, is it possible that the load commands etc are based on the ```package.py``` at the time of the install? If so maybe there should be a warning if a user wants to load a package which ```package.py``` has changed

**Comment by healther** [comment]
After some further testing:
It is sufficient to just _additionally_ install ```py-pudb``` after the update of its ```package.py```, this however leaves me with two installed ```py-pudb```'s, which are both loaded on a ```spack load py-pudb``` call, which is definitely not what I expected.
I'm not comfortable with the silence of ```spack load``` in my opinion it should both complain if it finds multiple or none compatible package

**Comment by citibeth** [comment]
Can you generate the correct set of modules using `spack module loads`?

**Comment by adamjstewart** [comment]
> is it possible that the load commands etc are based on the `package.py` at the time of the install?

Sounds like it. In my opinion, that's the create behavior. Imagine this: If you add a new package to a branch and switch back to develop, that package no longer exists according to Spack. But you still want to be able to use it. Using the `package.py` that it was installed with solves this problem.

> which are both loaded on a `spack load py-pudb` call, which is definitely not what I expected.

I agree, we shouldn't be loading multiple installations of the same package. @alalazo?

**Comment by healther** [comment]
@tgamblin Regarding your post in #3502, okay I get that the ```package.py``` at install-time is the one that should be associated with an installed module, however I still think it is unexpected behaviour (at least from the user side) that changing a dependency_type_ requires a reinstall. Not that I don't understand why it is necessary, but I didn't expect it from the start (as proven by me opening this issue). 

I guess I would have liked for spack to tell me that I'm working with an outdated ```package.py``` file. Regarding your example: A dropped dependency on a new version should _not_ change the spec of an older version. The information in ```package.py``` should only be increasing (i.e. adding a restriction to a dependency, not removing it)

What happens right now is (at least for me) not helpful, as 
1. add missing dependency to ```package.py```
2. notice that ```spack load``` does not honor that change
3. do ```spack install <package>```
4. now ```spack load <package>``` loads both modules (the outdated and the current)

I'm not even sure if it's deterministic which of the two will be the first one in the final environment.

I see a couple of ways to resolve this:
1. Don't use the ```package.py``` from the install time (probably not wanted, as it may change the resulting behaviour)
2. Ask the user what to do when the two ```package.py``` are not identical (probably also not wanted, e.g. a new version is not a reason to complain)
3. Implement a smarter comparison that detects if the current ```package.py``` would lead to a different spec and ask if that's the case (probably pretty costly, but essentially what I would want)
4. Abort or at least warn if there are multiple responses to ```spack.store.db.query(spec, **kwargs)``` in ```_specs``` for a ```ConstraintAction```

1 & 2 wouldn't really fix the problem. I have 4 at the moment for me locally, but haven't tested it regarding different uses (i.e. not ```spack module loads```). This feels rather hacky
Ideally I would want to submit a PR for 3 and a more general way of handeling "not exactly one package found" behaviour (spack should complain if I want it to load a non-existing/installed package or one where multiple versions exist).

Is that something that you would be interested in or am I missing the point where the current behaviour is useful?

**Comment by citibeth** [comment]
The fundamental problem here is that `spack load` is wimpy,
non-deterministic and generally broken.  When you run `spack install`, you
specify what you want installed.  The next logical thing you do is `spack
load` (or equivalent).  You should not have to make Spack "guess" which
installed version you are looking for.

Spack Environments should absolutely fix this problem.  I'm reluctant to
spend large amounts of effort on a less-general solution.

**Comment by tgamblin** [comment]
> The information in package.py should only be increasing (i.e. adding a restriction to a dependency, not removing it)

If I understand you correctly, I don't think this is actually true.  It's legit for version 1.0 of `foo` to depend on a library and for version 1.5 NOT to depend on the same library.  We don't restrict that in Spack, and 1.0 and 1.5 should work fine if both installed at once.

> I still think it is unexpected behaviour (at least from the user side) that changing a dependency_type_ requires a reinstall.

Ok, maybe I should refine my answer.  I think it's true that *many* people would want the behavior you describe for *run* dependencies.  It's also true that we could probably change run dependencies retroactively without hurting much of anything, and that this would be beneficial when people find that their modules aren't generated *quite* the way they want (that's your real problem, right?)

Consider other dependencies, though:
1. For `build` dependencies, well we don't really care about those because they effectively don't exist at runtime (and we don't currently hash them either -- so build dependency versions won't affect hashes).

2. For `link` dependencies, things are harder.  `link` dependencies' library locations are actually written into the `RPATH`s of dependencies' binaries, so we would have to re-`RPATH` an entire installation to change link dependencies retroactively.  I suspect that changes to link dependencies typically mean that something very real has changed about the build, and we *should* reinstall.  Spack originally only had one type of dependency (basically `('build', 'link')`), and it was designed for complicated libraries so this is the case I've thought most about.

Now, back to run dependencies.  I actually agree with @citibeth that `spack load` is wimpy and that we should consider deprecating it once we have "real" environments (like nix or conda).  However, I think your issue is not just with `spack load` but also with the *modules* generated, and we do really care about the modules because that is how most HPC people are going to be using packages.

It is a massive PITA to notice that you forgot a run dependency (or several) and then to have to go and reinstall EVERYTHING, when all you really need is a `module refresh`.  So let's review your suggestions.  I mostly agree with them.  I think (3) could get tricky in the details, but it makes the most sense.

```console
# prefer current `package.py` files for all generated modules
spack module refresh --use-current-package

# prefer current `package.py` files for run dependencies that match <spec>
spack module refresh --use-current-package <spec>
```

For each of these, you'd want to take the root of the installed DAG, strip its dependencies (including deptypes), and re-concretize it with the current packages.  If the resulting spec is different (besides deptypes) then I think we can safely use the new spec, with the *old* hashes (to preserve directory locations) to generate the module, with additional run deps it might have.  So basically you just copy the new deptypes into the old spec and generate the module with that.  If it's different I would argue that things have changed too much and you should reinstall.

That would allow you to potentially update your modules by adding/removing run dependencies to packages as needed, and I think it would reduce the iteration time on module generation for Spack users.  It would preserve old hashes, and thus *not* disrupt any link dependencies, and really the only thing that would change would be the modules.

Now, if i put on my reproducibility hat and think about what we want to do with Spack environments, I am not sure I like this as much.  I would really like to ensure that a spec with a certain hash, when activated in a certain environment, does the *same* thing.  So I think I would be opposed to adding equivalent behavior to environment generation.  But I could see how this would help with modules, and I think *most* sites consider the module tree as something separate from the packages themselves.  What do you think?

**Comment by citibeth** [comment]
Please see #3513 for my thoughts on this matter.

**Comment by healther** [comment]
@tgamblin 

> If I understand you correctly, I don't think this is actually true. It's legit for version 1.0 of foo to depend on a library and for version 1.5 NOT to depend on the same library. We don't restrict that in Spack, and 1.0 and 1.5 should work fine if both installed at once.

I meant that even if version 1.5 no longer depends on bar, spack does still know that version 1.0 did depend on it -> hence the _information_ should still be available in the ```package.py```


> That would allow you to potentially update your modules by adding/removing run dependencies to packages as needed, and I think it would reduce the iteration time on module generation for Spack users. It would preserve old hashes, and thus not disrupt any link dependencies, and really the only thing that would change would be the modules.

My problem was/is more that if I have a "broken" ```package.py``` (i.e. missing dependency), doing a ```spack module loads --dependencies``` or a ```spack load --dependencies``` gives me a broken package, i.e. something that is unusable. I would either expect spack to detect, that I'm reinstalling an already installed package (up to dependencies) and ask me whether this should indicate a broken installation, or to at least not give me both in case of ```spack module loads <package>``` and complain when finding multiple specs fitting a single package. (Is there any use case where I want multiple versions of a package loaded at the same time?)


After these discussions I think that my main problem isn't so much the module handling or even install hashing, but rather that ```spack load <package>``` may load 0, 1 or multiple versions of ```<package>``` without warning me.

**Comment by citibeth** [comment]
> I meant that even if version 1.5 no longer depends on bar, spack does
> still know that version 1.0 did depend on it -> hence the *information*
> should still be available in the package.py
>
In #3156 I suggested that the core installer part of Spack doesn't keep
around any `package.py` files.  It would be given only fully concretized
specs, along with a hash and `package.py` files for each node in the spec.
Clearly, anything dealing with installed packages would need to work off of
the `package.py` files used to originally install those packages (and
stored in the install dirs).



> That would allow you to potentially update your modules by adding/removing
> run dependencies to packages as needed, and I think it would reduce the
> iteration time on module generation for Spack users. It would preserve old
> hashes, and thus not disrupt any link dependencies, and really the only
> thing that would change would be the modules.
>
>

> My problem was/is more that if I have a "broken" package.py (i.e. missing
> dependency), doing a spack module loads --dependencies or a spack load
> --dependencies gives me a broken package, i.e. something that is
> unusable. I would either expect spack to detect, that I'm reinstalling an
> already installed package (up to dependencies) and ask me whether this
> should indicate a broken installation, or to at least not give me both in
> case of spack module loads <package> and complain when finding multiple
> specs fitting a single package. (Is there any use case where I want
> multiple versions of a package loaded at the same time?)
>
>  Would not #3513 clear up some of this?  Or are there two separate
problems... (1) modules change when you change dependencies, and (2) `spack
load` doesn't know which module to use...

After these discussions I think that my main problem isn't so much the
> module handling or even install hashing, but rather that spack load
> <package> may load 0, 1 or multiple versions of <package> without warning
> me.
>
Agreed.  `spack load` is nondeterministic, and thus not as useful as one
would think at first.  We need Spack Environments.

**Comment by healther** [comment]
My original issue is closed, so I close this thread. I think the discussions are better placed in #3515 or #3513
