### ISSUE TITLE
python+tkinter in a unified environment: "Cyclic dependency detected"

### ISSUE THREAD

**Issue by flxmr** [LLNL/spack#37947]
### Steps to reproduce

So, I want to create a (more or less "deterministic") unified environment including python with tkinter. Aka I put the following in a `spack.yaml` and create an environment:
```
spack:
  specs:
  - python @3.10+libxml2+tkinter %gcc@11.3.0
  view: true
  concretizer:
    unify: true
```

Then I concretize

### Error message

Now I want to concretize:
```
fmm@spack>spack -e testpy concretize -f
==> Error: concretization failed for the following reasons:

   1. Cyclic dependency detected between 'xcb-proto' and 'xcb-proto' (consider changing variants to avoid the cycle)
   2. Cyclic dependency detected between 'xcb-proto' and 'tk' (consider changing variants to avoid the cycle)
   3. Cyclic dependency detected between 'xcb-proto' and 'python' (consider changing variants to avoid the cycle)
   4. Cyclic dependency detected between 'xcb-proto' and 'libxcb' (consider changing variants to avoid the cycle)
   5. Cyclic dependency detected between 'xcb-proto' and 'libx11' (consider changing variants to avoid the cycle)
   6. Cyclic dependency detected between 'tk' and 'xcb-proto' (consider changing variants to avoid the cycle)
   7. Cyclic dependency detected between 'tk' and 'tk' (consider changing variants to avoid the cycle)
   8. Cyclic dependency detected between 'tk' and 'python' (consider changing variants to avoid the cycle)
   9. Cyclic dependency detected between 'tk' and 'libxcb' (consider changing variants to avoid the cycle)
   10. Cyclic dependency detected between 'tk' and 'libx11' (consider changing variants to avoid the cycle)
   11. Cyclic dependency detected between 'python' and 'xcb-proto' (consider changing variants to avoid the cycle)
   12. Cyclic dependency detected between 'python' and 'tk' (consider changing variants to avoid the cycle)
   13. Cyclic dependency detected between 'python' and 'python' (consider changing variants to avoid the cycle)
   14. Cyclic dependency detected between 'python' and 'libxcb' (consider changing variants to avoid the cycle)
   15. Cyclic dependency detected between 'python' and 'libx11' (consider changing variants to avoid the cycle)
   16. Cyclic dependency detected between 'libxcb' and 'xcb-proto' (consider changing variants to avoid the cycle)
   17. Cyclic dependency detected between 'libxcb' and 'tk' (consider changing variants to avoid the cycle)
   18. Cyclic dependency detected between 'libxcb' and 'python' (consider changing variants to avoid the cycle)
   19. Cyclic dependency detected between 'libxcb' and 'libxcb' (consider changing variants to avoid the cycle)
   20. Cyclic dependency detected between 'libxcb' and 'libx11' (consider changing variants to avoid the cycle)
   21. Cyclic dependency detected between 'libx11' and 'xcb-proto' (consider changing variants to avoid the cycle)
   22. Cyclic dependency detected between 'libx11' and 'tk' (consider changing variants to avoid the cycle)
   23. Cyclic dependency detected between 'libx11' and 'python' (consider changing variants to avoid the cycle)
   24. Cyclic dependency detected between 'libx11' and 'libxcb' (consider changing variants to avoid the cycle)
   25. Cyclic dependency detected between 'libx11' and 'libx11' (consider changing variants to avoid the cycle)
```

I think this is a bug as it should be possible to build python + X11 in a "clean" fashion.

Essentially this seems to happen, because `xcb-proto` extends `python` https://github.com/spack/spack/blame/develop/var/spack/repos/builtin/packages/xcb-proto/package.py#L23, while `libxcb` depends on `python` https://github.com/spack/spack/commit/371a8a361a838cca2c59da748498b31e0a8926db

Removing the python-dependency and the `extends` at least leads to concretization (checking currently what happens down the road)...

### Information on your system

* **Spack:** 0.21.0.dev0 (2f8cea2792322e5bc39bc2444f24862dd425c4d7)
* **Python:** 3.11.2
* **Platform:** linux-fedora38-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by flxmr** [comment]
Ok, I guess this is a very weird world, where we are in. Apparently you can't built libxcb without python, thus now no Tk without python, and no tkinter without tk. That is really weird. I wonder if breaking out tkinter as `py-tkinter` might make sense in spack? (could be done like proposed here: https://github.com/panda3d/tkinter)

**Comment by Jordan474** [comment]
I have the same issue with a simple `spack spec --fresh python+tkinter` (when there no python already installed(*)).

I tracked the regression to spack/spack#37575 . I would have thought this MR would require separate concretization of build dependencies to finally allow that change ?

If I comment the python dependency in `xcb-proto` and `libxcb` , then `python+tkinter` concertizes without cycles again.

(*) When I had a `python~tkinter` already installed, I'm sure I've seen spack use it for build dependencies and ignore the cycle.

**Comment by snehring** [comment]
I've also just hit this today, although I'm not actually in a unified environment, I just have it set up to unify when possible.

**Comment by flxmr** [comment]
https://github.com/spack/spack/issues/38226 would solve this too.

**Comment by gabrielctn** [comment]
I still get this issue ...

**Comment by snehring** [comment]
This seems to be default behavior of a fresh spack now if there isn't another python available.

**Comment by gabrielctn** [comment]
How did you manage to solve this issue ? I have other pythons available, but I need specifically one with tk

**Comment by flxmr** [comment]
you just remove the dependency/extends in libxcb/xcb-proto. I don't think it's that fastchanging so your patch/cherrypick should go nicely forward. Other than that the cleanest solution would be to make a py-tkinter-package!

**Comment by gabrielctn** [comment]
Ok it worked thanks !

**Comment by wdconinc** [comment]
Possibly addressed by https://github.com/spack/spack/pull/41875.

**Comment by brechtm** [comment]
I still cannot install python@3.13.2+tkinter. I have a different error message however:
```
>> 2209    [ERROR] _tkinter failed to import: libtk8.6.so: cannot open shared object file: No such file or directory
```

while tk 8.6.11 was already installed, multiple times?
```
/apps/hosted/spack $ spack find --variants tk
-- linux-rhel7-haswell / gcc@4.8.5 ------------------------------
tk@8.6.11+xft+xss  tk@8.6.11+xft+xss

-- linux-rhel7-skylake_avx512 / gcc@12.1.0 ----------------------
tk@8.6.11+xft+xss build_system=autotools  tk@8.6.11+xft+xss build_system=autotools
==> 4 installed packages
```

Commenting out the python dependency in _xcb-proto_ and _libxcb_ as suggested in https://github.com/spack/spack/issues/37947#issuecomment-1600865081 makes it possible to build _python@3.13.2+tkinter_ succesfully.

There seems to be a cyclic dependency between Python and Tk (#41146, spack/spack#41875, spack/spack#49201):
- Installing python-3.13.2-zrfkl6c2inbtm4ejslymiaxz4hn2decp [42/53]
- Warning: Skipping build of tk-8.6.11-lmrwy4ek44kvyml3u73zntjhmeol4am2 since libxft-2.3.8-uheonq6q32gpv2bys4in4til2xcwpjyc failed
- Warning: Skipping build of python-3.13.2-zg3hgpr4pfmzarh5veuns5nfuym2cagc since tk-8.6.11-lmrwy4ek44kvyml3u73zntjhmeol4am2 failed

Here's the full output:
<details>
  <summary><code>$ spack install python@3.13.2 +tkinter</code></summary>

```sh
[+] /usr (external glibc-2.17-7twpga5eggtc6nrhovsbs4zg7qjxbohu)
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/gcc-runtime-12.1.0-m4umwri4meuuokefxpyxmlobpro6yo4q
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/scrnsaverproto-1.2.2-35offbhzasubm5mvudf2quptfzpdae6k
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/zstd-1.5.6-ir5yducquq3b766cxclo24muulpr2s2a
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/xextproto-7.3.0-fbdlmw6hwgxs4hqmf2dbnz6rrngup5ch
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/berkeley-db-18.1.40-cs4bo5t2tcqlza56xb3evlm7fb3uutdc
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/zlib-ng-2.2.1-snfixpf42m6vei7u4dsyktt2urckjuvs
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/libiconv-1.17-nshaxjtpsp5ef2i7scs5kkgyho3lc666
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/xz-5.4.6-uvg3zhk2ftceh3646bn6ki5djwpfry2w
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/libpthread-stubs-0.5-zxl6sanbzchq3imccwffce4fyxxx4lfe
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/inputproto-2.3.2-74f2v5wv64mre7kclb5mvnhmjf3djb7w
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/pkgconf-2.2.0-uj5gsbhd4mocqxk2r53yakhca6oscphn
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/util-macros-1.20.1-zicnerw25y36cleheuzezmm5fl57y6f3
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/libffi-3.4.6-bpri7s4agfvon5672t56nxtmndo5zki5
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/gmake-4.4.1-smkdc37zghp5y5jnn3sahfqlnnuzcrw6
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/tcl-8.6.12-cl75mjdfccrjnqecvj7sapqevrwfsxz5
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/libxml2-2.10.3-i3yp5znawbk73j2sg5bdfenextzha4w3
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/openssl-3.3.1-2q3xzj5lgr6jzlarz3ojqd7wlh3k2jq7
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/renderproto-0.11.1-2shcik6ubxub4qrhay2dzsya7cd6oaov
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/xtrans-1.5.2-datfn4lis7fd2fcn3yezp4vl2swm43th
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/libmd-1.0.4-unrvljsvr2tnqc2ygt4a5revjc4mo3ft
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/gperf-3.1-4o6rlsptdw7jtjfrmjjpalxjl7kvkda4
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/kbproto-1.0.7-hc2genl7pyx53wueaiag23z6zv7gciae
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/util-linux-uuid-2.40.2-55yd2aslq7yuze4vhmramfw3ze7nc42u
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/font-util-1.4.1-flcui5tgnvntyyeqifd3nka333vc3zxc
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/ncurses-6.5-nrtk44ovm24m7gbetqjtusor7mgbvg5e
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/bzip2-1.0.8-lp24qpeblb7n6b5phnnlmu2uzzz652qt
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/pigz-2.8-qcjc2as6grehqvw3ngqcpcss6ntdr7re
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/xproto-7.0.31-snefrkti7spo5mapfujkcupd56rcunrb
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/libpng-1.6.39-ntjyvajw4mpafhwuszrrizz3rrvbh5ma
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/libbsd-0.12.2-ghowykrgkicbzh4aqrrmvgnglhaefwgp
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/readline-8.2-qiojmudyhizsmeu6fyrxr7fatfdp5svw
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/tar-1.34-cgflthioahps44vr77mm76ra52wadthx
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/libxau-1.0.12-p77m5ap6fogdxr4uwuyyaja3xqfipv4w
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/freetype-2.13.2-tzef2jy23hbzh5vznmsou44csuxg6dh5
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/expat-2.6.3-xwcd34zgv6mupqqizuohxkdvkspzssbb
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/libxdmcp-1.1.5-qrn6whll5snzujp3ns2yosu36zwpwlsn
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/gdbm-1.23-veteu4vgwcwsqyvgnrku74i6optw3jj4
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/sqlite-3.46.0-ykzc4r5tgg24rtclmv5dkpcmlic4rbzn
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/gettext-0.22.5-ft3sruf5ygckfnx76tfukgdc7uyxhcot
[+] /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/perl-5.40.0-gubknvursf3g6ge2l2vajwrsqfz2jrj6
==> Installing python-3.13.2-zrfkl6c2inbtm4ejslymiaxz4hn2decp [42/53]
==> No binary for python-3.13.2-zrfkl6c2inbtm4ejslymiaxz4hn2decp found: installing from source
==> Using cached archive: /apps/hosted/spack/var/spack/cache/_source-cache/archive/b8/b8d79530e3b7c96a5cb2d40d431ddb512af4a563e863728d8713039aa50203f9.tgz
==> Ran patch() for python
==> python: Executing phase: 'configure'
==> python: Executing phase: 'build'
==> python: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    '/apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/gmake-4.4.1-smkdc37zghp5y5jnn3sahfqlnnuzcrw6/bin/make' '-j1' 'install' 'COMPILEALL_OPTS=-j8'

4 errors found in build log:
     2203    if test $? -ne 0 ; then \
     2204    	echo "generate-posix-vars failed" ; \
     2205    	rm -f ./pybuilddir.txt ; \
     2206    	exit 1 ; \
     2207    fi
     2208    LD_LIBRARY_PATH=/apps/hosted/spack/var/spack/stage/appshost/spack-stage-python-3.13.2-zrfkl6c2inbtm4ejslymiaxz4hn2decp/spack-src ./python -E -c 'import sys
             ; from sysconfig import get_platform ; print("%s-%d.%d" % (get_platform(), *sys.version_info[:2]))' >platform
  >> 2209    [ERROR] _tkinter failed to import: libtk8.6.so: cannot open shared object file: No such file or directory
     2210    Following modules built successfully but were removed because they could not be imported:
     2211    _tkinter
     2212
     2213    Checked 112 modules (33 built-in, 77 shared, 1 n/a on linux-x86_64, 0 disabled, 0 missing, 1 failed on import)
     2214    ==> python: Executing phase: 'install'
     2215    ==> [2025-03-14-10:19:15.752330] '/apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/gmake-4.4.1-smkdc37zghp5y5jnn3sahfqlnnuzcrw6/bin/make'
             '-j1' 'install' 'COMPILEALL_OPTS=-j8'

     ...

     2252    	if test -d "libpython3.13.so.dSYM"; then \
     2253    		echo  /libpython3.13.so.1.0; \
     2254           /libpython3.13.so.1.0; \
     2255    	fi \
     2256    fi
     2257    /apps/hosted/spack/lib/spack/env/gcc/gcc -pthread -shared -L/apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/gettext-0.22.5-ft3sruf5ygckfn
             x76tfukgdc7uyxhcot/lib -L/apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/xz-5.4.6-uvg3zhk2ftceh3646bn6ki5djwpfry2w/lib -L/apps/hosted/spa
             ck/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/zlib-ng-2.2.1-snfixpf42m6vei7u4dsyktt2urckjuvs/lib -L/apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx
             512/gcc-12.1.0/libffi-3.4.6-bpri7s4agfvon5672t56nxtmndo5zki5/lib64 -L/apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/util-linux-uuid-2.40
             .2-55yd2aslq7yuze4vhmramfw3ze7nc42u/lib -L/apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/bzip2-1.0.8-lp24qpeblb7n6b5phnnlmu2uzzz652qt/li
             b  -L/apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/openssl-3.3.1-2q3xzj5lgr6jzlarz3ojqd7wlh3k2jq7/lib64 -L/apps/hosted/spack/opt/spack/
             linux-rhel7-skylake_avx512/gcc-12.1.0/sqlite-3.46.0-ykzc4r5tgg24rtclmv5dkpcmlic4rbzn/lib -L/apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.
             0/expat-2.6.3-xwcd34zgv6mupqqizuohxkdvkspzssbb/lib  -L/apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/readline-8.2-qiojmudyhizsmeu6fyrxr7
             fatfdp5svw/lib -L/apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/ncurses-6.5-nrtk44ovm24m7gbetqjtusor7mgbvg5e/lib -L/apps/hosted/spack/op
             t/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/gdbm-1.23-veteu4vgwcwsqyvgnrku74i6optw3jj4/lib     Modules/_tkinter.o Modules/tkappinit.o -L/apps/hosted/spack
             /opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/tk-8.6.11-uhv36k6mhwhnglee3kplogcm4oav5m64/lib -ltk8.6 -ltkstub8.6 -L/apps/hosted/spack/opt/spack/linux-rhe
             l7-skylake_avx512/gcc-12.1.0/tcl-8.6.12-be7zjtzcmam6yuzuc4carimatolwjavy/lib -ltcl8.6 -ltclstub8.6  -o Modules/_tkinter.cpython-313-x86_64-linux-gnu.so
  >> 2258    [ERROR] _tkinter failed to import: libtk8.6.so: cannot open shared object file: No such file or directory
     2259    Following modules built successfully but were removed because they could not be imported:
     2260    _tkinter
     2261
     2262    Checked 112 modules (33 built-in, 77 shared, 1 n/a on linux-x86_64, 0 disabled, 0 missing, 1 failed on import)
     2263    Creating directory /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/python-3.13.2-zrfkl6c2inbtm4ejslymiaxz4hn2decp/lib/python3.13
     2264    Creating directory /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/python-3.13.2-zrfkl6c2inbtm4ejslymiaxz4hn2decp/lib/python3.13/asyncio

     ...

     7013    /bin/install -c -m 755 Modules/_curses_panel.cpython-313-x86_64-linux-gnu.so /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/python-3.13.
             2-zrfkl6c2inbtm4ejslymiaxz4hn2decp/lib/python3.13/lib-dynload/_curses_panel.cpython-313-x86_64-linux-gnu.so
     7014    /bin/install -c -m 755 Modules/_sqlite3.cpython-313-x86_64-linux-gnu.so /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/python-3.13.2-zrf
             kl6c2inbtm4ejslymiaxz4hn2decp/lib/python3.13/lib-dynload/_sqlite3.cpython-313-x86_64-linux-gnu.so
     7015    /bin/install -c -m 755 Modules/_ssl.cpython-313-x86_64-linux-gnu.so /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/python-3.13.2-zrfkl6c
             2inbtm4ejslymiaxz4hn2decp/lib/python3.13/lib-dynload/_ssl.cpython-313-x86_64-linux-gnu.so
     7016    /bin/install -c -m 755 Modules/_hashlib.cpython-313-x86_64-linux-gnu.so /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/python-3.13.2-zrf
             kl6c2inbtm4ejslymiaxz4hn2decp/lib/python3.13/lib-dynload/_hashlib.cpython-313-x86_64-linux-gnu.so
     7017    /bin/install -c -m 755 Modules/_uuid.cpython-313-x86_64-linux-gnu.so /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/python-3.13.2-zrfkl6
             c2inbtm4ejslymiaxz4hn2decp/lib/python3.13/lib-dynload/_uuid.cpython-313-x86_64-linux-gnu.so
     7018    /bin/install -c -m 755 Modules/_tkinter.cpython-313-x86_64-linux-gnu.so /apps/hosted/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-12.1.0/python-3.13.2-zrf
             kl6c2inbtm4ejslymiaxz4hn2decp/lib/python3.13/lib-dynload/_tkinter.cpython-313-x86_64-linux-gnu.so
  >> 7019    /bin/install: cannot stat 'Modules/_tkinter.cpython-313-x86_64-linux-gnu.so': No such file or directory
  >> 7020    make: *** [Makefile:2311: sharedinstall] Error 1

See build log for details:
  /apps/hosted/spack/var/spack/stage/appshost/spack-stage-python-3.13.2-zrfkl6c2inbtm4ejslymiaxz4hn2decp/spack-build-out.txt

==> Warning: Skipping build of xcb-proto-1.17.0-nhpnin6fhodfldulmdu6xd254evacu75 since python-3.13.2-zrfkl6c2inbtm4ejslymiaxz4hn2decp failed
==> Warning: Skipping build of libxcb-1.17.0-ajjqdllawkth4ep3iutecvnhbwlugjy7 since xcb-proto-1.17.0-nhpnin6fhodfldulmdu6xd254evacu75 failed
==> Warning: Skipping build of libx11-1.8.10-r5qyx2a4fioy5yau454pwdaj7huxwpfa since libxcb-1.17.0-ajjqdllawkth4ep3iutecvnhbwlugjy7 failed
==> Warning: Skipping build of libxrender-0.9.11-3heddsj2f3xt6e5nhqbj2v6uif6dhtre since libx11-1.8.10-r5qyx2a4fioy5yau454pwdaj7huxwpfa failed
==> Warning: Skipping build of libxft-2.3.8-uheonq6q32gpv2bys4in4til2xcwpjyc since libxrender-0.9.11-3heddsj2f3xt6e5nhqbj2v6uif6dhtre failed
==> Warning: Skipping build of tk-8.6.11-lmrwy4ek44kvyml3u73zntjhmeol4am2 since libxft-2.3.8-uheonq6q32gpv2bys4in4til2xcwpjyc failed
==> Warning: Skipping build of python-3.13.2-zg3hgpr4pfmzarh5veuns5nfuym2cagc since tk-8.6.11-lmrwy4ek44kvyml3u73zntjhmeol4am2 failed
==> Warning: Skipping build of libxext-1.3.6-nj3pyi6wohf6t2ounmog6wj7dmqk6mh3 since libx11-1.8.10-r5qyx2a4fioy5yau454pwdaj7huxwpfa failed
==> Warning: Skipping build of libxscrnsaver-1.2.4-f7f4jia5wtry23o5srqqas3diwupjhkf since libxext-1.3.6-nj3pyi6wohf6t2ounmog6wj7dmqk6mh3 failed
==> Warning: Skipping build of fontconfig-2.15.0-ix6w7iswrpybyrjyp2hnmcaql7bps6fg since python-3.13.2-zrfkl6c2inbtm4ejslymiaxz4hn2decp failed
==> Warning: Skipping build of python-venv-1.0-twrh4tke4zrfbngs6deq3n3y7aaxpe32 since python-3.13.2-zrfkl6c2inbtm4ejslymiaxz4hn2decp failed
==> Error: python-3.13.2-zg3hgpr4pfmzarh5veuns5nfuym2cagc: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
```
</details>

* **Spack:** 1.0.0.dev0 (8235aa1804f70bfcab93c6a4c004b0b21b07ddee)
* **Python:** 3.10.4
* **Platform:** linux-rhel7-skylake_avx512

**Comment by alalazo** [comment]
@brechtm There _is_ a cyclic dependency between Python and tk. The PR I linked makes it possible to concretize `python+tkinter` using a `python~tkinter` for the cyclic dependency. Did you try a fresh build:
```
$ spack env activate --temp
$ spack add python@3.13 +tkinter
$ spack concretize -f --fresh
$ spack -v install
```
?

**Comment by brechtm** [comment]
@alalazo At this moment I cannot spend more time on this, unfortunately, and I'm afraid I don't know enough about how spack works to understand exactly what you are saying (for example, I'll need to look up the meaning of `python~tkinter`). Do you mean that existing installed packages cause this problem for me? If so, that is quite confusing behavior. 

BTW, probably related: spack/spack-packages#2067
