### ISSUE TITLE
Installation issue: on Azure storage cifs

### ISSUE THREAD

**Issue by vpiratla** [LLNL/spack#42507]
### Steps to reproduce the issue

```console
$ spack spec -I ca-certificates-mozilla
Input spec
--------------------------------
 -   ca-certificates-mozilla

Concretized
--------------------------------
 -   ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-centos7-x86_64_v4
[+]      ^gcc-runtime@11.4.0%gcc@11.4.0 build_system=generic arch=linux-centos7-x86_64_v4

```

### Error message

<details><summary>Error message</summary>

==> [2024-02-05-13:15:15.764057] Error: OSError: [Errno 38] Function not implemented: '/mnt/modulesharecifs/spack/opt/spack/linux-centos7-x86_64_v4/gcc-10.2.0/gcc-runtime-10.2.0-iq2yqqra7yq4g4zx4e2iee6cvo5vgzol/.spack/repos/builtin/packages/gcc-runtime/package.py'
See build log for details:
  /tmp/root/spack-stage/spack-stage-ca-certificates-mozilla-2023-05-30-ah67fxjbnujnn63z5vnkdhy2omeqfwe2/spack-build-out.txt

Traceback (most recent call last):
  File "/mnt/modulesharecifs/spack/lib/spack/spack/build_environment.py", line 1115, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/mnt/modulesharecifs/spack/lib/spack/spack/installer.py", line 2495, in build_process
    return installer.run()
  File "/mnt/modulesharecifs/spack/lib/spack/spack/installer.py", line 2360, in run
    self._real_install()
  File "/mnt/modulesharecifs/spack/lib/spack/spack/installer.py", line 2472, in _real_install
    log(pkg)
  File "/mnt/modulesharecifs/spack/lib/spack/spack/installer.py", line 720, in log
    dump_packages(pkg.spec, packages_dir)
  File "/mnt/modulesharecifs/spack/lib/spack/spack/installer.py", line 600, in dump_packages
    source_pkg_dir, dest_pkg_dir, allow_broken_symlinks=(sys.platform != "win32")
  File "/mnt/modulesharecifs/spack/lib/spack/llnl/path.py", line 99, in path_filter_caller
    return func(*args, **kwargs)
  File "/mnt/modulesharecifs/spack/lib/spack/llnl/util/filesystem.py", line 902, in install_tree
    _permissions=True,
  File "/mnt/modulesharecifs/spack/lib/spack/llnl/path.py", line 99, in path_filter_caller
    return func(*args, **kwargs)
  File "/mnt/modulesharecifs/spack/lib/spack/llnl/util/filesystem.py", line 862, in copy_tree
    shutil.copy2(s, d)
  File "/usr/lib64/python3.6/shutil.py", line 264, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/mnt/modulesharecifs/spack/lib/spack/llnl/util/filesystem.py", line 130, in copystat
    shutil._copyxattr(src, dst, follow_symlinks=follow)
  File "/usr/lib64/python3.6/shutil.py", line 157, in _copyxattr
    names = os.listxattr(src, follow_symlinks=follow_symlinks)
OSError: [Errno 38] Function not implemented: '/mnt/modulesharecifs/spack/opt/spack/linux-centos7-x86_64_v4/gcc-10.2.0/gcc-runtime-10.2.0-iq2yqqra7yq4g4zx4e2iee6cvo5vgzol/.spack/repos/builtin/packages/gcc-runtime/package.py'
==> [2024-02-05-13:15:15.765054] Flagging ca-certificates-mozilla-2023-05-30-ah67fxjbnujnn63z5vnkdhy2omeqfwe2 as failed: OSError: [Errno 38] Function not implemented: '/mnt/modulesharecifs/spack/opt/spack/linux-centos7-x86_64_v4/gcc-10.2.0/gcc-runtime-10.2.0-iq2yqqra7yq4g4zx4e2iee6cvo5vgzol/.spack/repos/builtin/packages/gcc-runtime/package.py'
==> [2024-02-05-13:15:16.145970] ChildError: OSError: [Errno 38] Function not implemented: '/mnt/modulesharecifs/spack/opt/spack/linux-centos7-x86_64_v4/gcc-10.2.0/gcc-runtime-10.2.0-iq2yqqra7yq4g4zx4e2iee6cvo5vgzol/.spack/repos/builtin/packages/gcc-runtime/package.py'

...
</pre></details>

### Information on your system

/mnt/modulesharecifs  is a cifs mount on Azure, 

```mnt/modulesharecifs type cifs (rw,relatime,vers=default,cache=strict,,domain=X,username=xxxx,uid=0,noforceuid,gid=0,noforcegid,addr=x.x.x.x,file_mode=0777,dir_mode=0777,soft,persistenthandles,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=30)```

* **Spack:** 0.22.0.dev0 (0960f691a1ad80beeb32a95ea77edcf2f3fc79cc)
* **Python:** 3.6.8
* **Platform:** linux-centos7-x86_64_v4
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/14172109/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/14172113/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by wyphan** [comment]
I'd also add that using the `copystat` method from the Python built-in `shutil` module with `follow_symlinks=False` already reproduces the error.

**Comment by haampie** [comment]
Can you check if it's fixed in a newer version of Python? 3.6 is ancient and not maintained

**Comment by wyphan** [comment]
@haampie The irony is this issue hit us when trying to Spack-build Python 3.11.6 on the CIFS mount. We can try building it somewhere else and report back.

**Comment by vpiratla** [comment]
We tried with latest python version and the issue is still the same
spack -d -k install ca-certificates-mozilla
ERROR: OSError: [Errno 38] Function not implemented: '/mnt/moduleshare/gcc-runtime/11.4.0/.spack/repos/builtin/packages/gcc-runtime/package.py'
==> [2024-02-08-13:51:21.740099] Flagging ca-certificates-mozilla-2023-05-30-cixfdugcxkfpjmo5jfq66tkvbpjbjs5b as failed: OSError: [Errno 38] Function not implemented: '/mnt/moduleshare/gcc-runtime/11.4.0/.spack/repos/builtin/packages/gcc-runtime/package.py'
==> [2024-02-08-13:51:22.102081] ChildError: OSError: [Errno 38] Function not implemented: '/mnt/moduleshare/gcc-runtime/11.4.0/.spack/repos/builtin/packages/gcc-runtime/package.py'
[root@ip-0AB42689 spack]# spack python --version
Python 3.11.6

**Comment by haampie** [comment]
Try with

```diff
diff --git a/lib/spack/llnl/util/filesystem.py b/lib/spack/llnl/util/filesystem.py
index 63eea1788e..ec758e05ea 100644
--- a/lib/spack/llnl/util/filesystem.py
+++ b/lib/spack/llnl/util/filesystem.py
@@ -859,7 +859,7 @@ def escaped_path(path):
                 if os.path.isdir(s):
                     mkdirp(d)
                 else:
-                    shutil.copy2(s, d)
+                    shutil.copy(s, d)
 
             if _permissions:
                 set_install_permissions(d)
```

shutils looks like giant mess regarding extended attributes.

@trws do you agree it would be better not to even attempt to copy extended attributes in Spack in general? Where necessary, let people do so explicitly? But in practice I think it's nowhere necessary? They're probably not in source tarballs, nor in build cache tarballs, so would be surprised if anything could possible break if we just ignore xattrs.

**Comment by wyphan** [comment]
@haampie Another possible workaround is checking the value of ` os.supports_follow_symlinks` and not calling `copystat` if it's not supported.

**Comment by haampie** [comment]
Actually note https://github.com/spack/spack/blob/27b72b76918e9c14df1ca81e7a3e929a4fc44e7e/lib/spack/llnl/util/filesystem.py#L90

we're already patching `shutil.copystat` like that, although I don't immediately see how it's related, cause your error happens at

https://github.com/spack/spack/blob/27b72b76918e9c14df1ca81e7a3e929a4fc44e7e/lib/spack/llnl/util/filesystem.py#L130


The docstring says

> On Linux, copystat() also copies the "extended attributes" where possible.

but it's bogus since it doesn't wrap `_copyxattr` in a `try except OSError` and check if unsupported?

IMO better to avoid `shutil` as much as possible... it's very broken.

**Comment by wyphan** [comment]
We had a tiny reproducer Python script where `shutil.copystat` triggers the exact same error when we set `follow_symlinks=False` since this platform (Azure CIFS) prolly has some kind of NTFS storage backend (it's Microsoft after all) and thus doesn't support extended attributes.

**Comment by haampie** [comment]
Smallest reproducer should just be `os.listxattr(<regular file on Azure CIFS>)`

**Comment by trws** [comment]
Oof... Generally we can get away with it, many systems don't support them or if they do don't support them properly.  I ran into an issue with this using spack in a docker container on mac bind-mounting a MacOS filesystem too.  That's actually the case I'm a bit worried about though, extended attributes can be important in some cases where user namespaces are involved...  Not a super easy call.

I second the "avoid xattr" point though.  I recently found out that it will catch an error in `shutil.move` if the `os.relink` call fails, and *open the target file without unlinking it* to copy in the contents.  Not safe with permission changes. _sigh_
