### ISSUE TITLE
[spack buildcache push] fails with error: "401: Failed to login: Unauthorized"

### ISSUE THREAD

**Issue by jmurugan-fzj** [LLNL/spack#48187]
### Steps to reproduce

- Try to execute the **spack buildcache push** command to upload all the built packages to a private gitlab container registry
- Command fails with unauthorized error as shown below:
- ![image](https://github.com/user-attachments/assets/0227c7ba-9250-4de1-9e04-2a86e3b97657)
- The mirror for the cache is setup as follows (the ${variables} contain sensitive information, hence kept them as $vars!):
- ![image](https://github.com/user-attachments/assets/cf23cd1c-4dad-4a18-aa38-81f51ef4688d)

Note: Could not find the GitLab container registry usage information in the [docs section](https://spack.readthedocs.io/en/latest/binary_caches.html#oci-docker-v2-registries-as-build-cache). I assume, this must be the right way to define the mirror for _gitlab container registry_ via OCI scheme, if not please advice the right usage!  I have an associated GitLab token, which is been used also used along with the username as the combination for the defined access_pair.

### Information on your system

* **Spack:** 0.22.2 (594a376c521cc746978571b1181a47bbcff30a21)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Hi @jmurugan-fzj, thanks for opening this issue. It is indeed best to use env variables. You're getting 401s because `${...}` is taken as literal user/pass.

The latest release of Spack has improved dealing with token in env variables :)

It looks like we did not update the documentation yet, but we now have:

```
spack mirror add --oci-username-variable GITLAB_USER --oci-password-variable GITLAB_USER_ACCESS_TOKEN
```
and
```
spack mirror set --oci-username-variable GITLAB_USER --oci-password-variable GITLAB_USER_ACCESS_TOKEN buildcache-destination
```

**Comment by jmurugan-fzj** [comment]
> spack mirror add



> Hi @jmurugan-fzj, thanks for opening this issue. It is indeed best to use env variables. You're getting 401s because `${...}` is taken as literal user/pass.
> 
> The latest release of Spack has improved dealing with token in env variables :)
> 
> It looks like we did not update the documentation yet, but we now have:
> 
> ```
> spack mirror add --oci-username-variable GITLAB_USER --oci-password-variable GITLAB_USER_ACCESS_TOKEN
> ```
> 
> and
> 
> ```
> spack mirror set --oci-username-variable GITLAB_USER --oci-password-variable GITLAB_USER_ACCESS_TOKEN buildcache-destination
> ```

@haampie Thanks for the detailed information, but I have seen this issue while executing **spack buildcache push** command after replacing the variables with my actual username and access token (manually edited via **spack config edit**), hence created this issue! The respective mirrors-picture attached with the issue is just a sample and it is been used within the ci/cd GitLab pipeline which is also replaced correctly by the appropriate values during the pipeline execution! Strangely within the CI/CD build I see a completely different error, hence I was testing the command line upload of the binaries!
_Error seen in GitLab CI/CD pipeline build job:_
![image](https://github.com/user-attachments/assets/43754a7d-e9a2-4345-84d8-eb9e8bd47bc4)

Actually the options _--oci-username-variable_ and _--oci-password-variable_ are not available in my spack tool, is this not available in latest release?
![image](https://github.com/user-attachments/assets/d14071dc-7dbb-4a5e-9be7-358f13bdb5f6)
![image](https://github.com/user-attachments/assets/9c156e9a-62ac-4ab8-ad21-ec2049ed47e8)

**Comment by haampie** [comment]
Those flags were added in Spack 0.23

Can you check if that other issue is still present in Spack 0.23?

If so, please share `spack config get mirrors` (without the secret token).

**Comment by jmurugan-fzj** [comment]
> spack mirror add --oci-username-variable GITLAB_USER --oci-password-variable GITLAB_USER_ACCESS_TOKEN

@haampie The same problem is seen in v23.0 also!!
![image](https://github.com/user-attachments/assets/587f5df6-fc81-43d3-a190-6c5465d81572)

Tried different URLs too:

URL: oci://gitlab-registry.______.eu/GITLAB_USER
![image](https://github.com/user-attachments/assets/fc0e77d4-8023-4223-ade9-245ab81b60e9)

URL: oci://gitlab-registry.______.eu
![image](https://github.com/user-attachments/assets/93b56c3b-329d-45f9-bdcb-46d9c0c9913a)

**Comment by jmurugan-fzj** [comment]
@alalazo Why have you closed this issue?

**Comment by alalazo** [comment]
Cause I merged a PR that said to fix documentation for it? Note that this happens automatically, if somebody adds:
```
fixes XXXXX
closes XXXXX
```
to the PR description.

**Comment by jmurugan-fzj** [comment]
> Cause I merged a PR that said to fix documentation for it? Note that this happens automatically, if somebody adds:
> 
> ```
> fixes XXXXX
> closes XXXXX
> ```
> 
> to the PR description.

@alalazo Ahh I see, could you reopen it please? the issue still persists! Thanks

**Comment by haampie** [comment]
@jmurugan-fzj are you on the [Spack slack](https://slack.spack.io/)? That would make it a bit easier to troubleshoot this issue.

Looks like login fails because Spack expects more fields in the `WWW-Authenticate` header. I don't quite understand why your *.eu website redirects to Dockerhub for login. Better to discuss in chat.

**Comment by jmurugan-fzj** [comment]
@haampie Thanks, I just joined! messaged you there..

**Comment by haampie** [comment]
For the future reader, the issue with Gitlab registries is that they are associated to a specific repo, and you cannot push/tag arbitrary images with a given token.

In this example `oci://<gitlab domain>/<gitlab project>/<image name>` had to be used.
