### ISSUE TITLE
`spack commands --update-completion` broken

### ISSUE THREAD

**Issue by michaelkuhn** [LLNL/spack#51497]
### Steps to reproduce

Running the following command results in the completion files containing color codes. My guess would be that this was somehow broken by #51484.
```console
$ spack commands --update-completion
```
The following can be used as a workaround:
```console
$ spack commands --update-completion | tee
```

### Information on your system

* **Spack:** 1.1.0.dev0 (https://github.com/spack/spack/commit/b1ed39ae38e8c6939eeb7bdf3f2920984445975b)
* **Builtin repo:** https://github.com/spack/spack-packages/commit/70e933303b87ba111bd473eef2c85bcd5bf42a1d
* **Python:** 3.14.0
* **Platform:** linux-fedora43-skylake

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by becker33** [comment]
@michaelkuhn I'm having trouble reproducing the behavior -- can you post which commands/options you updated that you were trying to regenerate completions for?

**Comment by becker33** [comment]
Could it have been fixed by https://github.com/spack/spack/pull/51560?

**Comment by michaelkuhn** [comment]
This happens for the changes in #51495. I just gave it a try with up-to-date develop and it still happens for me.

**Comment by linsword13** [comment]
This might be related to the new coloring behavior from `argparse` (since 3.14): https://docs.python.org/3/library/argparse.html#color. There's a `color=` argument that can be used to turn things off. Based on the documentation, one workload could be to run the command with `NO_COLOR=1`.

**Comment by michaelkuhn** [comment]
I just gave this a try while rebasing #51495 and can confirm that `NO_COLOR=1` seems to fix the problem.

**Comment by johnwparent** [comment]
#52174 should resolve this.
