### ISSUE TITLE
Local repos with packages with patches break spack

### ISSUE THREAD

**Issue by Sbozzolo** [LLNL/spack#51505]
### Steps to reproduce

[visit](https://github.com/spack/spack-packages/tree/develop/repos/spack_repo/builtin/packages/visit) is a well-behaved and working package in `spack-packages`. What makes `visit` special is that it patches some of its dependencies. The steps below show that when you add `visit` to a local `repo`, spack stops working. 

First, verify that `spack info visit` works:
```console
$ spack info visit | head
CMakePackage:   visit

Description:
    VisIt is an Open Source, interactive, scalable, visualization, animation
    and analysis tool.

Homepage: https://wci.llnl.gov/simulation/computer-codes/visit/

Preferred version:  
    3.4.1      https://github.com/visit-dav/visit/releases/download/v3.4.1/visit3.4.1.tar.gz
```

Now, add a new repo `local`, where we copy the `visit` package
```bash
mkdir -p /tmp/spack_repo/local/packages
git clone --depth=1 https://github.com/spack/spack-packages.git /tmp/spack-packages
cp -r /tmp/spack-packages/repos/spack_repo/builtin/packages/visit /tmp/spack_repo/local/packages/
```

Add a `repo.yaml` to `/tmp/spack_repo/local`:
```yaml
repo:
  namespace: local
  api: v2.1
```

Add `/tmp/spack_repo/local/packages` to the repos:
```sh
spack repo add /tmp/spack_repo/local/
```

Verify that it is there:
```console
$ spack repo list
[+] local      v2.1    /tmp/spack_repo/local
...
```

Verify that `visit` is broken:
```console
$ spack info visit | head
==> Error: Package 'spack_repo.local.packages.vtk_m.package' not found in repository '/tmp/spack_repo/local'
Use 'spack create' to create a new package.
CMakePackage:   visit

Description:
    VisIt is an Open Source, interactive, scalable, visualization, animation
    and analysis tool.

Homepage: https://wci.llnl.gov/simulation/computer-codes/visit/

Preferred version:  
    3.4.1      https://github.com/visit-dav/visit/releases/download/v3.4.1/visit3.4.1.tar.gz
```

This also breaks environments where `visit` is not used:
```console
# spack -e . concretize -f
==> Error: Package 'spack_repo.local.packages.vtk_m.package' not found in repository '/tmp/spack_repo/local'
Use 'spack create' to create a new package.
```

### Information on your system

* **Spack:** 1.1.0.dev0 (https://github.com/spack/spack/commit/dc7e4a2de12347597f2ae0eb8570704cf4ccd51f)
* **Builtin repo:** https://github.com/spack/spack-packages/commit/151eb9d4c2ca44f739f3339a8ebe85e2916655f1
* **Python:** 3.13.5
* **Platform:** darwin-sequoia-m3

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by rbberger** [comment]
Probably related to https://github.com/spack/spack/issues/34961

**Comment by hughcars** [comment]
@rbberger This is causing quite a lot of friction in using spack to maintain/distribute Palace, how can we get this addressed?

**Comment by rbberger** [comment]
@hughcars was this retested with the changes since https://github.com/spack/spack/pull/52675? The issue I mentioned might have been resolved in part, so it would be good to know if this is happening with v1.2 and `develop`.

**Comment by Sbozzolo** [comment]
> [@hughcars](https://github.com/hughcars) was this retested with the changes since [#52675](https://github.com/spack/spack/pull/52675)? The issue I mentioned might have been resolved in part, so it would be good to know if this is happening with v1.2 and `develop`.

Yes, I retested this with develop last week and the problem is still there

**Comment by hughcars** [comment]
This still reproduces on v1.2.2, which includes #52675. I've opened #53107 with a fix and regression tests. @rbberger @psakievich, could one of you please review it? Palace pins `releases/v1.2`, so a v1.2 backport would let us drop our mfem-symlink workaround.
